### ISSUE TITLE
App does not work (location)

### ISSUE THREAD

**Issue by marceljay** [corona-warn-app/cwa-app-android#1068]
Referencing https://github.com/corona-warn-app/cwa-app-android/issues/524 from this repository and one I opened in the API's repo https://github.com/google/exposure-notifications-android/issues/49

This obviously has to do with Google's API, but maybe there is a way around it. I will not use the app anymore, if I have to share my location. Too many apps harvest the device's location data so I want to have my location turned off 99,9% of the time. 

![2020-08-23 19 50 47](https://user-images.githubusercontent.com/37071670/90985128-1cca1d00-e57a-11ea-9e16-ed7e7d4cc215.jpg)

**Comment by MikeMcC399** [comment]
Hi @marceljay 

You might like to read through the wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/160 "App does not work any longer if GPS is deactivated" where you can find some up-to-date references and tips.

**Comment by daimpi** [comment]
What @MikeMcC399 said ^

If you want a detailed explanation on why you need location enabled, see my thread [here](https://threadreaderapp.com/thread/1293947837567336450.html) (German) and the CWA [FAQ entry](https://www.coronawarn.app/en/faq/#android_location) on this topic 🙂.

**Comment by svengabr** [comment]
Thank you, everyone, for your feedback.

According to the [Exposure Notification release notes](https://developers.google.com/android/exposure-notifications/release-notes#locationless_scanning), the bug will be fixed in an upcoming Android release. There is currently no workaround possible for this issue.

> ### Locationless scanning
>With Android 11, version 1.6 and higher of Exposure Notifications works without having to enable Location Services. This means there are now additional cases in which it is not necessary to prompt users to manually enable this setting.

As @MikeMcC399 already mentioned, there is an open discussion here as well https://github.com/corona-warn-app/cwa-wishlist/issues/160

Since there is no workaround possible, this issue will be closed.

Best regards,
SG

Corona-Warn-App Open Source Team
