### ISSUE TITLE
Wrong "Aktualisierung"-Date after reboot if Date/Time was changed before to a future date

### ISSUE THREAD

**Issue by buergerapp** [corona-warn-app/cwa-app-android#1129]
## Describe the bug
-i changed the date to a future date several times to get bonus in a game-app (Terarium)
-i switched back to automatical time
-then i restarted the handy
-then i started the Corona-App
-Now it says: "Aktualisiert Morgen, 14:13" 

## Expected behaviour
Show the last update date/time which cannot be in the future

## Steps to reproduce the issue
Close Corona-App
Set Date to manual
Change one or two days back
Start the Cortona App
Now it shows "Morgen" or "Übermorgen"

![Screenshot_20200908_164423_de rki coronawarnapp](https://user-images.githubusercontent.com/67011857/92492658-e46e4400-f1f3-11ea-934a-635a3442b2fd.jpg)

## Technical details

- Mobile device:
Huawei Mate 10 Pro
- Android version: 10

**Comment by thomasaugsten** [comment]
We strongly not modify the date of your device. The wrong date in the Risikoermittlung ist not a big problem you will only see a wrong refresh time. But wrong date/time will cause problem in the ssl chain and also it will cause the creation of multiple TEK per day which leads to submit problem.

**Comment by buergerapp** [comment]
Why does it not simply show an error if the date is in the future which is never possible?

**Comment by buergerapp** [comment]
Is it correct that it could be possible that the App detects a positive beacon twice when changing the date backwards? This could then lead to a higher displayed risk if the two positive Hashs are submited twice. 
Or more then twice if changing time 20x one hour back followed by an Update.

**Comment by thomasaugsten** [comment]
Because the app is relying on the OS information which should provide the correct date. We could double check with a external provider but we cannot correct the date of the OS and it is more important to have exposure check than a correct time.
I think the os stores RPIs based on the id not on the date/time they collect it.

**Comment by buergerapp** [comment]
Possible alternative: 
Is the return of getTimeInMillis() also changing when the date is changed? Or is this timer running hardcoded on the processor?

**Comment by daimpi** [comment]
Related to:
- https://github.com/corona-warn-app/cwa-wishlist/issues/88
- https://github.com/corona-warn-app/cwa-app-ios/issues/1097

**Comment by svengabr** [comment]
Hello @buergerapp, thank you for your feedback.

As @daimpi already mentioned there is already a wishlist entry for this issue here:
[Active time is easy to fake #88](https://github.com/corona-warn-app/cwa-wishlist/issues/88)

To keep our GitHub issues cleaner I will close this issue.

Best regards,
SG

Corona-Warn-App Open Source Team
