### ISSUE TITLE
Auf Samsung Handy seit 2 Wochen Fehlermeldung 39508

### ISSUE THREAD

**Issue by Gigglebug** [corona-warn-app/cwa-app-android#1130]
Ich habe seit ca 2 oder 3 Wochen diese Fehlermeldung auf meinem Samsung Handy obwohl sowohl das System, als auch der Playstore und die App selber auf dem neuesten Stand sind.

Alle 2-3 Tage aktualisiert sich die App mitten in der Nacht ohne dass ich sie aufrufe.

Ich habe sie für gewöhnlich im Hintergrund aktiv und auch die Risikoermittlung ist dauerhaft aktiv.

**Comment by marcohabeck** [comment]
https://github.com/corona-warn-app/cwa-app-android/issues/1021

**Comment by daimpi** [comment]
@Gigglebug 
Das ist ein rate-limiting Error, also im Endeffekt hat die App heute bereits zu häufig versucht auf ein bestimmte API Funktion zuzugreifen. Was da normalerweise hilft: App beenden -> 24h warten -> App wieder öffnen

Das limit wird nämlich jeden Tag wieder zurückgesetzt.

Hier ist der dazugehörige FAQ entry: https://www.coronawarn.app/de/faq/#API39508, das entsprechende GH issue hat @marcohabeck ja bereits verlinkt 🙂.

**Comment by Gigglebug** [comment]
Da stand Haufenweise Zeug was ich alles nicht verstanden hab. Ich spreche kein PC-Sprech, tut mir leid. 

Auf dem FAQ stand wenn das Problem weiter besteht und man alles da getan hat (ausschlaten, updates ect) soll man ein Issue auf Github aufmachen. Hab ich gemacht.

**Comment by thomasaugsten** [comment]
In den nächsten Tagen kommt ein Update was den Fehler minimieren sollte. Die Risikoberechnung funktioniert trotzdem einfach auf das nächste Updaten dann ist der Fehler weg.

**Comment by marcohabeck** [comment]
Das Update ist schon längst ausgerollt. Allerdings ist das eigentliche Problem nicht behoben, nur kaschiert.  Die App auf keinen Fall deinstallieren ! Da sonst alle Daten gelöscht werden. Das ENF arbeitet im im Hintergrund weiter!  Was Probleme macht ist die Verbindung der App zum ENF…

**Comment by thomasaugsten** [comment]
Ich rede von dem Update 1.3.1 was in den nächsten Tagen erscheinen wird, die Version wird das Problem beheben. Bitte ein wenig Geduld und das Tages Limit ignorieren. Die App funktioniert trotzdem weiter.

**Comment by Gigglebug** [comment]
Alles klar, vielen Dank (auch für die Erklärungen). Dann warte ich einfach noch etwas.

**Comment by svengabr** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1021

**Comment by svengabr** [comment]
As already discussed this issue is flagged as a duplicate. I will close this issue and kindly ask you to contribute to the already existing issues instead:

* [CAUSE: 3 Something went wrong. ApiException: 39508 #1021](https://github.com/corona-warn-app/cwa-app-android/issues/1021)
* [Resetting the CWA triggers error 39508 #934](https://github.com/corona-warn-app/cwa-app-android/issues/934)
* [Fehler bei Kommunikation mit Google API (39508) #774](https://github.com/corona-warn-app/cwa-app-android/issues/774)
* [Risikostatus wird nicht aktualisiert #1119](https://github.com/corona-warn-app/cwa-app-android/issues/1119)

Most of the issues are tackled with the upcoming hotfix release 1.3.1 which will be released within the next days.

Best regards,
SG

Corona-Warn-App Open Source Team
