### ISSUE TITLE
3 Exposures but 13 matchescount:1

### ISSUE THREAD

**Issue by SamsoniteS86** [corona-warn-app/cwa-app-android#1217]
Hey, 

The last days (4 days ago) I recognized "3 Begegnungen mit geringem Risiko". 
Then I checked the json file and found 10 times "matchescount":1. 
Today I checked again and it was 13 times but still 3 Exposures visible in the App. 
And today I met no one. 

I already called the hotline but also the second level couldn't help. 

Has anyone the same issue? 

Kind regards, 
Sam

![Screenshot_20200923_125916_de rki coronawarnapp](https://user-images.githubusercontent.com/71758592/94004714-68503080-fd9d-11ea-810b-e1c2fb368b9c.jpg)
![Screenshot_20200923_130644_com google android apps docs editors docs](https://user-images.githubusercontent.com/71758592/94004892-ac433580-fd9d-11ea-90a2-b6ac09b102a3.jpg)

**Comment by daimpi** [comment]
Could you share your ENF log here (you can either put it into a .zip archive or rename the ending from .json to .txt), then we can take a closer look at this.

**Comment by SamsoniteS86** [comment]
I renamed it to txt 
[all-exposure-checks.txt](https://github.com/corona-warn-app/cwa-app-android/files/5268159/all-exposure-checks.txt)

**Comment by daimpi** [comment]
Thanks 🙂.
I've put your log file into the [EN analyzer](https://felixlen.github.io/ena_log/) and got the following output:
![grafik](https://user-images.githubusercontent.com/22129968/94015832-ab1a0480-fdad-11ea-8f56-69fe25b1b3e6.png)

This means your CWA display is correct. You had three encounters (and in this case) with 3 different ppl who later tested positive:
- The first person uploaded their keys on the September 15th.
- The second person uploaded their keys on Sept 16th.
- The third person uploaded their keys on Sept 18th.

Those matches will show up in your ENF log each time your CWA performs a check until the respective encounter lies more than 14 days in the past.

**Comment by SamsoniteS86** [comment]
Okay thank you very much!
But then I have some follow up questions :) 
I.e. The second one. 
Match at the 16. and Überprüfungszeitpunkt 20., 21.,...? What does that mean?
And second questions:
You wrote:
"The first person uploaded their keys on the September 15th."
What do you mean with "uploaded their keys? Is this the date of our match or the date when the person entered the positive test into the app? 

Thanks a lot for your answers.

**Comment by daimpi** [comment]
> I.e. The second one.
Match at the 16. and Überprüfungszeitpunkt 20., 21.,...? What does that mean?

This means the person you had this encounter with uploaded their keys (more on this below) on the 16th. The actual encounter therefore must have happened on the 15th or earlier. Given that encounters will not be displayed anymore if they lie more than 14 days in the past (counting from the actual time of the encounter) in either CWA or the ENF log, we can even narrow the window further: the match showed up in todays checks (23.9.2020, 08:23) which means the actual encounter mustn't be more than 14 days in the past from this timestamp. This limits the window for this encounter from anywhere between the 9th and the 15th. If this match still shows up tomorrow you can further limit the window of the encounter to between 10th and 15th etc… until the day when the match disappears, at which point you'll know that this encounter must have happened ~15 days before. 

Regarding "Überprüfungszeitpunkt": this is what is labeled `timestamp` in your logfile: It's the time when your CWA downloaded keys from the server and handed them over to the Exposure Notification Framework (ENF) to check for a match ([FAQ Entry](https://www.coronawarn.app/en/faq/#keys_matches)). Usually this should happen once a day and b/c it always checks for encounters in the past 14 days there should be 14 entries each day ([one for each previous day](https://www.coronawarn.app/en/faq/#multiple_exposure_checks)).
One thing which is a bit strange in your log is that there are no entries for the days between the 16th and 20th. Did you maybe have your phone turned off or did you not have internet connection on those days?


> "The first person uploaded their keys on the September 15th."
What do you mean with "uploaded their keys? 

Every day ppl get their test results and if they tested positive they can then decide to share their keys for the past 14 days in order to warn others. If they do, their keys are uploaded to the server. The day when this happens is what I was referring to when I said "x person uploaded their keys on y date" and it's also what you can see in the EN analyzer output as "Schlüsseldatei vom y". Those keys are then downloaded the next day by all the CWA apps which then check whether there is a match between the rolling proximity identifiers (RPIs) they have recorded (from contact with other phones) and the diagnosis keys (DKs) (which they have just downloaded from the server).

> Is this the date of our match or the date when the person entered the positive test into the app?

The latter: It's unfortunately not the time when you actually had the encounter. This information is currently only shown for "red exposures" by CWA (feel free to upvote https://github.com/corona-warn-app/cwa-wishlist/issues/178 to also get this info for green encounters).
But you can narrow the time window for when the encounter must have happened by the "waiting method" I described in the first paragraph.

**Comment by svengabr** [comment]
Thank you very much @daimpi for your help here!

When reading through the comments, I dont see an actual action item resulting from this conversation.

I will close this issue to keep the list clean.

Best regards,
SG

Corona-Warn-App Open Source Team
