### ISSUE TITLE
App takes long to launch

### ISSUE THREAD

**Issue by ucmichan** [corona-warn-app/cwa-app-android#1222]
It takes ca 10 seconds to launch the app and to show the risk status. This happens since the last update of the app.

Device:
Galaxy A6 (a6lte)
Android 10

---
Internal Tracking ID: EXPOSUREAPP-2837

**Comment by GPclips** [comment]
Hello @ucmichan ,

does this issue still occur? 
@abro1i do we have any update on this?

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by phpman89** [comment]
I have the same problem with version 1.5 on my Mi 9 with MIUI 12 / Android 10

**Comment by daimpi** [comment]
@phpman89 thanks for sharing your screen recording. Does this issue appear every time you try to open CWA or was this a one off?

**Comment by phpman89** [comment]
Unfortunately the issue appear every time I open the CWA.

**Comment by daimpi** [comment]
@phpman89 thanks the devs probably have to take a look at that 🙂. 

(cc @GPclips @abro1i)

**Comment by ralfgehrer** [comment]
This was very likely fixed with https://github.com/corona-warn-app/cwa-app-android/pull/1857 by @d4rken 

The update check during app launch could happen on the main thread, blocking the UI.
Further changes to app config behavior should also have a positive effect on this.

Hence, we would consider this as being addressed and closed, @JoachimFritsch .

**Comment by dsarkar** [comment]
Hi @ucmichan, this issue should be fixed now. We would appreciate your feedback. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Since there is no more feedback on this, I assume the issue is fixed. We are therefore closing this issue.

----
Corona-Warn-App Open Source Team
