### ISSUE TITLE
"This app is incompatible with all of your devices." (via web)  / App not visible for non-German/-EU Google accounts (via play store)

### ISSUE THREAD

**Issue by thanatha** [corona-warn-app/cwa-app-android#1265]
![image](https://user-images.githubusercontent.com/72132561/94671490-3d715980-0314-11eb-988e-55ba4a1a72da.png)

it seems - even with recent changes to include EU countries - that Google accounts that are not initiated/set-up in Germany/the EU causes the App to be not visible in Google's Play Store, with those non-EU accounts. 
I suspect that - at signing up to a Google account - Google logs in which geo-zone/country it has been set up, and embeds this info into the account directly.
Since the App is set to show up only for Germany/EU countries, this will leave out a lot (at least a million accordig to CIA's World Factbook) of migrants and refugees that are currently living in Germany.

a possible solution would be, allow it to be installed by anyone, and checking local GPS/cellular tower data/IMSI data (considering one has to be paying a local Telco if one lives in the country, if not, s/he/they've definitely ROAMING status on the network) to determine if someone is eglible to use the app.

I speak out of experience; my wife (American) and myself (lived for 15 years in the U.S.) are unable to get the app via our Google accounts, being initiated in the U.S. but living in Germany for years now.

**Comment by MikeMcC399** [comment]
@thanatha 
If you are permanently resident in Germany, then you can change your Google Play account to be in Germany.
There are instructions on how to change the country on https://support.google.com/googleplay/answer/7431675?hl=en

**Comment by daimpi** [comment]
@thanatha 
What @MikeMcC399  said ^

Additionally: see this FAQ entry: https://www.coronawarn.app/en/faq/#international

And feel free to upvote US availability here: https://github.com/corona-warn-app/cwa-wishlist/issues/41

**Comment by MikeMcC399** [comment]
Thanks to @daimpi for pointing to the [FAQ]( https://www.coronawarn.app/en/faq/#international) and to the [wishlist](corona-warn-app/cwa-wishlist#41) :smile:.

Also, as mentioned elsewhere today by @vaubaehn https://github.com/corona-warn-app/cwa-app-android/issues/510#issuecomment-701231812 you can also sideload the app from https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/ as a work-around. You would have to update the app manually when new versions are released though. The preferred solution is to change your Google Play country to Germany.

**Comment by thanatha** [comment]
thank you for all your prompt replies. Much appreciated.
Problem is, if you switch your Google account to a different nation, you'll loose certain services/content (i.e. Books/Movies what not). For us that's normally not an issue.
But what is an issue, for us, is loosing our Google VOICE accounts, as it is the only way for my wifes' older relatives to get hold of us directly. They do not know how to use smartphones. They just know how to call our Google VOICE phone numbers, and it gets redirected to our smartphones (or via the webbased interface). Google VOICE doesn't exist in Germany. It never will - Telekom & Co made sure of that.
So in light of what's currently happening in the U.S. (we all watch the news), I'm sure you know what our choice in this matter is.

cheers

**Comment by MikeMcC399** [comment]
@thanatha 
I'm sorry to hear that Google VOICE and family needs are limiting your choices. 

If your question has been answered, then perhaps you would like to close this issue? If https://github.com/corona-warn-app/cwa-wishlist/issues/41 doesn't cover your request, then you could [open a new wishlist item](https://github.com/corona-warn-app/cwa-wishlist/issues/new/choose).

**Comment by BIGFAAT** [comment]
> 
> 
> Thanks to @daimpi for pointing to the [FAQ](https://www.coronawarn.app/en/faq/#international) and to the [wishlist](corona-warn-app/cwa-wishlist#41) 😄.
> 
> Also, as mentioned elsewhere today by @vaubaehn [#510 (comment)](https://github.com/corona-warn-app/cwa-app-android/issues/510#issuecomment-701231812) you can also sideload the app from https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/ as a work-around. You would have to update the app manually when new versions are released though. The preferred solution is to change your Google Play country to Germany.

Isn't there a way to put the App in Fdroid?

**Comment by MikeMcC399** [comment]
@BIGFAT 
> Isn't there a way to put the app in F-Droid?

The question about F-Droid is discussed in the [FAQs](https://www.coronawarn.app/en/faq/#apk). This has some references in it, however the text seems to be a little out of date. The discussion about F-Droid took place in the issue https://github.com/corona-warn-app/cwa-documentation/issues/5 , which is closed with the label `wontfix`. See https://github.com/corona-warn-app/cwa-documentation/issues/5#issuecomment-627860999 for a summary.

**Comment by wmmccreedy** [comment]
I don't think that saying to just "change your country to Germany" is an acceptable answer.

1. Not everyone is tech savvy, how do you expect normal people to even figure out that the app isn't showing up because they don't have a German account? Most people don't even know that the Play store Apps can be region-locked. I arrived in Germany on Saturday, and all they give you is a piece of paper that says "Here, download this app and enter this code to get your results, it is super easy".
2. Even if you figure out you need to change your account to Germany, you can't unless you have a German form of payment. Sure, you could argue that if you've been here a while that you should have this or can set this up, but this App is most likely initially going to be used by people coming in to the country who don't have this. Even worse, as someone in quarantine while waiting for my results (which I need the App to check), I can't go out and get a German form of payment because I'm in quarantine. Do you see the issue?

If you are truly trying to prevent the spread of Corona, fixing this is imperative to getting it out to as many people as possible. You can't just assume that only established German residents will use it.

**Comment by MikeMcC399** [comment]
@wmmccreedy 
Is there anything the community here can help you with in the short term?
Which country are you coming from?

**Comment by wmmccreedy** [comment]
I'm coming from the US. I did end up sideloading the app per the instructions above and that helped my personal situation, but again this is something that I wouldn't expect a normal person to have to do to get the app.

**Comment by MikeMcC399** [comment]
@wmmccreedy 
I just realised that you are almost my namesake :grin: !
I'm glad to hear anyway that you've been able to sideload.

I do agree with you that people coming from USA should have an easier time. I don't know if it will make any difference, but you can always add to the corresponding wish-list item https://github.com/corona-warn-app/cwa-wishlist/issues/41 and it seems that it is mainly a legal issue.

I hope everything goes well for you in and after quarantine! 🤞

**Comment by wmmccreedy** [comment]
Haha yep I noticed that as well. First one of us I have run in to in the wild :) 

Unfortunately, I agree that it is a legal issue, I just wanted to make sure that it is known that the current workarounds aren't perfect. Thanks for taking the time to respond, I really appreciate it. Hopefully this gets resolved soon

**Comment by ckujau** [comment]
@mtwalli can you explain why this was closed? What's the blocker here? So far all I've read were some hand waving "legal concerns" preventing CWA to be able to show up in non-German Play Stores, but nothing substantial has been described, or maybe I missed it?

**Comment by mtwalli** [comment]
@ckujau  There are  already many issues in the wishlist which cover this topic see: 
https://github.com/corona-warn-app/cwa-wishlist/issues/143
https://github.com/corona-warn-app/cwa-wishlist/issues/38
[https://github.com/corona-warn-app/cwa-wishlist/issues/105](https://github.com/corona-warn-app/cwa-wishlist/issues/143)
https://github.com/corona-warn-app/cwa-wishlist/issues/41
https://github.com/corona-warn-app/cwa-wishlist/issues/93
https://github.com/corona-warn-app/cwa-wishlist/issues/85
https://github.com/corona-warn-app/cwa-wishlist/issues/79
https://github.com/corona-warn-app/cwa-wishlist/issues/63
https://github.com/corona-warn-app/cwa-wishlist/issues/58
https://github.com/corona-warn-app/cwa-wishlist/issues/56
https://github.com/corona-warn-app/cwa-wishlist/issues/51
https://github.com/corona-warn-app/cwa-wishlist/issues/46
https://github.com/corona-warn-app/cwa-wishlist/issues/45
https://github.com/corona-warn-app/cwa-wishlist/issues/43
https://github.com/corona-warn-app/cwa-wishlist/issues/42

Since this is not an Android specific issue but also concerns iOS. I closed this one here as duplicate.
