### ISSUE TITLE
Cause: 3 Something went wrong 

### ISSUE THREAD

**Issue by Iguzjo** [corona-warn-app/cwa-app-android#1300]
Guten Tag 

Ich habe ein Problem und ich finde leider nicht keine Lösung. 

![1601661228864](https://user-images.githubusercontent.com/72274026/94954176-0607d600-04e9-11eb-89e5-0207a5d1ddec.jpg)

![1601661254799](https://user-images.githubusercontent.com/72274026/94954234-2172e100-04e9-11eb-8e53-95e5cbc78e09.jpg)

Ich warte auf Ihre Antwort.

Xiaomi MI8
Android 10

Danke in voraus

**Comment by daimpi** [comment]
Das ist ein rate-limiting Error, also im Endeffekt hat die App heute bereits zu häufig versucht auf ein bestimmte API Funktion zuzugreifen. Was da normalerweise hilft: App beenden -> 24h warten -> App wieder öffnen

Das Limit wird nämlich jeden Tag wieder zurückgesetzt.

Hier findest du den dazugehörigen FAQ Eintrag: https://www.coronawarn.app/de/faq/#API39508 

Und hier ist das entsprechende Github issue in dem das Problem getrackt wird: https://github.com/corona-warn-app/cwa-app-android/issues/1021

**Comment by daimpi** [comment]
Duplicate of #1021

**Comment by heinezen** [comment]
Hey @Iguzjo,

Thanks for your feedback. Your bug is the same as in #1021, so I will close your issue as a duplicate. If you have further questions or feedback, please follow the link and continue the discussion there. In #1021, we will also post updates or news on the issue once they become available.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Duplicate of #1021
