### ISSUE TITLE
Wrong date for exposure checks (ApiException: 39508)

### ISSUE THREAD

**Issue by chrisschober** [corona-warn-app/cwa-app-android#1376]
## Avoid duplicates
* [x ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
Yes, but it says: If it still occurs afterwards, please call the hotline or **open an issue on GitHub**.
* [x ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x ] Bug is not already reported in another issue

## Describe the bug

The risk status has not been updated for a few days (Oct. 4th) and also the date for the last actualisation (Oct. 17th) is not correct.

![App1](https://user-images.githubusercontent.com/72634060/95640117-81dec100-0a9b-11eb-98ee-e5e4da3a37b2.png)

The following error message appears:

![App2](https://user-images.githubusercontent.com/72634060/95640127-91f6a080-0a9b-11eb-99ac-81b8bcd60c2f.png)

![App3](https://user-images.githubusercontent.com/72634060/95640136-9a4edb80-0a9b-11eb-9ca7-feb167c8a606.png)

Keeping the app closed for more than 24 hours, as described in the issue https://www.coronawarn.app/en/faq/#API39508, did not help either. The date and time on the smartphone is correct, I have no idea why there is Oct. 17th.

Here are the exposure checks perhaps it can help:

[all-exposure-checks.zip](https://github.com/corona-warn-app/cwa-app-android/files/5358123/all-exposure-checks.zip)

## Expected behaviour

I expect the risk status update to run correctly once a day.

## Steps to reproduce the issue

Open the app and click on the start screen, then the error message that can be seen in the screenshot above will appear.

## Technical details

- Mobile device: Google Pixel 3a
- Android version: 11

![AndroidVersion](https://user-images.githubusercontent.com/72634060/95640312-89529a00-0a9c-11eb-9dc5-7ede038f6277.png)

## Possible Fix

Somehow the wrong date in the Corona app (October 17th) seems to be causing the problem.
Is the date checked when the risk status is updated? If e.g. checks whether there is newer data than the last update and the date in the future means that it no longer works?

## Additional context

----
Internal Tracking ID: EXPOSUREAPP-3178

**Comment by MikeMcC399** [comment]
Hi @chrisschober 

You have an interesting combination of problems! The new Android 11 operating system may be contributing here, in addition to a couple of known issues. Android 11 is being seen on Google devices first, whilst other manufacturers prepare their update rollouts.

The timestamp "17. Oktober 2020, 22:17" is listed in the [all-exposure-checks.zip](https://github.com/corona-warn-app/cwa-app-android/files/5358123/all-exposure-checks.zip) so the phone must have had that date/time set when it tried to pull the keys from the server. I imagine it got this time (incorrectly) from the network, so to temporarily keep a stable time, you might want to disable "Zeit aus Netzwerk verwenden" and "Zeitzone aus Netzwerk verwenden" in Android system settings, checking afterwards that the date/time/timezone are correct.

The quota of 20 (14+6) was exceeded on Oct 4, 2020, so I can't explain why you still get the 39508 error on Oct 9/10, 2020.

Date | Count
-- | --
4\.   Oktober 2020, 02:23 | 14
4\. Oktober 2020, 22:18 | 6

Although the time 22:17 on Oct 17 is suspiciously close to the time 22:18 on Oct 4, so possibly the time jumped forwards and then backwards again.

Date | Count
-- | --
17\.   Oktober 2020, 22:17 | 14

Google resets the quota daily at 00:00 UTC, which is currently 02:00 local German CEST time. [Reference: Google API documentation](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#modes). If you open CWA manually today, you may find that the 39508 error no longer occurs. Your screenshots show a time of 01:23 shortly before the daily quota reset at 02:00.

The other workarounds you might like to try are:

- connect your phone to a charger overnight and leave the phone running with either WLAN or data access. In this case CWA will try to retrieve keys at a random time soon after 02:00 CEST (typically between 02:00 and 03:00).
- open CWA daily manually to check that updates have been done (Aktualisierung) and if they have not been done overnight then opening the app will trigger a manual update.

For reference, let me give the links to two relevant open issues:
"Background update does not work, despite v.1.1.1 and “prioritized background activity”" #933 
"CAUSE: 3 Something went wrong. ApiException: 39508" #1021

**Comment by heinezen** [comment]
Hello @chrisschober ,

I have updated the title of your issue to better reflect the problem you have. The issue has also been mirrored to the internal Jira with ticket ID EXPOSUREAPP-3178. It will now be investigated by the devs.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by tomanku** [comment]
Hello, my issue is similar (Huawei ALE-L21, Android 6).
After the App stopped to update the "last updated" risk status for nearly 2 weeks and indicating error 39508 daily, I tried the workarounds but finally re-installed the app, losing the data   :-(
This didnt help either. During the first 2 days, it downloaded 0 keys for 20 times each day.
On the 3rd day, a mixture of zero-key and non-zero-key downloads happened.
Since then, a 6-digit number of keys id downloaded, but the app still gives the installation time as time of last risk update.
Error 39508 ist still present.

**Comment by MikeMcC399** [comment]
@tomanku 
Is your app updated to version 1.5.0?

**Comment by tomanku** [comment]
@MikeMcC399 , yes, updated from 1.3.1 to 1.5.0 since today

**Comment by MikeMcC399** [comment]
@tomanku 
Great! 👍 
You may need to wait until tomorrow morning 02:00 CEST (00:00 UTC) to see any improvement because that is when the daily quota causing the 39508 error is reset.
If you still get an error tomorrow use the "export exposure checks" function and post the all-exposure-checks.json file here (either rename the extension to .txt or zip it). Your zero-key comment makes me suspicious there is something else going wrong.

Also you might want to monitor the main thread on the 39508 error https://github.com/corona-warn-app/cwa-app-android/issues/1021.

**Comment by chrisschober** [comment]
Here is a quick update from me.
Since October 17th is over, the update has been working again and no error messages appear.
Everything else hadn't helped.

**Comment by tomanku** [comment]
As of today, after 1 day with v1.5.0, it seems to be working again. Looks good for the moment ....

**Comment by MikeMcC399** [comment]
@chrisschober 
> Here is a quick update from me.
> Since October 17th is over, the update has been working again and no error messages appear.
> Everything else hadn't helped.

If everything is now working, would you like to close this issue now?

**Comment by dsarkar** [comment]
Dear community,

my understanding is that this issue is related to ApiExeption 39508, which was resolved in release 1.5. This issue will be closed now.
Should you experience any further issues related to ApiExeption 39508 even after updating to app version 1.5, please report here https://github.com/corona-warn-app/cwa-app-android/issues/1459.

Many thanks to all contributors, 
DS

Corona-Warn-App Open Source Team
