### ISSUE TITLE
Ursache 3: etwas schief gelaufen, 39508

### ISSUE THREAD

**Issue by gaziwo** [corona-warn-app/cwa-app-android#1423]
mobile device: SM-G800F
Android version: 6.0.1
Corona App: 1.3.1
last update risk status : Oct. 10th

happend several times before, but with the current release, the bug was gone. Now it is back again.

**Comment by PapaBravo** [comment]
mobile device: Pixel 3
Android version: 11 (Build RP1A.201005.004)
Corona App: 1.3.1

Same problem. Never had any problems before.
![cwa](https://user-images.githubusercontent.com/2863907/96365329-1acaa780-1140-11eb-8204-200cd1a40978.png)

**Comment by daimpi** [comment]
@gaziwo does the error message look something like this?

<img src="https://user-images.githubusercontent.com/22129968/96158596-f7bbb000-0f13-11eb-9cc8-ff3f42bfbc0f.png" width="300">

In particular: does it mention the number 39508? If so: this issue is tracked here: https://github.com/corona-warn-app/cwa-app-android/issues/1021
CWA 1.5 contains a patch for the issue and should hit the play-store on tomorrow.

**Comment by daimpi** [comment]
@PapaBravo your issue is probably different from @gaziwo: you're probably encountering https://github.com/corona-warn-app/cwa-app-android/issues/1304.

To [quote](https://github.com/corona-warn-app/cwa-app-android/issues/1304#issuecomment-705567529) @thomasaugsten:
> The issue is related to Android 11 and GMS. 20.26.XX it will fixed in the next Google Play Service release

Which Google Play Service version do you have?

**Comment by gaziwo** [comment]
Hallo Daniel Frey,

yes indeed.

Thank you for your kind answer and I´m looking forward to updating CWA tomorrow.

Have a nice Sunday afternoon.

Silke Flatow

 

 

Von: Daniel Frey <notifications@github.com> 
Gesendet: Sonntag, 18. Oktober 2020 13:30
An: corona-warn-app/cwa-app-android <cwa-app-android@noreply.github.com>
Cc: gaziwo <silke.flatow@t-online.de>; Mention <mention@noreply.github.com>
Betreff: Re: [corona-warn-app/cwa-app-android] Ursache 3: etwas schief gelaufen, 39508 (#1423)

 

@gaziwo <https://github.com/gaziwo>  does the error message look something like this?

 <https://user-images.githubusercontent.com/22129968/96158596-f7bbb000-0f13-11eb-9cc8-ff3f42bfbc0f.png> 

In particular: does it mention the number 39508? If so: this issue is tracked here: #1021 <https://github.com/corona-warn-app/cwa-app-android/issues/1021> 
CWA 1.5 contains a patch for the issue and should hit the play-store on tomorrow.
