### ISSUE TITLE
Only one encounter entry every day

### ISSUE THREAD

**Issue by FrankfurterRadler** [corona-warn-app/cwa-app-android#1471]
Samsung A5
Android 7.0
CWA 1.5.0 (prioritized background activity in on)

I've been using the app continuously since it was first released in June. But since the update  on Oct. 19th to 1.5.0 I only see only one entry for the encounter check every day (see screenshot). 

![image](https://user-images.githubusercontent.com/36239646/97100851-31b94e80-1698-11eb-819f-08bb290597b0.png)

Before the update I saw 14 entries per day here. That unsettles me a lot. Restarting the smartphone did not help. I can't think of any other possible solution.

**Comment by MikeMcC399** [comment]
@FrankfurterRadler 
What you are seeing is correct. It is not a bug!

The handling of the keys has been made more efficient in V1.5.0 so instead of making 14 calls, it only makes one a day. There are a lot more keys in the one call, which you can check by opening one of the new entries and comparing to one of the old entries before you updated to V1.5.0.

Anyway, there is no need to worry!

**Comment by daimpi** [comment]
@FrankfurterRadler I second what @MikeMcC399 said above ^

Instead of handing over 14 separate packages potentially DoS'ing ENF and causing timeouts, CWA 1.5 under Android now submits all packages in one batch (cf. PR [1088](https://github.com/corona-warn-app/cwa-app-android/pull/1088), PR [1150](https://github.com/corona-warn-app/cwa-app-android/pull/1150)).

**Comment by FrankfurterRadler** [comment]
Ah! Many thanks for your helpful answers.
