### ISSUE TITLE
One or four contacts?

### ISSUE THREAD

**Issue by SilverMeise** [corona-warn-app/cwa-app-android#1508]
I use CWA 1.5.1 under Android 10 with Google-Play-Services 20.39.15 and I see in the CWA-App "Niedriges Risiko", "1 Begegung mit niedrigem Risiko.

![Screenshot_20201030-073756](https://user-images.githubusercontent.com/68152733/97775864-544dda80-1b64-11eb-91d1-87686a90f9b7.png)

But if I see details in the "all-exposure-checks.json"-File with https://felixlen.github.io/ena_log/ I see 4 (four) contacts/hits, or in german "Begegnungen".

![31-10-_2020_10-26-08](https://user-images.githubusercontent.com/68152733/97775801-c70a8600-1b63-11eb-807f-4a5d98f8faeb.png)

Here the original-json-data:

![31-10-_2020_10-33-21](https://user-images.githubusercontent.com/68152733/97775904-a7279200-1b64-11eb-998f-b01fce618ea9.png)

What do the four entries in the json-file  (matchesCount) mean? Is it always the same (positively tested) person or are there 4 positively tested people? And why do I only see one (1) encounter in the CWA display?

**Comment by MikeMcC399** [comment]
@SilverMeise 

The most likely explanation is that it is one encounter i.e. one person. 

The json data is showing that the keys were checked once each day and they matched once on each day from Oct 28 to today Oct 31.
When this happened to me, the match disappeared on the fourth day and I was back to Low Risk again. It all depends on when the encounter happened and when the infection was reported.

There is a document on https://github.com/corona-warn-app/cwa-documentation/blob/master/cwa-risk-assessment.md which describes how the assessment is supposed to work, however I don't think that document is up-to-date because the submission is now supposed to include the additional information about Start of Symptoms beginning with version 1.5.0. At the moment there will be a mixture of Diagnosis Keys in the system from before and after the upgrade.

**Comment by heinezen** [comment]
Hey @SilverMeise 

@MikeMcC399 is likely correct that this is the same encounter and not 4 individual encounters. The CWA checks the key database once a day to find risk encounters. `matchesCount` is the total number of matches it found during the particular check on that day. It is not the number of new encounters.

Keys will be saved up to 14 days, so if a key is matched during the check on the 28th, it will also be matched on the 29th if it was not deleted then.

I hope this clarifies the stuation a bit.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by SilverMeise** [comment]
Many thanks for the comprehensive information. Now I'm curious when the message disappears again. It would be better if the APP would also name the period/day of contact.

**Comment by heinezen** [comment]
I am closing this issue now because the question was answered and resolved.
