### ISSUE TITLE
Reset App delays risk evaluation for one day "Unknown Risk"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1510]
## Avoid duplicates 
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Describe the bug
Using the Reset App function appears to delay risk evaluation for one day. In the meantime the "Unknown Risk" status is shown.

## Expected behaviour
CWA should re-evaluate the risk data and display the results without delay after a Reset App has been done.

## Steps to reproduce the issue

1. Install CWA, activate exposure logging and wait one day.
2. Open (Android) Settings > Google > COVID-19 exposure notifications > Exposure checks
check that there are exposure check log entries and make a note of the first date / time.
3. Open CWA > three-dot menu > Settings > Reset App
confirm RESET APP, RESET
4. Go through onboarding sequence
    1. LET'S GET STARTED
    2. NEXT
    3. ACTIVATE EXPOSURE LOGGING, Turn on
    4. NEXT
    5. NEXT, OK and ALLOW (& go back from OPTIMISE BATTERY USAGE)
5. Note that Unknown Risk card appears.
6. Check as in 2. above for exposure log entries. Note that the original entry/entries are still present and there is a new entry with a timestamp from the time that Activate Exposure Logging above was selected.

## Technical details

- Mobile device: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- Google Exposure Notification System (ENS) version: 18204516000
- CWA App version: 1.7.1

## Possible Fix

Check for usable key data in the Google ENS datastore, evaluate and display a risk if possible, without delay.

## Additional context

A similar situation can occur after using another ENS compatible app from another country, then moving to Germany and activating CWA. There will be key data in the ENS store which can be immediately evaluated without waiting one day. (Thanks to @ndegendogo for pointing this out.)

---
Internal Tracking ID: EXPOSUREAPP-3547

**Comment by otacke** [comment]
I can confirm the aforementioned behavior for:
* Mobile device: Samsung Galaxy S10 SM-G973F
* Android version: 10 (kernel version 4.14.113-19530501)
* Google Exposure Notification System (ENS) version: 17203915000

**Comment by daimpi** [comment]
One option to fix this would be to [drop the display of "Number of Active Days" completely](https://github.com/corona-warn-app/cwa-wishlist/issues/102) and immediately show a the screen with the results (feel free to upvote the linked issue).

Regarding
> Check for usable key data in the Google ENS datastore, evaluate and display a risk if possible, without delay.

I'm not sure whether CWA can actually do this at least in the currently used v1 legacy ENF mode. Afaik keys don't get exposed to CWA and are handled fully within ENF.

Just to also mention the workaround for this problem here:

1. Before you do the reset within CWA, set the date 1 day in the past in the settings of your phone (or 14 days in the past if you immediately want the "permanently active" status in CWA) and disable automatic time synchronization.
2. Reset the data within CWA: Open CWA > three-dot menu > Settings > Reset App 
confirm RESET APP, RESET
3. Go through onboarding sequence 
4. Note that Unknown Risk card appears
5. Change the time back to the current day and enable automatic time synchronization again in your phone settings.
6. Check CWA again and note that the risk evaluation has been active *permanently* or *for one day* depending on how you set the date in step (1) and CWA is showing you the results of previous encounters right away.

**Comment by MikeMcC399** [comment]
@daimpi 
>>Check for usable key data in the Google ENS datastore, evaluate and display a risk if possible, without delay.
>>
>I'm not sure whether CWA can actually do this at least in the currently used v1 legacy ENF mode. Afaik keys don't get exposed to CWA and are handled fully within ENF.

I didn't want to specify what methods to be used, since I'm not really confident in understanding the [API](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#methods) exactly. Hopefully it just means ignoring the one day delay and just immediately showing the results of the exposure check.

Thank you very much for listing the workaround!

In fact what is even more important, even if a user has already carried out a Reset App from inside the app, **they can do it one more time**, but the next time setting the clock back first, before doing a repeat reset and they will get the full risk card (without Unknown Risk) displayed!

**Comment by heinezen** [comment]
Thank you for the report @MikeMcC399 and @daimpi for the workaround.

I have mirrored the issue to Jira now (ticket ID: EXPOSUREAPP-3547). The devs will pick it up and look for a solution. We will notify you here, if we get any feedback on the bug.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
This issue is no longer reproducible with CWA Android 1.9.1.

After resetting the app and completing the onboarding sequence, the app displays in sequence:

- Data is being downloaded
- Check is running
- Low Risk

It no longer displays "Unknown Risk" after resetting the app. The final state is green Low Risk. 🚀

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for feedback.
