### ISSUE TITLE
[BSI][20201107] Unencrypted Storage of Data

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-app-android#1554]
Rating: Informational (Best Practice Violation)

Description:
The new update of the Android CWA app introduces a CalculationTracker class that tracks risk calculations and updates. For this, it creates and updates a JSON file on the device’s filesystem. The file does not directly store sensitive data, but stores data that is implicitly related to the user. Therefore, it is only considered as a best-practice violation.

Proof of concept:
The following excerpt contains an exemplary content of the calcuation_tracker/calculations.json file:
{"c444e6d0-c7bd-4d81-a876- 422f9296c10c":{"finishedAt":{"iMillis":1604655600587},"identifier":"c444e6d0-c7bd- 4d81-a876- 422f9296c10c","result":"NO_MATCHES","startedAt":{"iMillis":1604655599018}},"7453d6c4- 8b31-42fd-a620- 0666672f09b3":{"finishedAt":{"iMillis":1604670253917},"identifier":"7453d6c4-8b31- 42fd-a620-0666672f09b3","result":"NO_MATCHES","startedAt":{"iMillis":1604670251995}}}

Recommended controls:
The file should be encrypted similar to how other data within the app is encrypted. An example for this is the shared preferences file. All necessary functionalities are already given, so the implementation efforts should be low.

---
Internal Tracking ID: [EXPOSUREAPP-4323](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4323)

**Comment by d4rken** [comment]
Thanks for the recommendation.

The gain in security is marginal. The file is already stored in private storage. It would require a privilege escalation to root/system level to access it, and if an attacker has that kind of access, then this extra level of encryption is unlikely to stop the attacker from reading this data (or from getting the same information from the system directly).

> Recommended controls:
> The file should be encrypted similar to how other data within the app is encrypted. An example for this is the shared preferences file. All necessary functionalities are already given, so the implementation efforts should be low.

We've already had plenty of trouble with encryption issues breaking the app for users (e.g. #642), using the `necessary functionalities` that `are already given`.

I think that the costs outweigh the benefits here, and that the current implementation is appropriate.

**Comment by GisoSchroederSAP** [comment]
Again, thanks for reporting the finding with a detailed information. 
Since the related issues #1988 , #1989 , and #1907 all tackle the same finding and recommendations, but just different data objects, we will handle them with high priority for evaluation and for a proper solution design.

Still, I urgently ask @BSI-TF-CWA , to follow the agreed procedure documented in:
[https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md](url)
Following this path ensures the findings are addressed to the right team, so the required procedure and documentation becomes transparent and efficient. Otherwise we may lose time and generate additional communication effort with disclosure of sensitive information.

All GitHub issues (including #987) are already _converted_ into a respective internal work item that allows the experts to follow up.

Thanks, @BSI-TF-CWA, for your input and for following the agreed procedure as described here: [https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md](url)

**Comment by heinezen** [comment]
This issue is probably obsolete. Closed in favour of https://github.com/corona-warn-app/cwa-app-android/issues/2846

----
Corona-Warn-App Open Source Team
