### ISSUE TITLE
Improve UX for disabling battery optimization

### ISSUE THREAD

**Issue by timokau** [corona-warn-app/cwa-app-android#1606]
## Avoid duplicates
* [x] This enhancement request has not already been raised before (to the best of my knowledge, it's a bit hard to search for)
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation

Currently, corona-warn
- explains why battery optimization should be disabled and why that is okay
- suggests that the user disables it
- forwards the user to the settings if they chose to do so.

The problem is with the last step. It just leaves the user in the "battery optimization" setting, which by default just shows a list of apps that does not even include the Corona-Warn app (at least for me). You then have to chose "all apps" and search for Corona-Warn in a long list. Then you can finally select it and disable battery optimization.

I think this can be confusing for the user and might prevent them from disabling the battery optimization and/or leave them a bit confused.

## Suggested Enhancement

If I remember correctly, the [syncthing-android](https://github.com/syncthing/syncthing-android/) app was able to directly prompt me to disable battery optimization *for that app*. I just had to approve it, and it was done. Similar to a normal permission prompt. Corona-Warn should do it the same way.

Edit: For reference
- [Here](https://github.com/syncthing/syncthing-android/blob/9f646cc28b7ab40c1556d0d24e1348229e01da84/app/src/main/java/com/nutomic/syncthingandroid/activities/MainActivity.java#L132) is how synthing implements it.
- [Here](https://developer.android.com/reference/android/provider/Settings#ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS) is the relevant android documentation.

## Expected Benefits

More users will disable battery optimization and get warnings on time. As a "softer" benefit, more users will have a good first impression in the app (instead of feeling slightly confused and unsure if they might have messed up something when setting it up).

---
Internal Tracking ID: [EXPOSUREAPP-3835](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-3835)

**Comment by heinezen** [comment]
Hello @timokau 

Thank you for the suggestion. I have created a ticket in the internal Jira for your request (ticket ID: EXPOSUREAPP-3835) where it will now be discussed by the developers. They will decide how and when this change will be implemented. We will notify everyone here on Github if we get any news about the implementation progress of this request.

Best Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Note: I know that background exposure checking has been an ongoing issue to get it to work reliably on all Android devices, and I assume that the current implementation is the best compromise at this time.

But in any case, I made a comment relevant to this issue in https://github.com/corona-warn-app/cwa-app-android/issues/1884#issuecomment-744363225 regarding the complexity of the steps to enable Prioritised Background Activity, using the Android system UI.

In the following, PBA indicates enabled Prioritised Background Activity and "!" is a .not. operator:

CWA passes me to the Android system UI heading "Optimise battery usage" (= !PBA)
where I see the "Apps not optimised" filter  (= !!PBA = PBA)
where I select "All" filter (finds PBA and !PBA) which I need to use because there is no filter for "Apps optimised"
then I seek the Corona-Warn element which has a slider (!PBA), so to ENABLE Prioritised Background Activity I DISABLE the Corona-Warn slider.

This is all logical, but complex and confusing. I need to think hard any time I need to do it.

**Comment by MikeMcC399** [comment]
@timokau 
> If I remember correctly, the syncthing-android app was able to directly prompt me to disable battery optimization for that app. I just had to approve it, and it was done. Similar to a normal permission prompt. Corona-Warn should do it the same way.

Until and including version CWA Android 1.5.1 selecting ALLOW for Prioritized Background Activity directly disabled battery optimisation for the app. Because this didn't work well for all devices, there was an FAQ article  https://www.coronawarn.app/en/faq/#battery_optimization_background written to warn that it may be necessary to restart the device in order for the battery optimisation setting to become effective. I just checked this on an Android 11 emulator with version 1.5.1 and I had to carry out a cold boot on the device to get the setting to be applied, so that confirms the information in the FAQ.

Starting with CWA Android 1.6.0 selecting ALLOW for Prioritized Background Activity in CWA does not apply the OS battery optimisation setting for CWA directly, instead it puts the user into the Android Settings UI to allow the user to carry out the action themselves. The CWA UI instructions really don't tell the user what to do. That could perhaps be improved, or we could consider having this described in more detail in an FAQ article.

**Comment by timokau** [comment]
I think it would be preferable to have a simple "allow" prompt, even if it requires a reboot on "a limited number of Android devices". If it is possible to check for such devices / vendored OSes, the app could even have some special casing for those (ask them to reboot or open the settings dialog).

I think that would be better because

- rebooting is arguably easier than manually disabling battery optimization and
- in most cases, it will probably either work without rebooting or the user will reboot the device in some reasonable time.

There would be some cases where the setting doesn't apply and the user will not reboot for a long while. But I'm fairly certain those will be less than the amount of users that are currently put off by the confusing settings dialog.

**Comment by tomjschwanke** [comment]
The main problem are different UIs for different manufacturers. As @MikeMcC399 said, he has sliders on his Samsung device. I on the other hand have a different UI without sliders (see attached screenshots).
![Screenshot_20201222-210413.jpg](https://user-images.githubusercontent.com/12198004/102928947-f2da2600-4499-11eb-8ae1-ade82f4c01de.jpg)
![Screenshot_20201222-210421.jpg](https://user-images.githubusercontent.com/12198004/102928953-f5d51680-4499-11eb-8836-c27ee18f0359.jpg)

**Comment by daimpi** [comment]
In this context [the post](https://github.com/corona-warn-app/cwa-app-android/issues/925#issuecomment-664195652) by @ubuntudroid might also be relevant:
> There also is a library which helps routing the user to related settings screens on many devices: [judemanutd/AutoStarter](https://github.com/judemanutd/AutoStarter)
> 
> At the core it's just just a collection of setting intents.

**Comment by dsarkar** [comment]
Hi @daimpi, will forward your hint to the devs. Thanks. DS

**Comment by mtwalli** [comment]
No planned
