### ISSUE TITLE
CAUSE: 3 Something went wrong

### ISSUE THREAD

**Issue by haodengfrm2** [corona-warn-app/cwa-app-android#1645]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Mobile device: Meizu
- Android version: 7.1.2

## Additional context

---
Internal Tracking ID: EXPOSUREAPP-2410

**Comment by haodengfrm2** [comment]
![微信图片_20201118105014](https://user-images.githubusercontent.com/22814682/99514629-41247280-298c-11eb-9396-77a7504d809d.jpg)
![微信图片_20201118105010](https://user-images.githubusercontent.com/22814682/99514631-41bd0900-298c-11eb-9e30-024eff1cc819.jpg)

**Comment by haodengfrm2** [comment]
Dear Dsarkar,
I'm using 1.6.0. I don't understand the description in the link. Dose it mean, It could be solved if I update the software?
Best wishes,
Hao
> Dear @haodengfrm2,
> 
> Thank you for your post. Please have a look here: https://www.coronawarn.app/en/faq/#API10.
> Can you confirm that you are using CWA version 1.6.0 or 1.6.1 already, please?
> 
> Thanks. Best wishes,
> DS
> 
> Corona-Warn-App Open Source Team

![微信图片_20201118112335](https://user-images.githubusercontent.com/22814682/99518228-94002900-2990-11eb-837b-558964596962.jpg)

**Comment by dsarkar** [comment]
@haodengfrm2, thanks for the reply. Can you also please let us know the ENF version, see here https://www.coronawarn.app/de/faq/#ENF_version. Thanks. DS

---
Corona-Warn-App Open Source Team

**Comment by haodengfrm2** [comment]
I don't understand quite well "In the settings, select 'Google > Notifications about possible encounters with COVID-19 infected'"
In the settings of Google play or in the settings of CWA? I could not find the Notifications about possible encounters with COVID-19 infected....

**Comment by haodengfrm2** [comment]
Thanks for the reply! I don't understand quite well "In the settings, select 'Google > Notifications about possible encounters with COVID-19 infected'"
In the settings of Google play or in the settings of CWA? I could not find the Notifications about possible encounters with COVID-19 infected....
> @haodengfrm2, thanks for the reply. Can you also please let us know the ENF version, see here https://www.coronawarn.app/de/faq/#ENF_version. Thanks. DS
> 
> Corona-Warn-App Open Source Team

**Comment by Alex-Esko** [comment]
Geräte-Einstellungen > Google > COVID-19-Benachrichtigungen
ganz unten:
Version 18204217000

**Comment by vaubaehn** [comment]
@haodengfrm2 

> 
> Geräte-Einstellungen > Google > COVID-19-Benachrichtigungen
> ganz unten:
> Version 18204217000 (_Beispiel_)

translates to

Your Android device settings > Google > Covid-19-notifications
scroll down completely
Version 18204217000 (example)

**Comment by vaubaehn** [comment]
@haodengfrm2 and @dsarkar 

> Dear Dsarkar,
> I'm using 1.6.0. I don't understand the description in the link. Dose it mean, It could be solved if I update the software?
> Best wishes,
> Hao
> 
> > Dear @haodengfrm2,
> > Thank you for your post. Please have a look here: https://www.coronawarn.app/en/faq/#API10.
> > Can you confirm that you are using CWA version 1.6.0 or 1.6.1 already, please?

The link to the FAQ is obviously not related to your problem. That FAQ item is related to #737 (pipe is closed) which was actually solved with ENF version 15xxxxxxxxx and was affecting Android 6 devices only.

Your error indeed seems to replicate #1085 and #817 .

**Comment by MikeMcC399** [comment]
@haodengfrm2 

Just to summarize and make the error message searchable (instead of having it in a screen shot):

`com.google.android.gms.common.api.ApiException: 10: Unable to validate key file signature: no public key found for package de.rki.coronawarnapp`

Mobile device: Meizu
Android version: 7.1.2
CWA version: 1.6.0

The instructions to get the Google Exposure Notification System (ENS) version number for an English user interface are on https://www.coronawarn.app/en/faq/#ENF_version

So go to (Android) Settings > Google > COVID-19 exposure notifications
then scroll down to the bottom of the screen. (@vaubaehn almost got the translation right 😄 I just checked on my own device which is set to English, so I didn't do any translating.) When this problem occurred previously it was linked to a specific version of ENS, so it would be very helpful to know what version of ENS is installed on your Meizu device.

**Comment by haodengfrm2** [comment]
Dear Mike,
Thank you very much for your reply and summary. However, I could not find (Android) Settings > Google in Flyme/Meizu phone...
![微信图片_20201118224251](https://user-images.githubusercontent.com/22814682/99591669-6c8c7900-29ef-11eb-8473-6efa731ecdd8.jpg)

> @haodengfrm2
> 
> Just to summarize and make the error message searchable (instead of having it in a screen shot):
> 
> `com.google.android.gms.common.api.ApiException: 10: Unable to validate key file signature: no public key found for package de.rki.coronawarnapp`
> 
> Mobile device: Meizu
> Android version: 7.1.2
> CWA version: 1.6.0
> 
> The instructions to get the Google Exposure Notification System (ENS) version number for an English user interface are on https://www.coronawarn.app/en/faq/#ENF_version
> 
> So go to (Android) Settings > Google > COVID-19 exposure notifications
> then scroll down to the bottom of the screen. (@vaubaehn almost got the translation right 😄 I just checked on my own device which is set to English, so I didn't do any translating.) When this problem occurred previously it was linked to a specific version of ENS, so it would be very helpful to know what version of ENS is installed on your Meizu device.

**Comment by MikeMcC399** [comment]
@haodengfrm2 
>... I could not find (Android) Settings > Google in Flyme/Meizu phone

Thanks for the screen shot. There is certainly no Google element in that menu!

It looks like Flyme/Meizu is non-standard concerning the Google Play services, which is a prerequisite for the Corona-Warn-App, because the Exposure Notifications System is licensed via the Google Play services. Were you able to install the Corona-Warn-App from the Google Play Store or did you do it some other way?

It may be possible to get in to the Google COVID menu by a trick.

1. Open the Corona-Warn-App and make sure that EXPOSURE LOGGING ACTIVE is showing (not STOPPED). If it is STOPPED, then enable it.
2. Disable Bluetooth.
3. If you get a red Google COVID notification "Exposure Notifications inactive" you can open it up. Then scroll down to the bottom and look for the Version. For me it says 18204217000.
4. Also if you manage to open that menu, then you can select Exposure checks and at the top right, select the three-dot menu, then Export exposure checks. Add a .txt file extension to the filename all-exposure-checks.json and post the file here.

**Comment by thomasaugsten** [comment]
@haodengfrm2 
You would help us a lot if you can provide a bug report for us that we can send to google because we are investigating this error over a long time now
https://developer.android.com/studio/debug/bug-report
and send this to me
thomas.augsten@sap.com

**Comment by haodengfrm2** [comment]
Dear Mike,
Thank you so much for this trick! Here is the picture. Exposure checks is dark that I could not select it. There is no there dot menu also....
![微信图片_20201119081641](https://user-images.githubusercontent.com/22814682/99633677-93729b80-2a3f-11eb-914a-b23f51fa5339.jpg)


> @haodengfrm2
> 
> > ... I could not find (Android) Settings > Google in Flyme/Meizu phone
> 
> Thanks for the screen shot. There is certainly no Google element in that menu!
> 
> It looks like Flyme/Meizu is non-standard concerning the Google Play services, which is a prerequisite for the Corona-Warn-App, because the Exposure Notifications System is licensed via the Google Play services. Were you able to install the Corona-Warn-App from the Google Play Store or did you do it some other way?
> 
> It may be possible to get in to the Google COVID menu by a trick.
> 
> 1. Open the Corona-Warn-App and make sure that EXPOSURE LOGGING ACTIVE is showing (not STOPPED). If it is STOPPED, then enable it.
> 2. Disable Bluetooth.
> 3. If you get a red Google COVID notification "Exposure Notifications inactive" you can open it up. Then scroll down to the bottom and look for the Version. For me it says 18204217000.
> 4. Also if you manage to open that menu, then you can select Exposure checks and at the top right, select the three-dot menu, then Export exposure checks. Add a .txt file extension to the filename all-exposure-checks.json and post the file here.

**Comment by thomasaugsten** [comment]
@haodengfrm2  Thank you for the ENF version but I assume all device has the same ENF version at the moment. Can you please provide the bug report?

**Comment by haodengfrm2** [comment]
Dear Thomas,
Here attached the screenshot of developer menu. I could not find the bug report setting....
![微信图片_20201119083530](https://user-images.githubusercontent.com/22814682/99635490-58be3280-2a42-11eb-993a-7db096643f3b.jpg)


> @haodengfrm2 Thank you for the ENF version but I assume all device has the same ENF version at the moment. Can you please provide the bug report?

**Comment by MikeMcC399** [comment]
@haodengfrm2 
> Thank you so much for this trick! Here is the picture. Exposure checks is dark that I could not select it. There is no there dot menu also....

Your screen shot gave two extra pieces of information:
- Your ENS version is 18204217000. That shows that it is updating correctly.
- "0 checks in the past 14 days" shows that there have been no successful checks, which means that the checks are failing silently leading to the 39508 quota exceeded error
- Because there are 0 checks stored, the menu to export the checks is not available. There is nothing to export. However the "0 checks in the past 14 days" status told us what we needed to know there.

**Comment by thomasaugsten** [comment]
With the option bug report shortcut in power menu you should see an extra button when you try to turn off the phone.
I assume the error is gone? If not please start the app with the error before creating the bug report

**Comment by haodengfrm2** [comment]
> With the option bug report shortcut in power menu you should see an extra button when you try to turn off the phone.
> I assume the error is gone? If not please start the app with the error before creating the bug report

Dear Thomas,
Sorry but there is no such a button. It seems that Flyme did not implement this function...

**Comment by MikeMcC399** [comment]
> > With the option bug report shortcut in power menu you should see an extra button when you try to turn off the phone.
> > I assume the error is gone? If not please start the app with the error before creating the bug report
> 
> Dear Thomas,
> Sorry but there is no such a button. It seems that Flyme did not implement this function...

It's strange, because in the screen shot you posted, it looks like "Bug report shortcut" is enabled. Perhaps you could get help from your device manufacturer's support / forum?

![Bug report shortcut](https://user-images.githubusercontent.com/66998419/99678601-48767980-2a7b-11eb-92fa-84f7ad46144c.jpg)

---

Here is what it looks like on a Samsung phone with Android 8:

![Take a bug report](https://user-images.githubusercontent.com/66998419/99679697-86c06880-2a7c-11eb-81b8-859f060a5105.jpg)

**Comment by dsarkar** [comment]
Dear community, dear @haodengfrm2, 

We would appreciate feedback if this issue persists with CWA version 1.7.1. Many thanks!

Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by haodengfrm2** [comment]
> Dear community, dear @haodengfrm2,
> 
> We would appreciate feedback if this issue persists with CWA version 1.7.1. Many thanks!
> 
> Best wishes,
> DS
> 
> Corona-Warn-App Open Source Team
Dear Dsarkar,
Thank you very much for your information! I update CWA and now it looks like this:
![微信图片_20201201092817](https://user-images.githubusercontent.com/22814682/100715504-95c9e380-33b7-11eb-8351-85fa836d13fc.jpg)
![微信图片_20201201092810](https://user-images.githubusercontent.com/22814682/100715507-96627a00-33b7-11eb-903c-c372098c7330.jpg)
![微信图片_20201201092803](https://user-images.githubusercontent.com/22814682/100715511-96627a00-33b7-11eb-9486-4dcdee016f66.jpg)

**Comment by MikeMcC399** [comment]
@haodengfrm2 
Your screen shot shows "0 checks in the past 14 days". Also you have told us that you have no Google menu to access normally (unless you use the trick of disabling Bluetooth).

It is most likely that there is something wrong with the Google Play services installed on your mobile phone, so you may need to go to your Flyme/Meizu support or forum to get help in installing or re-installing this.

**Comment by haodengfrm2** [comment]
> @haodengfrm2, are there any news on your issue? Did updating to 1.10.1 change anything? Thanks, DS

Dear dsarkar,
Thank you for your information. Unfortunately, nothing changed. Maybe it's just the problem of the system of my cell phone. Thanks.
Hao

**Comment by MikeMcC399** [comment]
@haodengfrm2 
Your issue has been open for many months without any further progress. I commented in Dec 2020 (https://github.com/corona-warn-app/cwa-app-android/issues/1645#issuecomment-736648785) that it could be due to Google Play services.

It doesn't seem like anything in the CWA app could be changed to help you. Maybe you could report back your status and then close the issue if there is nothing more to be done?

**Comment by svengabr** [comment]
I have just checked the linked Jira issue.

Jira Ticket is flagged as:
Resolution: `Wont Fix`
Status: `Obsolete`

Developer comment:
> No new information available. Will set it to obsolete.
