### ISSUE TITLE
App schließt sich nach Start wider

### ISSUE THREAD

**Issue by Mike-wall-pirat** [corona-warn-app/cwa-app-android#1722]
Seit 2 oder 3 Tagen schließt sich die App mal schneller, mal langsamer. Zu sehen ist nur der weiße Startbildschirm. Es findet keine Risikobewertung statt. Weder ein Neustart noch das starten und stoppen der App hat geholfen. Das ganze unter Android 7. 
Version der App ist 1.6.1

**Comment by dsarkar** [comment]
Hi @Mike-wall-pirat,

Thanks for reporting. 
The actual CWA version is 1.7 since yesterday. Please, let us know if the problem persists after updating.

Regarding the update to CWA 1.7: Please note that is a staged rollout. Over the next two days, 100% of the users should have received the update.
  
Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Mike-wall-pirat** [comment]
Hallo, ich muss meine erste Aussage bezüglich des Updates korrigieren! Zwar hat das Update das Problem behoben, aber nur direkt nach dem Update. Einen Tag später ist alles beim alten und die App startet nicht, bzw. schließt sich gleich wieder.
Dieser Zustand hält an.

**Comment by dsarkar** [comment]
Dear @Mike-wall-pirat,

we would need/confrim some more information:
- CWA version:     1.7.1 ?
- Android version: 7.x ?
- Mobile device:   ?
- Any error message notification ?

Thanks. Best wishes,
DS

---
Corona-Warn-App Open Source Team

**Comment by Mike-wall-pirat** [comment]
CWA version: 1.7.0
Android version: 7.0
Kernel-Version: 3.18.35
Mobile Device: Oukitel U20 Plus
No error messages.

**Comment by dsarkar** [comment]
Duplicate of https://github.com/corona-warn-app/cwa-app-android/issues/1731

**Comment by dsarkar** [comment]
Dear @Mike-wall-pirat, 

Thank you very much for the information. We might come back to you in order to request more information. This issue seems to be related to a problem with Android 6 and Android 7 devices. See here https://github.com/corona-warn-app/cwa-app-android/issues/1731.

I will close this issue here and forward your info to the developers. Any further development will be published here or here https://github.com/corona-warn-app/cwa-app-android/issues/1731. 

Best wishes,
DS

---
Corona-Warn-App Open Source Team
