### ISSUE TITLE
Micro G

### ISSUE THREAD

**Issue by Konradrundfunk** [corona-warn-app/cwa-app-android#188]
## Your Question
Hi, I have successfuly build and now I what to use the app with micro g(https://microg.org) can i use the regular app with some workaround or have I to wait or the libre App?
* Source File:
* Line(s):
* Question:

**Comment by marcmuschko** [comment]
Dear @Konradrundfunk,

thanks for reaching out! I am not quite familiar with micro g, to verify my answer for sure you would need to run a test. 
However they state to have developed "a free software clone of Google’s proprietary core libraries and applications". I highly doubt that they already implemented the necessary components within the GMS library the Corona-Warn-App requires to function properly.

As this seems quite similar to the [F-Droid question ](https://github.com/corona-warn-app/cwa-documentation/issues/5) in the documentation repository, I am closing this issue since we are not planning to deploy to any App Stores except Google's and Apple's.
Hope this helps! 

Best,
Marc

**Comment by Konradrundfunk** [comment]
Ok then I will reach out to the devs from Micro G.

**Comment by rugk** [comment]
MicroG now supports the Exposure Notification API, so yes, you can now use it.
