### ISSUE TITLE
[BSI][20201216] Insecure Storage of Symptoms Status

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-app-android#1907]
Rating: Low

Description:
The 1.9 update of the Android CWA app stores sensitive information in an unencrypted from.
The Android app stores a parameter that indicates whether the user is suffering from symptoms in a shared preferences file. The parameter submission.symptoms.latest is set to “POSITIVE” or “NEGATIVE” values and is stored in an unencrypted form in the shared preferences file submission_localdata.xml.
A local attacker with escalated privileges can capture this unencrypted information from the app’s sandbox storage.

Proof of Concept:
The following excerpt shows that the parameter submission.symptoms.latest is saved in submission_localdata.xml file:

Class SubmissionSettings
```
private val prefs by lazy { context.getSharedPreferences("submission_localdata", Context.MODE_PRIVATE) }
val symptoms: FlowPreference<Symptoms?> = FlowPreference( prefs, key = "submission.symptoms.latest", reader = FlowPreference.gsonReader<Symptoms?>(gson, null), writer = FlowPreference.gsonWriter(gson) )
```

Class SubmissionRepository
```
// to be used by new submission flow screens val hasGivenConsentToSubmission = submissionSettings.hasGivenConsent.flow val currentSymptoms = submissionSettings.symptoms
```

Class SubmissionSymptomIntroductionViewModel
```
fun onPositiveSymptomIndication() { updateSymptomIndication(Symptoms.Indication.POSITIVE) } fun onNegativeSymptomIndication() { updateSymptomIndication(Symptoms.Indication.NEGATIVE) } fun onNoInformationSymptomIndication() { updateSymptomIndication(Symptoms.Indication.NO_INFORMATION) } private fun updateSymptomIndication(indication: Symptoms.Indication) { Timber.d("updateSymptomIndication(indication=$indication)") submissionRepository.currentSymptoms.update { (it ?: Symptoms.NO_INFO_GIVEN).copy(symptomIndication = indication) } }
```

Recommended Controls:
Sensitive information about user’s infection and symptoms should be stored in an encrypted from. Therefore, it is recommended to encrypt values of submission_localdata.xml in the same way as with shared_preferences_cwa.xml file.

---
Internal Tracking ID: [EXPOSUREAPP-4322](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4322)

**Comment by GisoSchroederSAP** [comment]
Thanks for sharing these comments. 
We are taking security issues very seriously and will investigate impact, probability, and options to handle this issue accordingly.

**Comment by MikeMcC399** [comment]
Is there some reason not to follow the instructions in https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md:

"For reporting a vulnerability, please use the Vulnerability Report Form for Security Researchers on [SAP Trust Center](https://www.sap.com/about/trust-center/security/incident-management.html)"

instead of posting here?

**Comment by Diapolo** [comment]
Is this looked into or just ignored for now?

**Comment by GisoSchroederSAP** [comment]
Again, thanks for reporting the finding with a detailed information. 
Since the related issues #1988 , #1989 , and #1554 all tackle the same finding and recommendations, but just different data objects, we will handle them with high priority for evaluation and for a proper solution design.

Still, I urgently ask @BSI-TF-CWA , to follow the agreed procedure documented in:
[https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md](url)
Following this path ensures the findings are addressed to the right team, so the required procedure and documentation becomes transparent and efficient. Otherwise we may lose time and generate additional communication effort with disclosure of sensitive information.

All GitHub issues (including #987) are already _converted_ into a respective internal work item that allows the experts to follow up.

Thanks, @BSI-TF-CWA, for your input and for following the agreed procedure as described here: [https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md](url)

**Comment by GisoSchroederSAP** [comment]
Again, thanks for reporting the finding with a detailed information.
Since the related issues #1988 , #1907 , and #1554 all tackle the same finding and recommendations, but just different data objects, we will handle them with high priority for evaluation and for a proper solution design.

Still, I urgently ask @BSI-TF-CWA , to follow the agreed procedure documented in:
(https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md)
Following this path ensures the findings are addressed to the right team, so the required procedure and documentation becomes transparent and efficient. Otherwise we may lose time and generate additional communication effort with disclosure of sensitive information.

All GitHub issues (including #987) are already converted into a respective internal work item that allows the experts to follow up.

Thanks, @BSI-TF-CWA, for your input and for following the agreed procedure as described here: (https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md)

**Comment by heinezen** [comment]
This issue is probably obsolete. Closed in favour of https://github.com/corona-warn-app/cwa-app-android/issues/2846

----
Corona-Warn-App Open Source Team
