### ISSUE TITLE
[Discussion] Read Corona Warn App results with an app?

### ISSUE THREAD

**Issue by Timo1993** [corona-warn-app/cwa-app-android#1956]
I would like to implement an app which provides additional features to the corona warn app. Therefore I would need the number of risk encounters determined by the corona warn app and the time of the risk encounter (for high risk). 

Is it possible to get these data? It might obviously be possible via root.

**Comment by thomasaugsten** [comment]
This is not allowed by Google and Apple you can only access this data when you disable the security system from google via rooting this device. Google and Apple are not allowing because with the exact time you can identify the other person.

**Comment by Timo1993** [comment]
Would it be possible that the corona warn app stores the risk encounters in a local file on the device to get access to it? For the app the user should enter a date and the app needs to verify that there was a risk encounter at this time.

**Comment by thomasaugsten** [comment]
It is planned to show a contact history which marks each day with encounters

**Comment by not-a-feature** [comment]
Hi,

there is already an App on the market which provides more information to the risk encounters.
You probably want to take a look at it.
See: https://github.com/mh-/corona-warn-companion-android
And: https://play.google.com/store/apps/details?id=org.tosl.warnappcompanion&hl=de&gl=DE

**Comment by ndegendogo** [comment]
> already an App on the market which provides more information to the risk encounters

@not-a-feature yes. But, as @thomasaugsten mentioned above, it needs root to access this data

> Achtung: Um die Daten der Warn-App zu lesen, benötigt die App Root Rechte. Ohne Root Rechte kann sie nur zusammen mit der RaMBLE App oder mit der CCTG App / microG verwendet werden.

**Comment by Timo1993** [comment]
@not-a-feature I am already using this app with root and it works perfect. But I would like to provide a way for app user (without root) to show where the risk encounters occur. So that they can adapt the behavior. My current modification of the Corona warn app companion delivers fruitful insights (e.g., most risk encounters are in a bus or during a shopping trip).

**Comment by ndegendogo** [comment]
> I would like to provide a way for app user (without root) to show where the risk encounters occur.

@Timo1993 in the current implementation, the matching algorithm is provided by the Exposure Notification System (ENS / ENF) and implemented by a library from Google / Apple. **So cwa has no detailed information on single risk encounters.**

However, for Android there exists an alternate implementation of this ENS library, and a fork of cwa integrating. See more details in the links mentioned in [this discussion](https://github.com/corona-warn-app/cwa-app-android/issues/1483). You might consider to discuss your ideas with those projects.

**Comment by thomasaugsten** [comment]
Apple and Google will not provide exact information of the encounters. Because with this information you can easily identify positive tested persons. To protect user from being identified is for Apple and Google much more important than to provide a nice to have time of the encounter. This is also understandable nobody wants to be identified and shamed by strangers.

**Comment by MikeMcC399** [comment]
@heinezen 
You added the Fix 1.10 label to this issue, however in Android 1.10.1 the Contact Journal is not automatically linked to exposures. Perhaps this is now planned for a later version?

**Comment by Ein-Tim** [comment]
>Perhaps this is now planned for a later version?

I think this is planned for version 1.12.

**Comment by MikeMcC399** [comment]
@Timo1993 

There have been many enhancements to the app since you posted your original question, including displaying more concrete information about when risk encounters took place. See for instance: https://www.coronawarn.app/en/blog/2021-02-10-corona-warn-app-version-1-12/ which says: "Another new feature in version 1.12 is the exposure history, which users can find in the contact journal’s overview."

Does this issue still need to be kept open? What features (if any) do you think are necessary on top of the ones existing in the current version 2.0.4?
