### ISSUE TITLE
Transnational country list names displayed in English when system is German

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#1958]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A50 SM-A505FN
- Android version: 10
- App version: 1.9.1

## Describe the bug

The country names are shown in English when the system language is set to Deutsch (Deutschland).
This is a regression from version 1.7.1 (see screenshots from previous version in https://github.com/corona-warn-app/cwa-app-android/issues/1872#issuecomment-743124411)

## Steps to reproduce the issue

1. Set Android system language to Deutsch (Deutschland)
2. Tap RISIKO-ERMITTLUNG AKTIV
3. Tap Länderübergreifende Risiko-Ermittlung
4. Scroll down to heading "Derzeit nehmen die folgenden Länder an der länderübergreifenden Risiko-Ermittlung teil:"

![Country_list_1 9 1_de](https://user-images.githubusercontent.com/66998419/102689485-c5be1700-41fe-11eb-9ada-2222266c7de9.jpg)

## Expected behaviour

The names of the countries should be shown in German when the system language is set to German.

## Possible Fix

Use German country names when the UI is set to German and sort the names according to their German names.

## Additional context

See also https://github.com/corona-warn-app/cwa-app-android/issues/1957 regarding sorting.

---
Internal Tracking ID: [EXPOSUREAPP-4416](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4416)

**Comment by dsarkar** [comment]
ok, thanks, in iOS is not an issue. Thanks, DS

**Comment by Jo-Achim** [comment]
Android 10 with Android security update: November 1st, 2020
Nokia 7.1, Build: 00WW_4_16B_SP01
CWA version: 1.9.1
ENF: 18204713000

No problems here:

![CWA 1 9 1 - Country-Info](https://user-images.githubusercontent.com/21124877/102690124-7f1eeb80-4203-11eb-82a0-418a89333659.jpg)

Best regards.

**Comment by dsarkar** [comment]
@Jo-Achim, ok! Interesting. Thanks for the information, will be forwarded to devs. DS

**Comment by MikeMcC399** [comment]
@Jo-Achim 
Thanks for your screen shot!
The problem was changing the language from English to German without closing and re-opening CWA.
Android apps are supposed to cope with this, but this is a minor problem if the work-around is simply to restart the app.

**Comment by PhilippNowak96** [comment]
This issue occurs because of the usage of

https://github.com/corona-warn-app/cwa-app-android/blob/5bfc89c1d91bf8afd6aa610dbd611b4515d30e46/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/ui/LazyString.kt#L9-L15

in

https://github.com/corona-warn-app/cwa-app-android/blob/5bfc89c1d91bf8afd6aa610dbd611b4515d30e46/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/view/CountryListView.kt#L23-L29

After you changed the language the cached string still stays the same obviously. I'm not 100% sure what was the idea to use this approach of a cached string. It could be fixed (already tried) by simply using `context.getString(it.labelRes)` at this point but maybe there was a good reason (performance or anything like that?) to use cached strings.
Another approach would be to store the language code to the cached string as well but then you would have to look up the language code each time you try to get the string. Not sure, if that isn't even worse in performance.

Maybe @maugst can say something about it. I could then open a new PR to also match the sorting reintroduced in #1961

**Comment by dsarkar** [comment]
@PhilippNowak96, thanks, I forwarded your post to the developer's ticket. Best, DS

**Comment by Jo-Achim** [comment]
An alternative could be to carry a (global) 'cache valid flag' that determines whether the cache data is used or renewed.
Especially if the problem exists multiple times.

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2053

**Comment by MikeMcC399** [comment]
"Transnational country list names not changing when language is changed (EXPOSUREAPP-4416)" https://github.com/corona-warn-app/cwa-app-android/pull/2053 is included in [v1.11.0-RC1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.11.0-RC1)

**Comment by MikeMcC399** [comment]
Fixed in CWA 1.11.0 released on Jan 28, 2021.
