### ISSUE TITLE
test results delete poorly implemented

### ISSUE THREAD

**Issue by CSchepelmann** [corona-warn-app/cwa-app-android#1979]
After scanning the qr, many patients press the delete tests button. This is where we as a medical office need to give people support for the app! There is already enough work. The test delete button is pointless and only brings problems in the practice!

**Comment by thomasaugsten** [comment]
Thanks for the feedback. But we have multiple information about the consequence to delete a pending test.
The delete button is necessary because some test-labs doesn't want to be connected to the Corona-Warn-App. To add a new test you have to delete the old test. Also with a deleted test the user can share his diagnosis keys via a TAN.

![IMG_50CDF4F0A787-1](https://user-images.githubusercontent.com/6367738/102823776-d677b400-43db-11eb-8d35-401142bcda91.jpeg)
![IMG_9C89231A1ED5-1](https://user-images.githubusercontent.com/6367738/102823782-d8417780-43db-11eb-8752-ba3f8e55eba0.jpeg)

**Comment by CSchepelmann** [comment]
If deleting is necessary, the button does not have to be placed hugely above the home button. It makes more sense to have a small trash icon in the upper area like in most other apps! 

The problem that the result is accidentally deleted, we have several times a day. Either the users are too stupid or the app is not user friendly.

Why not several tests can be saved is not clear. But that is another topic.

Translated with www.DeepL.com/Translator (free version)

**Comment by thomasaugsten** [comment]
We will think about this but we thought. A extra popup with an red "Entfernen" button prevents the user from accidentally deleting the test. He needs to accidentally tap on test entfernen and then on button Entfernen to delete the test

**Comment by Diapolo** [comment]
> some test-labs doesn't want to be connected to the Corona-Warn-App

Can you give some insight, why that is the case? From the technical side it's off topic, but IMHO it should be the goal to have all labs connected to CWA, no?

**Comment by thomasaugsten** [comment]
I cannot say anything about internal priorities of the test labs but we cannot force them to connect their system to the CWA.

**Comment by DerVogel2020** [comment]
> 
> 
> We will think about this. But we thought an extra popup with a red "Entfernen" button prevents the user from accidentally deleting the test. He needs to accidentally tap on test entfernen and then on button Entfernen to delete the test

In the android app, the "Test entfernen"-Button is not red and there is no such detailed hint for the user, as the iOS-screenshot in https://github.com/corona-warn-app/cwa-app-android/issues/1979#issuecomment-749204892 shows. The test is deleted after the first press of "Test entfernen".

**Comment by MikeMcC399** [comment]
@DerVogel2020 
> The test is deleted after the first press of "Test entfernen".

Perhaps there is a difference between deleting a rapid test and a PCR test?

If I try to delete a PCR test which is in the status waiting for result (English UI: "DELETE TEST"), then the dialog comes up "The test can only be scanned once." which has the options "CANCEL" or "REMOVE".

**Comment by MikeMcC399** [comment]
- See [Corona-Warn-App version 2.14 introduces recycle bin feature for PCR and rapid tests](https://www.coronawarn.app/en/blog/2021-11-22-cwa-2-14/) so that inadvertently deleted tests can be restored.

- In addition, regarding comments from @thomasaugsten and @DerVogel2020  PR https://github.com/corona-warn-app/cwa-app-android/pull/5538 planned for release 2.27 introduces red text for the delete confirmation dialog

![Testergebnis löschen](https://user-images.githubusercontent.com/66998419/188893006-c4abc57f-1c62-4d2d-b5bd-a5d422bb0ca2.jpg)

@CSchepelmann 
Perhaps you would like to give feedback again based on your practical experience?
