### ISSUE TITLE
[BSI][20201223] Insecure Storage of Risk Values

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-app-android#1989]
Rating: Low

Description:
The 1.10-diary update of the Android CWA app stores sensitive information in an unencrypted from.
The risk database used to store the risk value history is stored unencrypted on the device's filesystem. While it does not contain personal data, it might be used to infer the user's infection status. Thus, it is highly recommended to encrypt this database.
A local attacker with escalated privileges can capture this unencrypted information from the app’s sandbox storage.

Proof of Concept
The following screenshot shows the structure of the database found on the device.
![image](https://user-images.githubusercontent.com/65443025/102974436-d7edcd00-44fe-11eb-932a-298fb2130b2e.png)

The content of the database might give insights to the infection status of the user.
![image](https://user-images.githubusercontent.com/65443025/102974464-e2a86200-44fe-11eb-8fb3-ffb98338abdd.png)

Recommended Controls
Sensitive information about a user should be stored in an encrypted from. Therefore, it is recommended to store the database in an encrypted form. Encryption should be based on current best practices in terms of algorithms, cipher modes and key lengths.

**Comment by GisoSchroederSAP** [comment]
Again, thanks for reporting the finding with a detailed information. 
Since the related issues #1988 , #1907 , and #1554 all tackle the same finding and recommendations, but just different data objects, we will handle them with high priority for evaluation and for a proper solution design.

Still, I urgently ask @BSI-TF-CWA , to follow the agreed procedure documented in:
[https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md](url)
Following this path ensures the findings are addressed to the right team, so the required procedure and documentation becomes transparent and efficient. Otherwise we may lose time and generate additional communication effort with disclosure of sensitive information.

All GitHub issues (including #987) are already _converted_ into a respective internal work item that allows the experts to follow up.

Thanks, @BSI-TF-CWA, for your input and for following the agreed procedure as described here: [https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md](url)

**Comment by heinezen** [comment]
This issue is probably obsolete. Closed in favour of https://github.com/corona-warn-app/cwa-app-android/issues/2846

----
Corona-Warn-App Open Source Team
