### ISSUE TITLE
Exposure check not happening / Keine Risiko Aktualisierung (1.9.1)

### ISSUE THREAD

**Issue by d4rken** [corona-warn-app/cwa-app-android#2001]
Try also workarounds described here:
**EN** https://www.coronawarn.app/en/faq/#no_risk_update
**DE** https://www.coronawarn.app/de/faq/#no_risk_update

----

This ticket is about exposure checks not happening on 1.9.1.

(Splits #1894, as which was reported to be fixed, and due to the large changeset in 1.9.1 this is likely a different issue).

Original poster (@gehwissenlos ):

> Hallo zusammen,
>ich erlaube mir, mein Problem mit ebenfalls einem Samsung-Gerät hier anzuhängen:
>Samsung Galaxy Note 9, SM-N960
>App-Version 1.9.1
>Android 10

> Meine Daten wurden seit 25.12. nicht mehr aktualisiert, obwohl das davor immer zuverlässig mehrmals am Tag funktioniert hat.

>Gruß
> Manuel

> [all-exposure-checks.json.txt](https://github.com/corona-warn-app/cwa-app-android/files/5746545/all-exposure-checks.json.txt)
>[Screenshot_20201228-095432_Google Play services](https://user-images.githubusercontent.com/6155210/103203119-883f4500-48f4-11eb-8bcb-96f2707a82c9.jpg)
>[Screenshot_20201228-095452_Google Play services](https://user-images.githubusercontent.com/6155210/103203122-89707200-48f4-11eb-952d-795b02ea7d69.jpg)
> [Screenshot_20201228-125159_Corona-Warn](https://user-images.githubusercontent.com/6155210/103212624-9b114400-490b-11eb-914a-32729f675076.jpg)

---
Internal Tracking ID: [EXPOSUREAPP-4473](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4473)

**Comment by thomasaugsten** [comment]
@gehwissenlos
Kannst du schauen welches Datum auf deinem Gerät eingestellt ist und siehst du nach einem force stop eine Animation auf der grünen Kachel wenn du die App startest?

**Comment by gehwissenlos** [comment]
@thomasaugsten 
Datum ist der 28.12.2020, 13:27 (also aktuell).

Hier das Video beim Start nach einem force stop. Eine Animation sehe ich nicht.

https://user-images.githubusercontent.com/6155210/103214270-47552980-4910-11eb-838a-94d48836014d.mp4

**Comment by d4rken** [comment]
Some thoughts:
* It's curious that the app shows: "Last updated 25th 22:51", and today is the "28th 13:20".
* The card itself uses the last ENF submission [timestamp date](https://github.com/corona-warn-app/cwa-app-android/blob/715c30ad482301594b77a003ce870f5997302541/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/tracing/card/TracingCardStateProvider.kt#L67).
* This would mean there was no submission since then, or the RiskLevelTask did not run.
* If the RiskLevelTask runs and the downloaded files are older than 48h, there should be a [white error card](https://github.com/corona-warn-app/cwa-app-android/blob/715c30ad482301594b77a003ce870f5997302541/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/risk/RiskLevelTask.kt#L112).
* As there is no white card, either the `RiskLevelTask` did not run or we have more recent key downloads, but have not submitted them for [some reason](https://github.com/corona-warn-app/cwa-app-android/blob/715c30ad482301594b77a003ce870f5997302541/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt#L72).

@gehwissenlos Danke für das Video, es bringt uns schon etwas weiter. Kannst du in den System Einstellungen der CWA die "Batterie Optimierungen" einschalten, und dann "Hintergrundnutzung einschränken" anschalten? Danach sollte auf der grünen Karte ein Knopf erscheinen zum manuellen aktualisieren. Es wäre super wenn du noch ein Video aufzeichnest von dem was passiert wenn du auf den Knopf drückst (bitte vorher ohne Video nicht drauf drücken).

[Screenshot from 2020-12-28 13-31-30](https://user-images.githubusercontent.com/1439229/103214645-4a044e80-4911-11eb-912d-01e71b418fbe.png)

**Comment by gehwissenlos** [comment]
![Screenshot_20201228-133549_Settings](https://user-images.githubusercontent.com/6155210/103214844-e7f81900-4911-11eb-9d1e-f5c003e9f7ec.jpg)

Einstellung geändert

https://user-images.githubusercontent.com/6155210/103214838-e3cbfb80-4911-11eb-919d-705628f3ae8a.mp4

Wie man sieht, es passiert "nichts".

**Comment by d4rken** [comment]
Danke für das Video. Auch wenn es sehr schnell geht zumindest beide Tasks an :thinking: 

![Screenshot from 2020-12-28 13-56-40](https://user-images.githubusercontent.com/1439229/103215872-ea0fa700-4914-11eb-8ae6-700a3bf4f6a2.png)
![Screenshot from 2020-12-28 13-56-34](https://user-images.githubusercontent.com/1439229/103215874-eb40d400-4914-11eb-93d4-7abc775941c7.png)

**Comment by gehwissenlos** [comment]
Ich habe nun mal von WLAN auf LTE geswitcht, dabei kam noch dieses Bild. Danach aber auch im Mobilfunknetz das gleiche Problem wie bisher im WLAN.

![Screenshot_20201228-140413_Corona-Warn](https://user-images.githubusercontent.com/6155210/103216740-090f3880-4917-11eb-800a-1ff3334629da.jpg)

**Comment by gehwissenlos** [comment]
Oh, da hat sich gerade etwas getan. Habt ihr etwas geändert?

![Screenshot_20201228-210931_Corona-Warn](https://user-images.githubusercontent.com/6155210/103240764-835cae80-4951-11eb-828e-405a84c61170.jpg)

**Comment by ndegendogo** [comment]
@gehwissenlos check doch mal drine Version.
Es läuft gerade ein Release an.

**Comment by gehwissenlos** [comment]
Die CWA ist immer noch bei 1.9.1 und die Play-Services bei 18204516000.
Also nirgends hat ein Update stattgefunden. Auch bin ich immer noch im selben WLAN.

**Comment by ndegendogo** [comment]
@gehwissenlos es ist wieder ein staged rollout. Du wirst wohl irgendwann in den nächsten Tagen dran sein.

Zu deiner anderen Beobachtung kann ich nix sagen, da müßten nochmal die Entwickler ran. Vielleicht ist ja irgendein Timer abgelaufen.

**Comment by legendofa** [comment]
Same Problem in Version 1.10 for me:

Device: OnePlus 3T
Android 10

![signal-2020-12-31-000852](https://user-images.githubusercontent.com/34162874/103385999-b3908280-4af4-11eb-808f-f6ebe432895a.png)

**Comment by dsarkar** [comment]
@legendofa Thanks for your report. We forwarded your case to the developers. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
@gehwissenlos Could you update to CWA 1.10.1. By today 100% should have been rolled out. If you could update it, does your problem still persist? Thanks for the feedback. DS

**Comment by legendofa** [comment]
> @gehwissenlos Could you update to CWA 1.10.1. By today 100% should have been rolled out. If you could update it, does your problem still persist? Thanks for the feedback. DS

Was already at 1.10.1, my bad. The problem persists.

If there is anything else i can provide like logs, let me know.

**Comment by dsarkar** [comment]
@legendofa Thanks. Devs will come back to you if they need more info.

**Comment by d4rken** [comment]
@gehwissenlos Hast du mal etwas an der Uhrzeit des Gerätes verändert? d.h. Hast du diese mal in die Zukunft oder Vergangenheit gestellt?

**Comment by gehwissenlos** [comment]
@d4rken nein, ich habe es ganz normal auf Uhrzeit vom Netzwerk beziehen gelassen. Das hat auch gepasst, ansonsten hätte ich sicher beim Surfen einen SSL-Fehler bekommen wenn die Zeit nicht gepasst hat.

**Comment by d4rken** [comment]
@legendofa 

> If there is anything else i can provide like logs, let me know.

Thanks for the offer, currently the CWA does not print a lot of details into the system log to which you have access. We may add additional option to help you help us soon, but in the current version it's not there. So I'm not optimistic that it will get us further to a solution.
Still, I don't mind taking a quick look through the log if you would provide one.
It would be most effective if you also perform the manual refresh once as described here before taking the log:
https://github.com/corona-warn-app/cwa-app-android/issues/2001#issuecomment-751698066

How to take the log (if you can export `logcat` directly, that would work too):
https://developer.android.com/studio/debug/bug-report
Note that the log may contain sensitive information that other apps may output, so please don't post it here. Mail it, or the link, to me (matthias.urhahn@sap.com) or @thomasaugsten (thomas.augsten@sap.com).

@gehwissenlos Ok, danke für die Info.
  
Kleiner Zwischenstand:
Nach Diskussion mit @chiljamgossow haben wir bis jetzt nur eine potentielle Ursache gefunden die aber eine "Zeitreise" voraussetzt. Dazu müsste das Gerät für eine erfolgreiche Prüfung in der Zukunft gewesen sein. Dann könnten weitere Checks ausbleiben bis das Gerät diesen Zukünftigen Zeitpunkt eingeholt hat. 
Das scheint mir hier aber unwahrscheinlich da du keine  Zeitreise gemacht hast und Unterschiede von 1-2 Stunden nach 3 Tagen wieder eingeholt wären.

https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/diagnosiskeys/download/DownloadDiagnosisKeysTask.kt#L140

**Comment by ebora** [comment]
Device: Oneplus 3T, Android 10: lineage-microg-17.1 (no Gapps)

I saw something like this issue after update from CWA 1.9 to 1.10.1, "Aktualisiert" was stuck at 2. Jan since a system update shortly after the CWA update on 3. Jan until this morning. After update to microg 1.16 (from 1.14) yesterday evening (and waiting over night, I didn't restart the App) everything seems to be normal again.

Maybe what I saw during the 3 days (with updates) might help to pinpoint the cause of this issue? Let me know if you think it might be relevant to this issue and would like some more details.

**Comment by ebora** [comment]
It's back. After CWA and the Exposure Notification info in microg showed the same time for the check for dignostic keys yesterday (I did two manual checks), this morning the time diverges again.
In CWA the time of the last check from yesterday is still displayed, in the Exposure Notification info regarding CWA in a microg submenu the check this morning is shown, dignostic keys were processed.
And CWA seems to know this, too, because pressing the "Aktualisieren" Button results in only a very short "disapearance" of the green panel/card and microgs Exposure Notification info doesn't show a new check.

Since yesterday morning I didn't change any phone settings and didn't update anything. A reboot this morning after the check didn't change the display of the wrong time for it in CWA.

**Comment by legendofa** [comment]
The problem was resolved for me after updating microg 1.16 yesterday aswell.
There is no "Aktualisieren" button displayed for me, but the update works now regularily every day.
CWA is at version 1.10.1.

Is this problem now microg exclusive? Would be interesting to know from all participants in this issue.
This would shift the responsibility to the microg implementation of the Exposure Notifications.
Cant find the issue now, but as far as i remember the CWA team supports mainly the official Exposure Notification (Google/Apple) implementations.

> Device: Oneplus 3T, Android 10: lineage-microg-17.1 (no Gapps)
> 
> I saw something like this issue after update from CWA 1.9 to 1.10.1, "Aktualisiert" was stuck at 2. Jan since a system update shortly after the CWA update on 3. Jan until this morning. After update to microg 1.16 (from 1.14) yesterday evening (and waiting over night, I didn't restart the App) everything seems to be normal again.
> 
> Maybe what I saw during the 3 days (with updates) might help to pinpoint the cause of this issue? Let me know if you think it might be relevant to this issue and would like some more details.

**Comment by d4rken** [comment]
> There is no "Aktualisieren" button displayed for me, but the update works now regularily every day.

The manual refresh button only appears if background execution is restricted.

I currently have no new insights to offer, but we are preparing a debug log feature for one of the next updates, once that's available it should give everyone the opportunity to understand this issue much better, independent of whether it's GPlay or microG services.

There will also be some fixes regarding issues caused by timetravel in `v1.11.x` and while it could cause what we are seeing, I don't see how the micro G updates could have caused anything like this to happen or not happen.

**Comment by ebora** [comment]
Looking forward to the debug log feature. 
The behavior seems now to be erratic in my case, I did 3 manual refreshs, in the second refresh CWA updated the time but not in the others.

**Comment by uuuu1234** [comment]
Same issue here. No exposure check since 18.12.2020.

system info:
Fairphone 2
Android 2
open source play services replacement microg v 0.2.17

**Comment by ndegendogo** [comment]
I have heard of another user with Android and cwa 1.10 (unfortunately, I have no more infos on device type / exact Android and ENS version / Google play version at the moment).
The observation / suspicion was that it seems to be related to runtime since the last reboot of the device. Since then, said user reboots often.

@thomasaugsten *could you please check for memory leaks and similar suspects?

**Comment by ebora** [comment]
Finally, my CWA is running without issues again.

After my last post, I had about a week of erratic behavior with updates (Aktualisierungen) happening several times a day (as shown in microG) but the last update time shown in CWA was updated only once a day, usually. 

The behavior changed again after update to microG 1.17. (from 1.16) on 15.01.
After that I had only 3 successful updates in 4 days in CWA despite trying for manual updates 3x per day (plus automatic update in WLAN was allowed anyway). In contrast to the previous behavior now the information given in microG about CWA's updates was the same time as the one displayed in CWA. 
So no updates which are not displayed in CWA any more but instead no regular updates, not even in the notification backend.
The logest time without update was ~two days. 
Restarting the phone didn't help. CWAs notification "Bitte denke sie daran, die Corona-Warn-App regelmäßig..." was displayed very often.

On 19.01. I read about the app [corona contact tracing germany](https://codeberg.org/corona-contact-tracing-germany/cwa-android) and installed version 1.10.1.1 from fdroid. It did an update immediatly. Shortly after that, CWA did its first update since 1,5 days automatically.

Since then (for 2 days) both CWA and its fork update regularly and automatically several times a day. The times displayed in the apps and in microG match.

**Comment by dsarkar** [comment]
@uuuu1234, @legendofa, @gehwissenlos, @ebora,
Some of you reported that the issue was resolved, some didn't give feedback?
Is this issue resolved for everybody? Many thanks for the feedback. Best wishes, and have some nice Easter-days.

**Comment by ebora** [comment]
I didn't have any issues since my last post.

By the way: I noticed just now that I got the first part of the microG Version numbers wrong in my posts. I've fixed that now.

Thanks for your great work and happy Easter!

**Comment by dsarkar** [comment]
Dear community, 

Thanks for contributing here. We will close this issue. Re-open this issue if necessary, however, before doing so try also workarounds described here:
EN https://www.coronawarn.app/en/faq/#no_risk_update
DE https://www.coronawarn.app/de/faq/#no_risk_update

Best wishes, DS

---
Corona-Warn-App Open Source Team
