### ISSUE TITLE
Improved error message when no internet connection is available

### ISSUE THREAD

**Issue by not-a-feature** [corona-warn-app/cwa-app-android#2062]
## Avoid duplicates
* [x] This enhancement request has not already been raised before (couldn't find anything)
* [x] Enhancement request is specific for Android only, for general issues/questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist) (on IOS the Error Message is better, thanks @Ein-Tim for checking)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
When scanning the QR-code with no internet connection available the only message shown is: `Error: There is a connection error (597)`. A non-tech user doesn't know what this means and/or what to do, they simply click the message away...

Unfortunatly i see this error/behaviour quiet often (π * :+1: ≈ 3% of all patients, ≈ 5% of the cwa users i see)
 <img alt="Screenshot_20210108-192222_Corona-Warn" src="https://user-images.githubusercontent.com/25013642/104134824-4b5f5d80-538c-11eb-90ea-811a4aa73e27.png" width=200></img>

## Suggested Enhancement
Improve the error message with a large "No Internet" / "Kein Internet" header.

## Expected Benefits
The user doesn't give up immediately und knows what to do.

---
Internal Tracking ID: [EXPOSUREAPP-4569](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4569)

**Comment by MikeMcC399** [comment]
Even better would be if the network connection was checked before the camera tried to read the QR code.

What is 597? That is a strange error code.

@not-a-feature 
I agree with you that a clearer message is needed with instructions that internet connection is necessary to scan the QR code.

**Comment by d4rken** [comment]
> What is 597? That is a strange error code.

https://github.com/corona-warn-app/cwa-app-android/blob/4f7664467cb9be280f39e5e61f9e0eb5f6063613/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/exception/http/CwaWebException.kt#L70-L73

**Comment by MikeMcC399** [comment]
@d4rken 
Unknown host exception doesn't seem to be the right reaction when there is no Internet connection.

I can reproduce this.
1. Select Flight mode (disables WiFi and mobile data)
2. Restart device (just to make sure there is no network data cached)
3. CWA > NEXT STEPS > Test with QR Code > ACCEPT
4. Attempt to scan in QC code
5. Note error message 
```
Error
Connection could not be established
(597). Please try again.
```

Device: Samsung Galaxy A50 SM-A505FN
Android version: 10
CWA version: 1.10.1

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4569](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4569)

**Comment by Ein-Tim** [comment]
No problem under iOS (Error message there: "Your Internet connection may have been lost. Please ensure that you are connected to the Internet")

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, Info forwarded to JIRA ticket.

**Comment by dsarkar** [comment]
@not-a-feature, @Ein-Tim FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/2177

**Comment by MikeMcC399** [comment]
@not-a-feature

Would you like to check this? **If the new error message meets your expectations, perhaps you would like to close the issue?**

The issue has been solved in [CWA Android 1.12](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.12.0) through "Improved popup text for state "non internet" (EXPOSUREAPP-4569)" #2177.

The following pop-up error message is now shown when attempting to scan a QR code with no Internet connection:

![Your internet connection may have been lost](https://user-images.githubusercontent.com/66998419/107752688-64f31c80-6d1f-11eb-94bb-536ef33730d2.jpg)

I opened also a related wishlist item https://github.com/corona-warn-app/cwa-wishlist/issues/342 to request that the Internet availability be checked **before** attempting a scan, instead of first scanning, then finding out that there is no Internet available, but at least the new error message is clearer than before.

**Comment by not-a-feature** [comment]
Looks good to me! Thanks for fixing it

**Comment by dsarkar** [comment]
@not-a-feature @MikeMcC399 @Ein-Tim and community,

Thanks for contributing here! Best wishes, DS

---
Corona-Warn-App Open Source Team
