### ISSUE TITLE
Enhance the visibility of the tracking status if location service is deactivated. 

### ISSUE THREAD

**Issue by Nebkaa** [corona-warn-app/cwa-app-android#2301]
## Requested enhancement 

Hello everybody, I would like to recommend that the layout of the main screen gets changed to enhance the visibility of the tracking status to make it easier for normal people to see that the app is not registering meetings with other people. 

## Expected Benefits
I met many people who did not realise and knew that the location services always needs to be active. I bet we have low numbers of active users due to this fact. With this change the numbers should increase and our overall tracking of this virus will enhance rapidly.

![20210205_203318](https://user-images.githubusercontent.com/78616812/107081166-8f5e4a80-67f2-11eb-973b-45a71061f562.jpg)
![20210205_203302](https://user-images.githubusercontent.com/78616812/107081170-91280e00-67f2-11eb-82e2-32bcceeffb63.jpg) 

Example pictures with this very easy to oversee change in the status area on top of this huge green square of the status report that looks like everything is good and working fine.

---
Internal tracking ID: [EXPOSUREAPP-5116](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5116)

**Comment by Nebkaa** [comment]
![20210205_203318](https://user-images.githubusercontent.com/78616812/107080845-19f27a00-67f2-11eb-8a99-f34ac5d8ac57.jpg)
![20210205_203302](https://user-images.githubusercontent.com/78616812/107080856-1eb72e00-67f2-11eb-9d87-0a63b567d571.jpg)


Example pictures with this very easy to oversee change in the status area on top of this huge green square of the status report that looks like everything is good and working fine.

**Comment by MikeMcC399** [comment]
@Nebkaa 
Thanks for your feedback from other people's experience! It's good to have a reality check.

Location (Standortdienste) is needed for CWA under Android, except for the latest version, Android 11 (see https://www.coronawarn.app/de/faq/#android_location for German language FAQ) so it is important that location is enabled.

If a CWA user disables location, then the Google Exposure Notification System immediately fires a notification which warns the user and instructs what to do:

![COVID-19-Benachrichtigungen inaktiv Standortermittlung](https://user-images.githubusercontent.com/66998419/107114720-6082bb80-6868-11eb-8115-b417395944ac.jpg)

This notification can be dismissed by the user without taking any other action, in which case there would be no new recording of Random IDs from other mobile devices.

Your screen shots show that the status in CWA changes from "RISIKO-ERMITTLUNG AKTIV" to "STANDORTDIENSTE DEAKTIVIERT". If you tap on the status, a detailed screen is shown with Risiko-Ermittlung Gestoppt showing:

![Risiko-Ermittlung Gestoppt](https://user-images.githubusercontent.com/66998419/107114786-ed2d7980-6868-11eb-82e4-f5168b58b6bc.jpg)

---
**Problems with current display**

A. The display is misleading, because it says "Risiko-Ermittlung dauerhaft aktiv" even though it is not collecting new Random IDs if location is disabled. This is related to the hot topic ""Risiko-Ermittlung dauerhaft aktiv" despite BlueTooth being disabled" https://github.com/corona-warn-app/cwa-app-android/issues/920.

B. The status information "STANDORTDIENSTE DEAKTIVIERT" is a correct description, however it does not inform the user on the main screen of the consequences of this status in clear words.

C. Only the notification from COVID-19-Benachrichtigungen tells the user what to do. If this notification is dismissed without taking action to enable location then there is no further reminder or instruction to the user.

**Possible improvements**
1. The status could be split into two different points:
i. risk evaluation (needs Internet)
ii. encounter recording (needs Bluetooth and location)
2. The history status "Risiko-Ermittlung dauerhaft aktiv" should **only** refer to the recording status, not the evaluation status. It doesn't matter if risks were evaluated or not in the past. It is only important that risks can currently (or recently e.g. in the last 24 or 36 hours) be evaluated using all the available historically recorded Random IDs.  If Random IDs were not recording during all of the last 14 days, then the status display should subtract the missing time from the displayed status.
3. If either Bluetooth or location settings are disabled and preventing recording of Random IDs then the main screen should plainly show not only the status of Bluetooth or location, but also the fact that this is preventing recording of Random IDs in a plain text description, together with clear instructions what to do to remedy the situation.

(Missing Internet is already covered by the app and it is not necessary to have a device permanently connected to Internet via WiFi or a mobile data connection. If no risk evaluation has been possible for more than 36 hours then a deadman notification is shown which alerts the user to the problem.)

**Comment by Nebkaa** [comment]
@MikeMcC399 
Thanks, yes the improvements you showed here are a better and more precise formulation of what i meant.
I believe Improvement 2 & 3 would help a lot of people if combined with a clear color indication that the recording is not active, while the information that the evaluation is working is not that relevant for the normal (non-technical) user.

As i said before I was shocked to see nurses and doctors not understand this fact, telling me that the app is green and the "Risiko-Ermittlung" is active, and therefore ID recording was running in their minds.

**Comment by Jo-Achim** [comment]
> As i said before I was shocked to see nurses and doctors not understand this fact, telling me that the app is green and the "Risiko-Ermittlung" is active, and therefore ID recording was running in their minds.

I think there are a number of misunderstandings..., see: https://github.com/corona-warn-app/cwa-wishlist/issues/352#issue-797677685.

**Comment by heinezen** [comment]
Hello everyone,

Thank you for your input. We have brought this topic to the attention of the development team. They will now investigate if the information in the UI is precise enough and how it could be adjusted. We will make a comment with updates here, if we hear anything new from the developer's side.

Regards,
CH

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 

I have another related question about the Exposure Logging status
(three-dot icon > Settings, first section)

If Bluetooth is disabled Exposure Logging is **Restricted**
If location is disabled Exposure Logging is **Stopped**
If both Bluetooth and location area disabled Exposure Logging is **Stopped**
If both Bluetooth and location area enabled Exposure Logging is **Active**

I don't understand why there is a difference between Bluetooth disabled and location disabled. Both location and Bluetooth are only needed by CWA to enable Bluetooth Low Energy. If either one or both are disabled then no Rolling Proximity Identifiers (RPI) can be exchanged. CWA continues to carry out exposure checks by pulling the keys from the server and comparing them to the ones stored on the device at regular intervals, however it can't collect any new ones.

- **What is the intended meaning of "Restricted" status compared to "Stopped" status?**
- **Why is the status for location disabled and Bluetooth disabled different, when the effect of disabling either one in terms of RPI exchange is the same?**

**Comment by dsarkar** [comment]
@MikeMcC399 I forwarded your comment and questions to the developers.

**Comment by mtwalli** [comment]
No planned
