### ISSUE TITLE
[BSI][20210225] Insecure Storage of Survey and Analytics Data

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-app-android#2462]
Rating: low

Description:
The 1.13 update of the Android CWA app stores sensitive information in an unencrypted form.
The newly added analytics and survey features add additional storage locations to the app. For the survey feature, a one-time password is stored. The analytics feature stores data the user provides. Both of these are stored unencrypted in the app’s sandbox storage.
A local attacker with escalated privileges can capture this unencrypted information from the app’s sandbox storage

Proof of concept:
The excerpt below shows the content of the analytics_localdata.xml

<img width="708" alt="PoC_insecure_risk_values" src="https://user-images.githubusercontent.com/65443025/109141544-2406f900-775e-11eb-9e10-2e3ca63ceed3.png">

<img width="723" alt="PoC_insecure_risk_values_2" src="https://user-images.githubusercontent.com/65443025/109141620-38e38c80-775e-11eb-88a7-a30e28192658.png">

Recommended controls:
Sensitive information about a user should be stored in an encrypted form. Therefore, it is recommended to store the database in an encrypted form. Encryption should be based on current best practices in terms of algorithms, cipher modes and key lengths.

---
Internal Tracking ID: [EXPOSUREAPP-5388](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5388)

**Comment by MikeMcC399** [comment]
@BSI-TF-CWA 
Are you aware of the comment in https://github.com/corona-warn-app/cwa-app-android/issues/1989#issuecomment-750288431 from @GisoSchroederSAP ?

> ... I urgently ask @BSI-TF-CWA , to follow the agreed procedure documented in:
https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md
Following this path ensures the findings are addressed to the right team, so the required procedure and documentation becomes transparent and efficient. Otherwise we may lose time and generate additional communication effort with disclosure of sensitive information.
>
> ... Thanks, @BSI-TF-CWA, for your input and for following the agreed procedure as described here: https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md


[SECURITY.md](https://github.com/corona-warn-app/cwa-app-android/blob/main/SECURITY.md) includes the text:

**Please do not report security vulnerabilities directly on GitHub. GitHub Issues can be publicly seen and therefore would result in a direct disclosure.**

**Comment by Diapolo** [comment]
I'm interested, is there any work in storing the data the BSS refers to in encrypted form? I remeber there were a few more remarks into that direction, so what's the current state?

**Comment by heinezen** [comment]
This issue is probably obsolete. Closed in favour of https://github.com/corona-warn-app/cwa-app-android/issues/2846

----
Corona-Warn-App Open Source Team
