### ISSUE TITLE
Set Up errors

### ISSUE THREAD

**Issue by Traciges** [corona-warn-app/cwa-app-android#2542]
Could not resolve all dependencies for configuration ':Corona-Warn-App:deviceDebugRuntimeClasspath'.
Could not create task ':Corona-Warn-App:minifyDeviceForTestersReleaseWithR8'.
Cannot query the value of this provider because it has no value available.

I set the app up, but I'm facing these three problems. In "Corona-Warn-App/build.gradle",  File, Properties and String cannot be resolved. Any ideas?

![Screenshot_1](https://user-images.githubusercontent.com/37974148/110218996-f0924000-7ebc-11eb-95b6-14cc257241cf.png)
![Screenshot_2](https://user-images.githubusercontent.com/37974148/110218998-f12ad680-7ebc-11eb-882c-233622ec4cd8.png)

**Comment by MikeMcC399** [comment]
@Traciges 
What tool are you using and what instructions did you give it?

You should probably address the warning message concerning the Android SDK license not accepted first.

What are you trying to achieve in general?

**Comment by Traciges** [comment]
I'm using Android Studio latest version and I also accepted all Android licenses with the sdkmanager.bat

![Screenshot_1](https://user-images.githubusercontent.com/37974148/110237354-ef542800-7f3b-11eb-855d-aca596bc713f.png)

In general, I'm trying to understand how the CWA works and I want to set it up on my local machine, so I can run the app in Android Studio

**Comment by MikeMcC399** [comment]
@Traciges 
I've never had to use the command line tool sdkmanager and I'm running Android Studio 4.1.2 on Windows 10.
That corresponds with what it says on https://developer.android.com/studio/command-line/sdkmanager.

Are you experienced with Android Studio or are you just starting up? If you are just starting up, have you built any other apps using your current installation?

There are limitations in what you can do with the app in Android Studio. Unless you have an allowlisted Goggle account, you cannot run the exposure notifications part of the app without getting errors occurring. (See https://developers.google.com/android/exposure-notifications/implementation-guide)

**Comment by Traciges** [comment]
Well I had to use the sdkmanager, cause it said I had unaccepted licences. Anyways, I just tried building an other app and it works totally fine

![Screenshot_1](https://user-images.githubusercontent.com/37974148/110239498-6e029280-7f47-11eb-9ee0-fe621dd6f760.png)

And I know that I can't run the app properly, because I have no allowlisted Google account, but I'm just curious, that I get errors at the basic syntax like "String, File and Properties". Right now, my goal is to just run the app in Android Studio. It doesn't have to work like it's intended

**Comment by MikeMcC399** [comment]
@Traciges 
It's good that you could prove you could build another app. I'm not sure what to suggest. It's working for me, so that suggests there is a problem with your environment.

If strange errors occur in Android Studio, it sometimes helps to use:
- Build > Clean Project
and if that doesn't help then
- File > Invalidate Caches / Restart...

**Comment by Traciges** [comment]
So, you can execute the App and run it (like above in my screenshot) in this virtual phone without any big errors? I tried your solutions but they don't work for me. It would help me a lot, if you could may send your source code to me and I can take a look, if it's really Android Studio or something else.

**Comment by MikeMcC399** [comment]
@Traciges 

I installed Android Studio on a clean virtual Windows machine and I can reproduce exactly your problem. 🙂 I'll see if I can find a solution.

**Comment by Traciges** [comment]
Thank you, I really appreciate your help in this situation

**Comment by MikeMcC399** [comment]
@Traciges 
The error about the license was the hint. Unfortunately Android Studio does not behave very graciously in this situation.

You need to install the Android 10.0 (Q) SDK because API 29 (Android 10) is specified in the build.gradle file(s).

There are two ways to get at this:

Open Android Studio and let it open the default (previously opened) project.
Select File > Settings then search for SDK to find the item
Appearance & Behavior > System Settings > Android SDK

In SDK Platforms, click on Android 10.0 (Q) API level 29 to activate the tick-mark, then click OK to install it.

You can also get to this menu by starting Android Studio, click Cancelling whilst it is loading the previous project, then select Configure  opening, then Configure > SDK Manager.

After I installed the Android 10 SDK then CWA was able to build on Android Studio 4.1.2 Windows.
I never noticed this problem before because when I installed Android Studio originally, Android 10 was the latest version so the Android 10 SDK was already installed by default. Since then Android 11 (R) has been released and there is also a pre-release of Android 11+ (S) available as SDK.

I hope that solves your issue!

**Comment by Traciges** [comment]
Thanks alot! It worked, I also had to delete the project and redownload it and now I can run it. Also had to uninstall the test device, because it was also based on Android 11...
Anyways, thank you very much, it's working now!

**Comment by Traciges** [comment]
By the way, do you know how to change the language in the app?

**Comment by MikeMcC399** [comment]
@Traciges 
> I also had to delete the project and redownload it and now I can run it.

I didn't need to download the project again after I installed the Android 10 SDK, but if it is working for you now, then that is not a concern.

> Also had to uninstall the test device, because it was also based on Android 11...

The app will run on Android 11, even though it is built for Android 10. That is normal compatibility for Android apps. 

> Anyways, thank you very much, it's working now!

You're welcome!

**Comment by Traciges** [comment]
Yeah I know, but for some it completly uninstalled the virtual phone so I had to set up another 😅

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks for taking care of @Traciges 

---
Internal Tracking ID: EXPOSUREAPP-2524

**Comment by MikeMcC399** [comment]
If anybody reading this is starting up with Android Studio then I would recommend [Android Developer Fundamentals](https://developer.android.com/courses/fundamentals-training/overview-v2) which is a good free (Java-based) course. 

Quite a few other free online courses are out-of-date, so if you are starting up it can be quite confusing to find exercise code which doesn't build without modification. The above course was updated in 2018, so it is "relatively" up-to-date.
