### ISSUE TITLE
Typo in privacy statement: closing list items missing a pointy bracket

### ISSUE THREAD

**Issue by redcatbear** [corona-warn-app/cwa-app-android#2585]
The following line contains a typo in the HTML closing `</li>` tag. The opening pointy bracket is missing.

https://github.com/corona-warn-app/cwa-app-android/blob/54342870ad7d4cc89d2dea0b85d3238ed635a229/Corona-Warn-App/src/main/assets/privacy_de.html#L324

---
Internal Tracking ID: [EXPOSUREAPP-5331](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5331)

**Comment by redcatbear** [comment]
Maybe you could add an HTML checker to your CI build?

**Comment by PhilippNowak96** [comment]
This is already fixed or more to say obsolete with 1.15, see the following commit: https://github.com/corona-warn-app/cwa-app-android/commit/a7a235f26c97865a2db78e6b2c59651f7f4fdaf0

**Comment by dsarkar** [comment]
@redcatbear Thanks for reporting.
@PhilippNowak96 Thanks for the hint.

**Comment by MikeMcC399** [comment]
The document for the 1.15.x release in German has been published to https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf

The html document https://github.com/corona-warn-app/cwa-app-android/blob/v1.15.1/Corona-Warn-App/src/main/assets/privacy_de.html doesn't contain any match for the string `./li>` any more. 

The relevant section of the document:
5. Welche Daten werden verarbeitet? 
e. Datenspende

has been largely re-written and the sub-section is now labelled:

 e. Nutzungsdaten (Datenspende)

---
It should be possible to close this issue now, since 1.15.1 has been released and the HTML coding error has been removed.

**Comment by dsarkar** [comment]
Dear @redcatbear, see https://github.com/corona-warn-app/cwa-app-android/issues/2585#issuecomment-808382764. We suggest closing this issue. Thanks for contributing here. Best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by redcatbear** [comment]
Hi @dsarkar, yes, closing the ticket was OK. Sorry that I didn't realize that you were waiting for my answer. I think the situation was pretty obvious. If the text changed, this ticket is obsolete.

I still recommend using an HTML checker in the CI build, just in case you don't already.
