### ISSUE TITLE
[Small problem] Different display representations between 'Dark Mode' & 'Normal Mode' ...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-app-android#2672]
Hi,
there is a little misrepresentation ... see markings in the screenshots: 
![Screenshot_20210323-122038_2](https://user-images.githubusercontent.com/21124877/112302127-02d0f400-8c9b-11eb-97d5-39b4cbdab93f.jpg)

and
![Screenshot_20210323-122011_2](https://user-images.githubusercontent.com/21124877/112302166-0e241f80-8c9b-11eb-8b21-a26534ca1cc9.jpg)

Best regards, Joachim.

Android 10 with Android security update: February 1st, 2021
Nokia 7.1, Build: 00WW_4_16B_SP04
CWA version: 1.14.3
ENF: 18210613000
NetGuard Pro 2.295
Norton 360, v.5.4.1.5649

---
Internal Tracking ID: [EXPOSUREAPP-5923](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5923).

**Comment by MikeMcC399** [comment]
@Jo-Achim 

The text "7-Tage-Mittelwert" wraps onto a new line by breaking the word "Mittelwert" in Android 10 with Font size (Schriftgröße) increased.
It affects other tiles also in light mode, not just dark mode.

This is a problem with the locale set to Deutsch because the text is long. With the locale set to English the problem doesn't appear because "7-Day Average" can be broken onto two lines at the space without affecting the readability. There is no space in "7-Tage-Mittelwert" which would indicate a preferred place to break the text, instead Android takes one or more letters from the end of the string and puts them on the next line.

I don't know if there is a simple fix for this. It will be interesting to see what the response from the devs is.

**Comment by dsarkar** [comment]
Dear @Jo-Achim,
 Thank you for your report. Next time, could you please use the bug template (Thanks!). Internal Tracking ID: [EXPOSUREAPP-5923](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5923). Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
It's part of a generic problem of how Android breaks strings when then don't fit the available space.

The following screen shot of part of the statistics tiles is from an Android 10 tablet with font size set to maximum.

![Statistics with large font](https://user-images.githubusercontent.com/66998419/112179118-af0ece00-8bfa-11eb-8be1-4a1136886ec2.jpg)

Maybe a workaround is to always have a line break(s) in the strings? So for instance display:
```
7-Tage-
Mittelwert
```

```
Bestätigte
Neu-
infektionen
```

```
7-Tage-
Inzidenz
```

**Comment by Jo-Achim** [comment]
@MikeMcC399, 
ok, that's logical. But who determines the size of the available space that is necessary to display the corresponding text (CWA or Google)? Here specifically / only between 'normal' and 'dark' mode.

Best regards, Joachim.

**Comment by MikeMcC399** [comment]
@Jo-Achim 

I think I found the problem!

The dark mode image is wider than the light mode image:
- https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/drawable/ic_main_illustration_infection.xml `android:width="107dp"`
- https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_infection.xml `android:width="134dp"`

So there is less room available for the text when the mode is switched to dark.

The layout is defined in https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml.

I used the Android Studio Layout Inspector to look into the dynamic display.

> Added: I also noticed that in 'Dark' mode the line "RISK-DETERMINATION ACTIVE" is scrolled up out of the window; not in "normal" mode. See: new screenshots above.

Would you like to open a new issue for this? I can see also see that the scrolling of the app status works differently in light and dark mode.

@dsarkar 
Could you pass the finding about the graphics size on to the devs for EXPOSUREAPP-5923?

**Comment by Jo-Achim** [comment]
@MikeMcC399,

thanks.

> Added: I also noticed that in 'Dark' mode the line "RISK-DETERMINATION ACTIVE" is scrolled up out of the window; not in "normal" mode. See: new screenshots above.
> 
> Would you like to open a new issue for this? I can see also see that the scrolling of the app status works differently in light and dark mode.

Tomorrow, I create a new issue. 
_But before_, I will inform, that the problem occurs in 'normal' mode too. In conjunction with 'in / from which position you scroll the screen'. Details, I couldn't find out at this time.

Best regards, Joachim.

**Comment by dsarkar** [comment]
@MikeMcC399 @Jo-Achim Thanks analysing, I will forward your findings to EXPOSUREAPP-5923.

**Comment by MikeMcC399** [comment]
@dsarkar 
Changing
https://github.com/corona-warn-app/cwa-app-android/blob/66055425822758f2575de50d7e82b371bb81370c/Corona-Warn-App/src/main/res/layout/home_statistics_cards_infections_layout.xml#L17

to `android:layout_width="107dp"`

could be a temporary workaround to the issue, which would shrink the display of the dark mode graphic https://github.com/corona-warn-app/cwa-app-android/blob/main/Corona-Warn-App/src/main/res/drawable-night/ic_main_illustration_infection.xml to match the width of the regular one.

I checked the widths of the vector graphics on the other three statistics tiles and they all have identical widths for regular and dark mode. It seems that the issue is only for the infection illustration.

**Comment by Jo-Achim** [comment]
@MikeMcC399.

> I used the Android Studio Layout Inspector to look into the dynamic display.
> 
> > Added: I also noticed that in 'Dark' mode the line "RISK-DETERMINATION ACTIVE" is scrolled up out of the window; not in "normal" mode. See: new screenshots above.
> 
> Would you like to open a new issue for this? I can see also see that the scrolling of the app status works differently in light and dark mode.

> Tomorrow, I create a new issue.
> _But before_, I will inform, that the problem occurs in 'normal' mode too. In conjunction with 'in / from which position you scroll the screen'. Details, I couldn't find out at this time.

No, I'm not going to create a new issue.
The scrolling behavior with regard to the line "RISK-DETERMINATION ACTIVE" depends on where you scroll. If in the upper part of the window is scrolled, "RISK-DETERMINATION ACTIVE" is pushed upwards. If you scroll in the lower part of the window (at the height of the fields "Confirmed new infections" / "Bestätigte Neuinfektionen"), the line "RISK-DETERMINATION ACTIVE" remains visible.

**This scrolling behavior is identical in 'normal' and 'dark' mode! And therefore not an issue.**

Best regards, Joachim.

**Comment by dsarkar** [comment]
@Jo-Achim Thanks for your feedback.

@MikeMcC399 I will forward your findings to the developers. Thanks!

**Comment by dsarkar** [comment]
@MikeMcC399 see PR https://github.com/corona-warn-app/cwa-app-android/pull/2691 and comment in OP.

**Comment by MikeMcC399** [comment]
@dsarkar 
The fix looks good. The dark vector graphic has been reduced in size so it is the same width as the regular graphic.

**Comment by fynngodau** [comment]
2.0 has been released – can this issue be closed?

**Comment by Jo-Achim** [comment]
Yes!
