### ISSUE TITLE
Warn about deactivated battery optimization on main screen

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#2682]
### Current situation

Over at CCTG, we have talked to users who had problems with background exposure notifications. In a lot of cases, the underlying issue was simply that users had forgotten to disable battery optimizations for the app.

Since CWA is also not able to sync reliably in the background when battery optimizations are enabled, I feel this is a topic that could be dealt with in CWA.

### Suggestion

Show a warning on the main screen that informs users that they should change their device's settings to disable battery optimization.

### Expected benefits

Users might read the text and be more aware of the cause of issues they might encounter, and might try to fix them themselves accordingly, reducing workload for technical support.

---
Related issues
https://github.com/corona-warn-app/cwa-app-android/issues/1606
https://github.com/corona-warn-app/cwa-app-android/issues/2683

----
Internal Tracking-ID: [EXPOSUREAPP-6663](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-6663)

**Comment by thomasaugsten** [comment]
For the CWA the battery optimization is not so critical because we are whitelisted from the battery optimization from all vendors and the Google Play Service wakes all 6hours the CWA up.

**Comment by MikeMcC399** [comment]
Perhaps if the deadman notification is triggered (after 36 hours) there could be a check done to see if battery optimization is enabled (or to use CWA app terminology, Prioritized Background Activity is disabled)? If so, the user could additionally be given the hint to disable battery optimization (enable Prioritized Background Activity) if possible.

![Your Risk Status expanded](https://user-images.githubusercontent.com/66998419/113306705-a7d77680-9304-11eb-86cc-9f8db4708aef.jpg)

**Comment by di-sc** [comment]
I had the same issue with CCTG on my phone recently and I found out the reason why it was not working because of the contact overview screen which is not available for CWA. If the CWA does not work, I won't recognize at all.
My feeling is that disabling the battery optimization is too complex for most users. It is not so clear what to do **and** how important it is to do it. For the user it is not obvious that the app will work for some days but may stop working later because of this battery optimization setting.
### My suggestion:
Add an algorithm to check if the app is working. If the user does not collect any new Ids anymore the app may not work anymore. By using the number of Ids that were collected in recent days it can be forcasted how likely it is that the user doesn't have had any contacts or if the app is not working.
If this algorithm detects that the app may not work anymore it should:
- Add a hint or notification to the main screen that advises the user to disable Battery Optimization for that App
- Add a possibility to the user so that she/he can manually reset the app herself/himself

**Comment by fynngodau** [comment]
> If the user does not collect any new Ids anymore the app may not work anymore.

As mentioned in the CCTG issue, this is not technically possible with Google's Exposure Notifications API.

**Comment by vaubaehn** [comment]
@di-sc @fynngodau 
Fynn is right, CWA can't do anything about it, because it already went to sleep and is not having enough processor time anymore, and also the ENS Api does not provide an function to check the amount of collected RPIs (= contacts). Also, as long as the device/bluetooth is not switched off, the phone will continue to receive beacons.
If at all, then the Google Exposure Notification System would need to add such a feature: if there is a contact tracing app installed, but it stopped to provide diagnosis keys for matching for some time (more than 36 hours for example), then the ENS could notify the user, that user should open the contact tracing app to wake it up again. How's this?
