### ISSUE TITLE
Old registration date is displayed after receiving result of a new test.

### ISSUE THREAD

**Issue by dg76** [corona-warn-app/cwa-app-android#2699]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

The bug was already reported here but there it says it would have been fixed in version 1.11 but it is still present in 1.15.1:

https://github.com/corona-warn-app/cwa-app-android/issues/2005

## Technical details

- Device name: Pixel 2 XL
- Android version: 11
- App version: 1.15.1

## Describe the bug

In December I added a test to the app. When I had received the result, I have removed the test. Yesterday I have added a new test to the app. Today I got the result but it displays the registration date of December instead of March:

![Screenshot](https://user-images.githubusercontent.com/17218461/112720100-b553c180-8efc-11eb-9a6f-39261a5a01e1.png)

## Steps to reproduce the issue

1. Add a test.
2. Remove a test.
3. Wait a few days.
4. Add a test.
5. Receive a result. The "Registered at" date is wrong/old.

## Expected behaviour

The new "Registered at" date should be displayed.

---
Internal Tracking ID: [EXPOSUREAPP-4484](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4484)

**Comment by MikeMcC399** [comment]
@dg76 
As you say, there was an issue fixed with https://github.com/corona-warn-app/cwa-app-android/issues/2005 that was released with  1.11. (That version was released on Jan 28, 2021 - see https://www.coronawarn.app/en/blog/2021-01-28-corona-warn-app-version-1-11/.)  The title of the relevant PR https://github.com/corona-warn-app/cwa-app-android/pull/2024 was "Reset the initial registration date on test removal correctly (EXPOSUREAPP-4484)".

Your previous test was registered on 14.12.2020 and according to the other blog posts on https://www.coronawarn.app/en/blog/ the latest release at that date was version 1.7.

So most probably you deleted the previous test using version 1.7 which did not include the fix.

I think the devs need to look at this again, because if a user registers a new test the only relevant date is the latest QR code scan date. Any previously stored test registration dates need to be overwritten. It should not depend on what (older) version a previous test may have been deleted with.

I will try the following repro steps:
1. Install CWA 1.7
2. Scan a QR code
3. Delete the test
4. Update to CWA 1.15.1
5. Wait a day
6. Scan a new QR code
7. Check the test date

**Comment by dsarkar** [comment]
@dg76 @MikeMcC399 Thanks for reporting and summary.

First of all: Although date date is wrong, the correct result will be retrieved. It is a display issue.

Context:
There was a fix PR in release 1.11: https://github.com/corona-warn-app/cwa-app-android/pull/2024
There was an additional fix PR in  release 1.15: https://github.com/corona-warn-app/cwa-app-android/pull/2638 

After the first fix (1.11), the following problem persisted: Even after a scan of a QR code after updating to 1.11 it showed the old date. Another test scan after that one would show the correct date.

After the second fix (1.15), the following problem persists: A test scanned before updating to CWA 1.15 would keep showing the old date. A test scanned after updaten should now not be showing the old date but the correct one.

**Comment by dsarkar** [comment]
@dg76 We will inform the developers.
@MikeMcC399 Thank you very much for looking into this.

**Comment by dg76** [comment]
Thank you for clarifying that the result is correct!

You are probably right about the versions. I can see that an update of the "Corona-Warn-App" was installed 14 hours ago. I scanned the QR code _before_ installing the update and got and viewed the result _after_ installing the update. So if I understand you correctly the issue is fixed now for new QR codes if the users use the latest version? Then it is fine for me, I just wanted you to know the problem. :-)

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-4484](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-4484)

**Comment by dsarkar** [comment]
@dg76 OK, thank you ver much for the feedback! Yes, if you scanned the QR code before updating to CWA 1.15 it will keep showing the old date. That is a know problem, and my understand is that this will not be fixed. Any scans after updating to 1.15 should show the correct date. Important, this is an older issue: the correct test will be retrieved, not the old one. The shown date is wrong (only).

**Comment by dsarkar** [comment]
@dg76 
@MikeMcC399 
I think in that case we can close this issue, do you agree ?

**Comment by dg76** [comment]
Yes, we can close it. Thank you very much for your quick feedback! :-)

**Comment by MikeMcC399** [comment]
@dsarkar 

It sounds like the remaining problem has been resolved with "If there is an initialTestResultReceivedTimestamp it may be (EXPOSUREAPP-4484)" https://github.com/corona-warn-app/cwa-app-android/pull/2638 which was merged into [release 1.15.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v1.15.1).

I will continue the planned test tomorrow. If the new scan tomorrow shows tomorrow's date, then everything is fine.

**Comment by dsarkar** [comment]
Hi @MikeMcC399, did you do the test you planned?

**Comment by MikeMcC399** [comment]
@dsarkar 
> did you do the test you planned?

Yes, I did the test and it was successful. I didn't report back here previously because the issue was already closed. All is good!

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks¡
