### ISSUE TITLE
Improve "check your status" message

### ISSUE THREAD

**Issue by CaroDD** [corona-warn-app/cwa-app-android#2722]
When you get a message like "check your status regularly", it´s a bit annoying because in my mind/opinion it could say if there is a risk or not (I think it sends me a push message in case there is a risky person or if I should do a test). 
But at the moment I have to open the app manually and see that there is no risk. It would be much easier if the message told me my status.

**Comment by MikeMcC399** [comment]
> (I think it sends me a push message in case there is a risky person or if I should do a test).

It is not strictly a push message. The app actually polls the server at regular intervals to get Diagnosis Keys from infected users which your phone then compares with the keys stored on your device. If the polling isn't working, then the app can't do any new comparisons and therefore cannot warn you. The warning it sounds like you are getting goes under the name of "deadman notification".  This appears after 36 hours have elapsed since last being able to do a risk check with new data.

![Your Risk Status expanded](https://user-images.githubusercontent.com/66998419/113188896-e57fc500-925a-11eb-81e3-a8bcfadb3c82.jpg)

**Comment by dsarkar** [comment]
Hi @CaroDD, 

Thank you for contributing here. See this https://github.com/corona-warn-app/cwa-app-android/issues/2722#issuecomment-811010383 and we would appreciate your feedback in order to have a look at your issue. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@CaroDD 

Are you interested in pursuing this issue further? If so, we would need some details from you. You can otherwise close the issue yourself (see button below) if you wish.

**Comment by heinezen** [comment]
Closed due to missing feedback.

----
Corona-Warn-App Open Source Team
