### ISSUE TITLE
"Daten herunterladen und Prüfen" funktioniert nicht automatisch?

### ISSUE THREAD

**Issue by leobm** [corona-warn-app/cwa-app-android#2750]
Hi,

I am not sure if this function works really automatically. I feel like I have to open the app every day so that it downloads and checks the data (keys).

I do these following steps and this is the current behavior. 

1. today I open the app for the first time at e.g. 15:27.
    It shows me that the app is downloading and checking the data.
2. after that the risk rating is displayed e.g..
    "Niedriges Risiko" 
      - Keine Risiko-Begenungen 
      - Aktualisiert: Heute at 15:28
3. I close the app again
4. I open the app again. No new data is downloaded or 
    checked. The last status is the current status.    
    "Niedriges Risiko" 
      - Keine Risiko-Begenungen 
      - Aktualisiert: Heute at 15:28

Expected Behavior:
The app downloads and checks the data on its own (e.g. always at night at 2:00am ).
Then when I open the app the data should not be downloaded again and checked. To me it looks like the data is only updated if I open the app once a day? I also can't check if the app has downloaded and checked the data before. 
Some kind of history would be desirable

Device: HUAWEI Mate 20 lite 
Model: SNE-LX1
Android Version: 10
Kervel version: 4.14.116
Security patch level: February 1, 2021
Corona Warn App Version: 1.15.2
ENF Version: 18210915000

Risiko-Ermittlung: **Aktiv**
Mitteilungen:  **An**
Priorisierte Hintergrundaktivität: **An**
Datenspende: **An**

**Weitere Android Einstellungen:**

Akkuoptimierung: **Nicht zulassen**
App-Start: "Beim Startup oder im Hintergrund starten" **Aktiv**
Sekundärer Start: "Kann von anderen Apps gestartet werden" **Aktiv**
Im Hintergrund ausführen: "App im Hintergrund weiter ausführen" **Aktiv**

**Comment by MikeMcC399** [comment]
@leobm 

There is an FAQ article concerning what you discuss. It sounds like you are using a German user interface, so take a look at https://www.coronawarn.app/de/faq/#no_risk_update

There is a link in that article to HUAWEI problems https://www.coronawarn.app/de/faq/#huawei_honor , however the link in that article to https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690615368 doesn't seem to be so helpful because you mention that you have a recent update to your phone.

If your phone has a properly functioning Google Play services installation you can show the history of exposure checks through the Google UI.

1. In den Android Einstellungen, "Google" wählen
2. Dann "COVID-19-Benachrichtigungen" auswählen
3. Rechts oben das Drei-Punkte-Symbol antippen
4. Dort "Überprüfungen auf mögliche Begegnungen" antippen
5. Jetzt wird eine Liste allen Überprüfungen der letzten (maximal 16 Tagen)  gezeigt

See if you can find out anything useful from the above information and what the exposure log on your device is telling you.

**Comment by leobm** [comment]
@MikeMcC399
Hello Mike ,
thank you. The app seems to really do something every day (loading and checking keys).
Today, however, only when I opened the app at 15:27. Maybe that's why my confusion. Somehow you should see the history in the app itself. I wouldn't have come across the view you mentioned now without your help.   

![Screenshot_20210406_172528_com google android gms](https://user-images.githubusercontent.com/25712/113736889-cb802f80-96fd-11eb-922d-3beec6ae61ef.jpg)

**Comment by MikeMcC399** [comment]
@leobm 

From the history you posted, it looks like it is doing the exposure checks regularly.

If you are connected to WiFi the checks are done about every 4 hours. If your Internet network connection is only through mobile data then the app tries to do the check about once every 24 hours.

If no check is possible after 36 hours you will get a warning (called a "deadman notification") that you should open the app to start a check. So if you are not getting this warning, this is a sign that the background checks are being done.

The app only shows you the timestamp of the last exposure check, as you noticed. You could make an enhancement request if you think that the app should show the full history of exposure checks (or perhaps link directly into the Google user interface).
