### ISSUE TITLE
Google Bug? Deleting CWA's Data used to also purge stored RPIs/TEKs from ENS

### ISSUE THREAD

**Issue by vaubaehn** [corona-warn-app/cwa-app-android#2795]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/) - **Actually, the FAQ seems to be outdated for the here reported issue, and should be updated accordingly**
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue - **probably it was reported in some other context, but it was not considered a main issue yet.**

## Technical details

- Device name: Probably all devices
- Android version: Probably all versions
- App version: Probably all releases
- ENS version: Probably all until today?

## Describe the bug

Do you remember our good old friend, issue #642 ? Thank's to @d4rken , the causes had been identified (buggy tink broke access to Encrypted Shared Preferences) and different solutions were found (in the end, migrating to common Shared Prefs).
For months, we had been stucked in that issue. Before it was resolved, the only way to regain access to CWA without uninstalling it, was to delete CWA's app data, hence causing a reinitialization of ESP with the loss of CWA's internal databases. I wrote a walkthrough for affected users here: https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-690615473 which is now clearly outdated and based on wrong assumptions.
Quite soon the question arised, if clearing CWA's app data also clears data from ENS, because the ENS logs were deleted, see e.g., here: https://github.com/corona-warn-app/cwa-app-android/issues/1053#issuecomment-678381760
We tried to clarify with @thomasaugsten , whether RPIs/TEKs are touched, when CWA's data is deleted via Android settings. His answer was, it's all safe: https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-688267231
Unfortunately, some time later it came apparent, that this might not be the case. @kbobrowski dived into it for research, and he returned with bad news: https://github.com/corona-warn-app/cwa-app-android/issues/1084#issuecomment-719642452 - slack users in COVID apps can find the connected thread here: https://covidapps.slack.com/archives/C0194ML0MLN/p1604061514489300?thread_ts=1604057577.482800&cid=C0194ML0MLN
A safe way to prevent ENS to purge RPIs/TEKs was only, to have another ENS-based contact tracing app installed (e.g., Immuni).

In my opinion, it is critical, that clearing CWA's app data may also delete ENS RPIs/TEKs, as many users might do so (un-)intentionally without knowing, that they can't be warned of any high risk contact of the past 14 days, or warn others in case of their infection, due to a clean ENS database.

**It is unclear, if the current version of ENS still behaves in the same way like 5 months ago, or if Google changed that behaviour.**

## Steps to reproduce the issue

1. Take care, that CWA is the only installed contact tracing app on your phone. Root your phone, and find databases for RPIs/TEKs inside ENS folder paths (see #1238).
2. Feed ENS with RPIs and TEKs (OR: feed ENS with a crafted high risk RPI, then run risk assessment using a fitting DK, you should receive a red alert.)
3. Take a snapshot of RPI and TEK dbs.
4. Clear CWA's data and cache via Android > settings > apps > CWA > data > clear...
5. Compare the new RPI/TEK dbs against the snapshot. If the formerly reported behaviour of ENS to purge RPIs/TEKs after being triggered by clearing App data/cache is still the same, the current db versions will differ at least in size from the snapshot in step 3. (Or: run risk assessment again with the DK from step 2. Still red alert?)

## Expected behaviour

In my opinion, ENS must not under no circumstances delete RPIs/TEKs after a simple reset of CWA's data/cache. There may be many users who may have the habit to sanitize their phones by regularly deleting app data, e.g. to free up some space for a limited period of time (like I do...). Other users may have run into problems with their CWA setup, trying to overcome it by deleting app data without knowing, that all RPIs/TEKs for risk assessment/uploading TEKs in case of infection are probably lost.
The only way to delete RPIs/TEKs should be via the UI of ENS, or by uninstalling the last remaining contact tracing app.

## Possible Fix
First, try to find out, if ENS still is triggered to purge its data, when CWA data is cleared (manually) via Android's settings menu.
If this is the case, I suggest to contact Google again, and ask them, if this is really intended behaviour (and why), or if this is a bug that was not on their radar yet. Would be good to have a final clarification on that issue.

## Additional context

If this was indeed a bug which was/will be resolved with a later ENS version, you may re-evaluate the handling of resetting CWA's in-app data. For now, it seems to get more and more complex, as more and more features are added or extended, see e.g., #2785 . If current/future ENS won't clear RPIs/TEKs anymore when clearing CWA app data, you could probably implement a simple `format c: ` (just kidding), I mean, a system-integrated function call to clear app data to reset in-app data, which could facilitate future development, if this was possible to handle it that way.

Cheers, V.

Edit: took off 'cache' from the title, as I believe RPIs/TEKs were only erased by deleting app data, not app cache. It found its way to the title as it is my habit to always clear data and cache in one go...

---
Internal Tracking ID: [EXPOSUREAPP-5956](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5956)

**Comment by MikeMcC399** [comment]
There is another related issue:

- [Google Exposure Notifications System should optionally preserve exposure data on app uninstall - wishlist #164](https://github.com/corona-warn-app/cwa-wishlist/issues/164)

The actions of clearing the CWA app data or uninstalling it are equivalent as far as Google Exposure Notifications System is concerned. If there is no other COVID-19 app remaining installed then the keys will be deleted.

Possibly the FAQ [Are the exposure logs/random IDs removed from my phone when I uninstall the app?](https://www.coronawarn.app/en/faq/#delete_random_ids) should be extended to warn against deleting app data, although anybody who accesses this level of data reset should expect to lose data if they execute "Clear data" on an app using the Android operating system UI.

I don't believe that anybody has been recommending using "Clear data" for many months and I have not seen any reports here in the Android repository since that time from people who have done it and got in trouble.

**Comment by vaubaehn** [comment]
@MikeMcC399 

> [...] although anybody who accesses this level of data reset should expect to lose data if they execute "Clear data" on an app using the Android operating system UI.

Anybody on this level of experience is probably informed well enough to not expect losing RPIs/TEKs, because they usually know that CWA and ENS hold different type of data, and losing the much more critical ENS data is against the common logic of deleting app data (not system data) in general. Otherwise, there wouldn't have been these concerns and confusing in our past discussions, e g. with @thomasaugsten (see above).

> I don't believe that anybody has been recommending using "Clear data" for many months and I have not seen any reports here in the Android repository since that time from people who have done it and got in trouble.

Why do you note this, what is your conclusion or recommendation? Is it not worth to try to clarify things up, finally?

**Comment by MikeMcC399** [comment]
@vaubaehn 

There was an answer to this by @thomasaugsten in https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-719786581 on Oct 30, 2020:

> I doubled check and it looks Google is now registering the data deleting and turns off the exposure notification framework the leads to a key wiping. We will update our FAQ

Does that answer your question? Or do you think that Google should be consulted again?

Just by coincidence I noticed a documentation inconsistency in the 148 page document [Datenschutz-Folgenabschätzung](https://www.coronawarn.app/assets/documents/cwa-datenschutz-folgenabschaetzung.pdf), so I opened a new issue: [Datenschutz-Folgenabschätzung says deinstallation keeps "Begegnungsaufzeichnung](https://github.com/corona-warn-app/cwa-website/issues/1066).

BTW: Deleting the app data via the operating system will also delete the Contact Journal and any registered test. The Contact Journal can be exported and re-entered by hand. A registered test cannot be re-entered because the process only allows a test QR code to be scanned and registered once.

**Comment by vaubaehn** [comment]
@MikeMcC399 
I think you missed the point. Did you read the OP carefully?

**Comment by vaubaehn** [comment]
@dsarkar 
Like @MikeMcC399 cited @thomasaugsten from https://github.com/corona-warn-app/cwa-app-android/issues/642#issuecomment-719786581 , there was the idea to update the FAQ accordingly, that CWA's data cleaning also cleans ENS data (losing ability for getting warned or warning others related to past 14 days). If I didn't overlook anything, nothing was changed in the FAQ, was it? Should we open an issue for that in the website repo?
As long as the behavior is still the same (or not known to have changed since then), I think it makes much sense to warn not to delete CWA data unless it's absolutely necessary.
If this is not already the case, I hope Google will change that behavior in the future.

**Comment by MikeMcC399** [comment]
@vaubaehn 
> I think you missed the point. Did you read the OP carefully?

I'm sorry you think I missed your point. I did my best to understand your intentions.

---
I have opened a new issue https://github.com/corona-warn-app/cwa-website/issues/1067 and a PR https://github.com/corona-warn-app/cwa-website/pull/1068 to update the FAQs

- Are the exposure logs/random IDs removed from my phone when I uninstall the app?<br>https://www.coronawarn.app/en/faq/#delete_random_ids

- Werden die gesammelten Zufalls-IDs beim Deinstallieren der App entfernt?<br>https://www.coronawarn.app/de/faq/#delete_random_ids

If the PR is approved then the consequences of using the Android operating system "Clear data" function on the "Corona-Warn" app entry will be better described.

---

In your original submission here (https://github.com/corona-warn-app/cwa-app-android/issues/2795), under "Expected behaviour" you stated that "... ENS must not under no circumstances delete RPIs/TEKs after a simple reset of CWA's data ...". That would be a change request to Google, which the Open Source Team will need to handle.

**Comment by vaubaehn** [comment]
@MikeMcC399 
Thanks for all your efforts, I highly appreciate them.

> That would be a change request to Google, which the Open Source Team will need to handle.

Yes, exactly. But as 5 months passed by since someone took a look into that 'erasing behaviour', it already might have been changed by Google (to not delete ENS data), but that would need to be verified which is not trivial.

I admit that my OP is a bit long and therefore maybe not too easy to understand. I tried to draw a sketch of the whole process to provide a better understanding and framing of the overall context, but maybe that turned it to the opposite?

**Comment by MikeMcC399** [comment]
@vaubaehn 
> ... as 5 months passed by since someone took a look into that 'erasing behaviour', it already might have been changed by Google (to not delete ENS data), but that would need to be verified which is not trivial.

I checked with:
Device name: Samsung Galaxy A5 (2017)
Android version: 8.0.0
App version: 1.15.2
ENS version: 18210915000

Using the steps:

1. Install CWA
2. Settings > Google > COVID-19 Exposure Notifications 
3. Ensure that "Corona-Warn" is the only app listed
4. Tap Three-dot icon > Exposure checks
5. Note the history of exposure checks
6. Settings > Apps > Corona-Warn > Storage > "CLEAR DATA"
7. Open CWA and run through onboarding including "ACTIVATE EXPOSURE LOGGING"
8. Wait for risk to be evaluated
9. Repeat step 2. & 4. and note that the previous history of Exposure checks has been completely replaced by one new entry only

I don't believe that ENS has changed in this respect. I don't however have a rooted device, so I cannot use your steps to reproduce or look any deeper. I can only say that the exposure check history is deleted. I assume that the key data is also deleted, but I cannot prove it.

**Comment by dsarkar** [comment]
@vaubaehn @MikeMcC399 I will come back to you.

---
Internal Tracking ID: [EXPOSUREAPP-5956](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-5956)

**Comment by vaubaehn** [comment]
@dsarkar 
Hi Dipankar, thanks a lot.

@MikeMcC399 
If I remember correctly, the deletion of the Exposure Log of ENS was not necessarily associated with deletion of RPIs/TEKs. Both were triggered by deletion of CWA data, but while the Exposure Log was always deleted, RPIs were erased only, when there was no other contact tracing app installed but CWA.
As it's long ago we handled that issue in other contexts here, I'm struggling to find the original comments. @daimpi , can you jump in here, Do you remember more in this context or remember the related GH comments?

**Comment by MikeMcC399** [comment]
@vaubaehn 
I recently had a red risk tile on a tablet which never leaves my desk, so even if it did have a Bluetooth exchange with another device whose owner submitted an infection, there was actually never any other person physically near that device on the day showing the exposure.

1. I reset the app
2. I used the Google UI to "Delete random IDs" v1.8 (220618000)

Even after doing that the red risk tile still appeared. I uninstalled CWA and reinstalled it, then the red risk went away.

I don't really want to be reverse-engineering what Google Exposure Notifications System is doing. That is too unreliable. Really we need Google / CWA Open Source Team to document what should be happening.
