### ISSUE TITLE
Execution failed for task ':Server-Protocol-Buffer:generateProto'. > protoc: stdout: . 

### ISSUE THREAD

**Issue by pepintos** [corona-warn-app/cwa-app-android#2817]
## Avoid duplicates
* [ ] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [ ] Bug is not already reported in another issue

## Technical details

- Device name:
- Android version:
- App version:

## Additional context

I've tried with different versions and I always have the same error. I haven't changed any code.

Execution failed for task ':Server-Protocol-Buffer:generateProto'.
> protoc: stdout: . stderr: internal/v2/event_registration_parameters.proto: warning: Import internal/v2/risk_calculation_parameters.proto but not used.
  ...\cwa-app-android-2.0.0-RC4\Server-Protocol-Buffer\build/generated/source/proto/main/javalite/de/rki/coronawarnapp/server/protocols/external/exposurenotification/TemporaryExposureKeyExportOuterClass.java: No such file or directory

**Comment by MikeMcC399** [comment]
@pepintos 

I assume that you are trying to build the app using Android Studio. Is that correct? You didn't give any steps to reproduce or any environment information. What is your level of developer experience?

Often this type of error can be mitigated by selecting Build > Clean Project in Android Studio.

Could you please edit and shorten the title of this issue? It is very long.

**Comment by pepintos** [comment]
Yes, I'm using Android Studio.
I have done simple apps with Android Studio before.
And I've also tried Build > Clean Project, but when I run it again it still appears the same error

**Comment by MikeMcC399** [comment]
@pepintos 
> And I've also tried Build > Clean Project, but when I run it again it still appears the same error

Another possibility to fix weird build errors is File > Invalidate Caches / Restart ...

**Comment by pepintos** [comment]
It happens the same

**Comment by MikeMcC399** [comment]
@pepintos 
It seems that something is not right on your development system.

Which version of Android Studio are you using and on what operating system? I am using Android Studio 4.1.3 on Windows 10 and I have no issue in building the release/2.0.x branch of the app.

Your clone of the app may be corrupted. You might try cloning a fresh copy of the app from GitHub.

**Comment by pepintos** [comment]
I am using the latest Android Studio version on Windows 10.
I have tried to download the app again and still the same problem.
I have seen on the exposurenotification folder I just have DiagnosisKeyBatchOuterClass.java but not TemporaryExposureKeyExportOuterClass.java. Could it be the problem?

**Comment by MikeMcC399** [comment]
@pepintos 

How did you get the app source on your system? Did you:
- Download and extract a zip file?
- Clone the repository https://github.com/corona-warn-app/cwa-app-android with git or GitHub Desktop and then checkout a branch?

Could you confirm which branch you are working with? Your error message includes the folder name "cwa-app-android-2.0.0-RC4" however "2.0.0 RC4" is an old tag. The release/2.0.x branch is currently tagged with "v2.0.1-RC1".

You said you are using the latest Android Studio version. Can you confirm that you mean version 4.1.3 (and not for instance 4.2 RC 1)?

I assume that you have the `Android 10.0 (Q)` SDK including `Android SDK Platform 29` installed otherwise you would be getting another error. Check that in any case though.

I can find the file `TemporaryExposureKeyExportOuterClass.java` which is missing on your system in the "Path from Repository Root"
`Server-Protocol-Buffer/build/generated/source/proto/main/javalite/de/rki/coronawarnapp/server/protocols/external/exposurenotification`
for branch release/2.0.x on my system. It includes the text:
```
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: external/exposurenotification/temporary_exposure_key_export.proto

```

If you invoke `Android Studio > Build > Clean Project` you should find that the folder
`Server-Protocol-Buffer/build`
is completely deleted.

Invoking `Android Studio > Build > Rebuild Project` should completely rebuild the project including re-creating the file which you are missing. There should be a line in your Build log which says:
`> Task :Server-Protocol-Buffer:generateProto`

Perhaps you can find out yourself what is going wrong on your system? If you cannot work it out, you could post your Build log as an attachment here to see if there are any other clues in the log.

If you need to freshen up any skills about Android Studio there is a free online  (Java-based) course [Android Developer Fundamentals](https://developer.android.com/courses/fundamentals-training/overview-v2).

Good luck!

**Comment by heinezen** [comment]
Hey @pepintos ,

Did the solution from @MikeMcC399 work for you? If so, we can close this issue.

----
Corona-Warn-App Open Source Team
