### ISSUE TITLE
Device (running on Android 8.0.0) requires restart every 24 hours for correct Bluetooth service since app was installed

### ISSUE THREAD

**Issue by lastRoach** [corona-warn-app/cwa-app-android#3043]
## Technical details

- Device name: CAT S41
- Android version: Android 8
- App version: 2.0

## Describe the issue

As title states, since I installed the app my phone (CAT S41) running on Android 8.0.0 has Bluetooth connectivity issues. None of my devices (car, headphones,...) recognize my phone after more than 24 hours after the latest restart of the phone.

This is not only annoying as I'm not used to constantly restart my phone (that's but a habit and it's slowly changing), but it also raises a concern that my phone's Bluetooth might not be working correctly after 24 hours resulting in flawed interactions with other devices using the app.

Could not find anything by googling or here in the issues, so I figured it might be worth opening an issue.
If that's just my phone: tough luck.
But if it's a greater issue it might be worth looking into.

**Comment by MikeMcC399** [comment]
@lastRoach 
There is an FAQ article https://www.coronawarn.app/en/faq/#various_device_problems about this, but it probably will not help you very much, except for the general advice to contact your device vendor.

I don't think it is a general issue, otherwise there would have been many reports here about it.

There were some issues previously reported on CAT S41 devices where they crashed. The issues didn't really get investigated in detail though. You can find them if you search for closed issues.

**Comment by heinezen** [comment]
Hey @lastRoach ,

As pointed out in the FAQ entry and @MikeMcC399 's explanation, the issue is likely a problem with vendor-specific settings for the OS on the device. Unfortunately, if that's the case, the CWA team probably cannot do much about this. I will nevertheless check if there are similar reports in the app stores and if we have a workaround available.

----
Corona-Warn-App Open Source Team
