### ISSUE TITLE
Privacy policy not displayed correctly on old devices

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#3166]
## Technical details

- Android version: API 23 / Android 6
- App version: 2.2.x

## Describe the bug

The ordered list is not parsed correctly by the platform HTML parser on old Android versions.

Result on API 23 | Result on API 28
---|---
![Screenshot_1620857867](https://user-images.githubusercontent.com/16943720/118051419-4681d900-b381-11eb-9bd8-b872f32b1312.png) | ![Screenshot_1620857853](https://user-images.githubusercontent.com/16943720/118051421-471a6f80-b381-11eb-97f2-1bfa158db199.png)

## Steps to reproduce the issue

View privacy policy on affected platform versions.

## Expected behaviour

Display text correctly. Possibly also show numbers in front of the *ordered* list?

## Possible fixes

* Remove ordered list
* Use custom tag handler such as this one: https://bitbucket.org/Kuitsi/android-textview-html-list/src/master/app/src/main/java/fi/iki/kuitsi/listtest/MyTagHandler.java

## Additional context

Regression in 2.2.x due to a change in the privacy policy that added an ordered list instead of `p` tags.

----
Internal Tracking-ID: [EXPOSUREAPP-7268](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7268)

**Comment by heinezen** [comment]
@fynngodau 

Thank you. The issue has been reported to the devs (EXPOSUREAPP-7268).

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Is this supposed to have been fixed in the release/2.3.x branch or is it still a work-in-progress? The changes which have been made so far in the release/2.3.x branch don't solve the issue well and have not returned the display of the privacy policy to the clean status it had in the 2.1 release.

Using release/2.3.x to view the English language privacy policy:
- on API 23 there are no line breaks between each entry in the table of contents list
- on API 30 there is an extra bullet before the number of each entry in the table of contents list

Perhaps it is time to revert to 2.1.x formatting?

---
release/2.3.x on API 23

![image](https://user-images.githubusercontent.com/66998419/119685541-be520800-be45-11eb-9db0-6b59a7235c3a.png)

---
release/2.3.x on API 30

![image](https://user-images.githubusercontent.com/66998419/119686704-e55d0980-be46-11eb-874f-e4037e6e2f0e.png)

---
released version 2.1.2 on API 23

![image](https://user-images.githubusercontent.com/66998419/119688046-f35f5a00-be47-11eb-8ba7-5ae1ee8f6c4e.png)

**Comment by heinezen** [comment]
@MikeMcC399 It's still work in progress. We don't know if it will be fixed in 2.3 yet.


----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
- See PR #5498

**Comment by MikeMcC399** [comment]
This should be fixed when 2.27 is released. In the current 2.27.0-RC3 version it looks like this:

| Result on API 23<br>Android 6.0 | Result on API 28<br>Android 9.0 |
| ------------------------------- | ------------------------------- |
|   ![Data Privacy API 23](https://user-images.githubusercontent.com/66998419/190662710-e2a3cada-4386-4c18-8630-b50c24d89714.png)  |     ![Data Privacy API 28](https://user-images.githubusercontent.com/66998419/190663102-dc428753-ea58-463e-a208-b380a0b8f791.jpg)          |
