### ISSUE TITLE
Understanding "Priorisierte Hintergrundaktivität"

### ISSUE THREAD

**Issue by Lutzion** [corona-warn-app/cwa-app-android#3181]
Do i have some misunderstanding concerning "Priorisierte Hintergrundaktivität"?
When i click "Priorisierte Hintergrundaktivität" it leads me to "Akkuverbrauch optimieren" / energy optimization.

Since i have the "pimped" version 
https://f-droid.org/de/packages/de.corona.tracing/
i am able to see some statistics of the collected ids.
![collected_ids](https://user-images.githubusercontent.com/46639828/118353044-f19eb800-b564-11eb-9504-421e13218b9e.png)

When there is no  "Priorisierte Hintergrundaktivität" then no ids are collected.
My first understanding was, that the "Priorisierte Hintergrundaktivität" is only neccessary for checking the ids on a regular basis.
Thats why i did not activate "Priorisierte Hintergrundaktivität", as i thought it would be ok to update the risk status manually.
But if there are no ids collected, it would not make any sense.

So, is the description misleading?
Is "Priorisierte Hintergrundaktivität" needed to collect the ids or just to do the regular checking of ids?

**Comment by fynngodau** [comment]
Hi @Lutzion,

CCTG is not able to stay alive in the background without "Prioritized Background Activity" / with Battery Optimizations enabled. For this reason, you will neither be able to collect IDs nor will you be able to compare those IDs to reported-positive cases.

For this reason, we added a warning card to the main screen to be displayed whenever battery optimizations are enabled (https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/112).

For Corona-Warn-App, the situation is different because it delegates the former task to Google Play services, which stays alive in the background anyhow.

We changed the strings in the popup on initial launch, but not the description in the settings, which indeed makes this slightly misleading.

In the future, please post issues that concern CCTG directly to our own issue tracker at https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues.

**Comment by dsarkar** [comment]
@Lutzion Thanks in any case for contributing. And @fynngodau for answering! Enjoy the weekend. Best, DS

---
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
@Lutzion I've opened a corresponding CCTG issue: https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues/132

If this addresses your confusion, this issue here in the Corona-Warn-App issue tracker can be closed.

**Comment by Lutzion** [comment]
Wow, thank you very much for the fast and perfect answer.
