### ISSUE TITLE
Reduce scariness of incompatibility warning

### ISSUE THREAD

**Issue by fynngodau** [corona-warn-app/cwa-app-android#3260]
In https://github.com/corona-warn-app/cwa-website/issues/1288, we also discussed that the current incompatibility warning card looks scary and may suggest to users that the app is not functional at all.

Therefore, we discussed these ways of reducing the scariness of the message:

* Remove warning triangle and replace it with an info "(i)"
* Change title from "Incompatibility warning" to something that sounds less critical

We haven't found a really great term (that must work both in German as well as in English) to implement the latter option yet. Suggestions are welcome.

----
Internal Tracking-ID: [EXPOSUREAPP-7592](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7592)

**Comment by dsarkar** [comment]
- On the "stronger" side
  - Alert
  - Warining
  - Error
- On the "softer" side 
  - Notification
  - Message
  - Reminder (probably not in this case, since most users were not aware of this issue)
  - Important notice: Incompatibility between CWA and device (or similar)

**Comment by MikeMcC399** [comment]
@fynngodau 

I'm wondering if the tile needs to be displayed at the top level. This hits users in the face with it.

It's a permanent condition caused by the mobile device's hardware / firmware capabilities, so once a user has been informed, it shouldn't be necessary to keep reminding them.

Maybe the check could be triggered only at installation / update time and the user could be given a choice if the message is no longer shown after first being displayed. In that case, maybe the Settings menu could include an option to trigger / retrigger the test.

Perhaps a small indication such as a "!" icon with a neutral text like "Hardware" could be made part of the risk tile and the detailed risk information shown by tapping the risk tile could include information about compatibility issues.

Did anybody suggest to Google that they incorporate the test into the Exposure Notifications System? That would benefit all COVID-19 apps and offload the work from CWA. (CCTG would still need it though.)

**Comment by codejus** [comment]
I would choose a softer tone regarding the term, that does also indicate that it isn't something you shouldn't ignore on the same time. 

So from my view these two possibilites @dsarkar noted would be good:
> Important notice: Incompatibility between CWA and device (or similar)
> Attention: Incompatibility between CWA and device (or similar)

I think there souldn't be a possibility to dismiss the warning, as this would probably lead to the usual "dissmiss without reading"  behavior of the users and so makes the warning kinda useless probably.

Additional the warning maybe isn't needed in this big form after the user was able to notice it for the first (2nd) time. So maybe a banner at the top wich states somethin like "limited mode" would be an idea, too. Or a integration at te hop of the risk card as @MikeMcC399 proposes.

**Comment by fynngodau** [comment]
I think the message sound rather "informational" and not like a "warning" in the future. After all, in most cases, the user can't do anything to fix the problem.

> a "!" icon with a neutral text like "Hardware"

"Hardware" is technically not or not always accurate. If the device supports BLE but not peripheral mode, then, with my limited knowledge about this, I would conclude that the hardware is present, but the driver is lacking the feature.

> Did anybody suggest to Google that they incorporate the test into the Exposure Notifications System? That would benefit all COVID-19 apps and offload the work from CWA. (CCTG would still need it though.)

Yes, in fact we have been wondering why Google doesn't have it, and why CWA didn't have it since the beginning. microG contains such a message in its setting menu. For CCTG, we added an additional warning (which is now the one we upstreamed to CWA) because the microG one was not visible enough.

**Comment by Jo-Achim** [comment]
> > a "!" icon with a neutral text like "Hardware"
> 
> "Hardware" is technically not or not always accurate. If the device supports BLE but not peripheral mode, then, with my limited knowledge about this, I would conclude that the hardware is present, but the driver is lacking the feature.

How about "device"? ("Gerät")?

**Comment by mtwalli** [comment]
No planned
