### ISSUE TITLE
[BSI][20200610] FAQ Section linking to Dummy/Placeholder Content

### ISSUE THREAD

**Issue by BSI-TF-CWA** [corona-warn-app/cwa-app-android#341]
Rating: Low
 
Description:

The (current-state) release version of the Android app is linking to dummy/placeholder content on bundesregierung.de in its FAQ section. This has no impact on the security of the app. 

Proof of Concept:

![android_faq-link-to-dummy-page-1](https://user-images.githubusercontent.com/65443025/84258467-4648e000-ab17-11ea-9185-27ad49ec7a76.png)
![android_faq-link-to-dummy-page-2](https://user-images.githubusercontent.com/65443025/84258470-46e17680-ab17-11ea-93e2-ef76e1b523be.png)
![android_faq-link-to-dummy-page-3](https://user-images.githubusercontent.com/65443025/84258473-46e17680-ab17-11ea-9f3c-cf9535aa5629.png)

https://www.bundesregierung.de/breg-de/themen/coronavirus/test-toggle-1754746

**Comment by harambasicluka** [comment]
Hi,

as you can see here we are using a string resource which contains the url for this card:

https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/ui/main/MainFragment.kt#L135

And this string resource contains `https://www.bundesregierung.de/corona-warn-app-faq`.

https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values/strings.xml#L254

The redirection is happening on the `bundesregierung.de` level and looks intentional (if you use a wrong url you get to see a 404 page).

Is that information enough for you? If yes, please close this issue, if not we can discuss it further.

Thanks,
Luka

**Comment by harambasicluka** [comment]
As this is open since two days I'll close it.
