### ISSUE TITLE
Allow to Store Vaccination Cert in Google Pay (Google equivalent of apple wallet)


### ISSUE THREAD

**Issue by 5V715** [corona-warn-app/cwa-app-android#3486]
## Feature description

As iOS will get the wallet feature I think I would be nice Todo the same for Android users. This should be possible thru the https://developers.google.com/pay/passes

Pass API in Google pay

## Problem and motivation
Quick access to the Vaccination Cert

## Is this something you're interested in working on

Solid Maybe

----
Internal Tracking-ID: [EXPOSUREAPP-7975](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7975)

**Comment by heinezen** [comment]
@5V715 Thank you for the request.

I've forwarded the feature request to the developers (ticket ID: [EXPOSUREAPP-7975](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-7975)). We will now investigate how this feature could be implemented and report back here on Github if we get any news.

----
Corona-Warn-App Open Source Team

**Comment by heinezen** [comment]
Hello everyone,

This feature request has been **declined** and will not be pursued further. We have decided against this feature because of the legal restrictions and drawbacks regarding the privacy of the stored data.

----
Corona-Warn-App Open Source Team

**Comment by DRSchlaubi** [comment]
> Hello everyone,
> 
> This feature request has been **declined** and will not be pursued further. We have decided against this feature because of the legal restrictions and drawbacks regarding the privacy of the stored data.
> 
> Corona-Warn-App Open Source Team

Could you elaborate a bit more on what the legal restrictions and privacy concerns were?

According to the APIs documentation, the Data is stored locally on the device?

What legal ristrictions are there ristricting this but seemingly not corona-warn-app/cwa-app-ios#2965

**Comment by heinezen** [comment]
@DRSchlaubi https://github.com/corona-warn-app/cwa-app-ios/issues/2965 was reopened by accident. The feature was rejected on both Android and iOS for the same reasons.

**Comment by DRSchlaubi** [comment]
## Feature description
As previously requested in Digitaler-Impfnachweis/certification-apis#37, corona-warn-app/cwa-app-ios#2965 and corona-warn-app/cwa-app-android#3486. The original issue on this has been closed due to privacy concerns, that were unfortunately discussed internally, so I can't know if all of them still exists. However since the original issue on this has been closed, Google has released [a new pass type](https://developers.googleblog.com/2021/06/google-updates-passes-api-to-save-covid-testing-and-vaccination-information-on-Android-devices.html) in the passes API specifically, which might solves some concerns? In other open discussions about this, people have been concerned about being able to see the phones Covid certificates even if it's locked, which won't be an issue, since this certificates require a display lock to be set and the phone to be unlocked.

### Documentation links
- https://developers.googleblog.com/2021/06/google-updates-passes-api-to-save-covid-testing-and-vaccination-information-on-Android-devices.html
- https://developers.google.com/pay/passes/guides/pass-verticals/use-cases?vertical=covid-cards
- https://payments.developers.google.com/terms/aup#covid-cards
- https://developers.google.com/android/reference/com/google/android/gms/pay/package-summary

## Problem and motivation
It can come in quite handy to have all of your cards and passes in one place, also having an official way to do this can make use of the new Pass type which is only available to authorities which can actually create vaccination certificates

## Is this something you're interested in working on

Maybe. I am not sure how much I could do as the documentation on Covid certificate is locked behind a registration form only authorities have access to, I would be able to work on the Integration in the App itself since this Documentation is public

**Comment by heinezen** [comment]
@DRSchlaubi I've asked the dev team to reevaluate the issue based on the information you provided. We'll have to see what RKI and BSI have to say about this new development.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
https://support.google.com/pay/answer/10890261 says
>**Add your COVID card to your Android device**
>
>On your Android device, you can store a digital copy of your COVID vaccination and test information as a COVID card.
>
>Your COVID card will only be stored on the device that you save it on. You can manually save it on more than one device.
>You don't need the Google Pay app to use this feature.
>This feature is currently available for government and healthcare providers or authorised third parties in the US.
>This feature is available in the US.

Is there any indication that this feature is planned to be made available in countries of the European Union?

**Comment by DRSchlaubi** [comment]
> https://support.google.com/pay/answer/10890261 says
> 
> > **Add your COVID card to your Android device**
> > On your Android device, you can store a digital copy of your COVID vaccination and test information as a COVID card.
> > Your COVID card will only be stored on the device that you save it on. You can manually save it on more than one device.
> > You don't need the Google Pay app to use this feature.
> > This feature is currently available for government and healthcare providers or authorised third parties in the US.
> > This feature is available in the US.
> 
> Is there any indication that this feature is planned to be made available in countries of the European Union?

As there is no clear documentation about this, I contact the Google Pay Developer support about this. I will update this comment as soon as I have an answer

**Comment by DRSchlaubi** [comment]
> Covid passes are not yet available in every region. If you are interested in issuing vaccine cards in Germany fill out the form [here](http://support.google.com/pay/merchants/contact/instore_merchants), and we will collect your information and add you to our pipeline, and we will get back to you once these passes are available in your region.

**Comment by DRSchlaubi** [comment]
Any updates on this?

**Comment by heinezen** [comment]
@DRSchlaubi No, nothing new here, sorry.

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
Also discussed in https://github.com/Digitaler-Impfnachweis/covpass-android/issues/52.

**Comment by DRSchlaubi** [comment]
Still no updated after months?
