### ISSUE TITLE
Validity of Certificate uses inconsistent date formats

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#3830]
## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- App version: ~~2.6.1-RC1~~ 2.9.0

## Describe the bug

Formatting of dates in the Certificate Validation function is inconsistent.

In the example below date / times are displayed in two different formats:
- 28.07.2021 4:26 PM
- 7/28/21 4:26 PM

with different separators (. and /), reversed day and month, and short and long forms of the year.

## Steps to reproduce the issue

1. Settings > General management > Language and Input > Language and set default language to English (United States)
2. Open CWA 
3. Tap "Certificates", tap "CONTINUE"
4. Tap "+ CERTIFICATE" and scan an EU Digital COVID Certificate
5. Tap "CHECK VALIDITY"
6. Accept default Country (Germany) and default Date and time
7. Tap "CHECK"

Compare date formats on input screen and result screen.

![Validity of Certificate 1](https://user-images.githubusercontent.com/66998419/127342180-c752d2b8-fe21-4d41-b4f9-333e381d651f.jpg)

![Validity of Certificate 2](https://user-images.githubusercontent.com/66998419/127342203-06acc5c5-250f-4f3b-a808-3e9699d83a4b.jpg)

## Expected behavior

Dates in the Certificate Validation function should be displayed in a consistent way.

## Possible Fix

Use the locale's date formatting to achieve consistency.

----
Internal Tracking-ID: [EXPOSUREAPP-8750](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8750)

**Comment by heinezen** [comment]
@MikeMcC399 

Thanks for checkin on this. I've made an internal report to the dev team.

----
Corona-Warn-App Open Source Team

**Comment by fynngodau** [comment]
#### Information on the cause of the error

Here the string is formatted:

https://github.com/corona-warn-app/cwa-app-android/blob/a9bc344cef8e4e9d10279a46c88c9c6a70a7af97/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/ui/validationresult/common/ValidationResultItemCreator.kt#L115-L117

The `DateTime.toShortDateTimeFormat` extension function is defined as:

https://github.com/corona-warn-app/cwa-app-android/blob/a9bc344cef8e4e9d10279a46c88c9c6a70a7af97/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/util/TimeAndDateExtensions.kt#L142-L145

However, it does not always return a string in the format that it is annotated as, because `DateTimeFormat.shortDateTime()` is documented as:

> Creates a format that outputs a short datetime format.
>The format will change as you change the locale of the formatter. […]

Whereas the extension function `DateTime.toShortDayFormat()` uses a `"dd.MM.yy"` as a fixed pattern.

**Comment by dsarkar** [comment]
@fynngodau Thanks. I will forward this to the internal ticket.

**Comment by MikeMcC399** [comment]
PR https://github.com/corona-warn-app/cwa-app-android/pull/3987 is merged into [release/2.10.x](https://github.com/corona-warn-app/cwa-app-android/tree/release/2.10.x)

This issue (https://github.com/corona-warn-app/cwa-app-android/issues/3830 Internal Tracking-ID: [EXPOSUREAPP-8750](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8750)) is solved by PR #3957 so this issue (#3830) can be given the Fix 2.10 label.

**Comment by MikeMcC399** [comment]
@dsarkar 
Would you please add the fix 2.10 label to this issue?

**Comment by MikeMcC399** [comment]
@dsarkar 
This issue is fixed in the CWA 2.10.1 Android version which was released today.
You may like to add the Fix 2.10 label.

Closing as fixed.

**Comment by dsarkar** [comment]
@MikeMcC399 Thanks! Forwarded to internal ticket.
