### ISSUE TITLE
Validity of Certificates: Error text about wrong date/time cut off

### ISSUE THREAD

**Issue by chk1** [corona-warn-app/cwa-app-android#3892]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Xiaomi Redmi 4X
- Android version: 9 (LineageOS 16.0)
- App version: 2.6.1

## Describe the bug

The message about choosing the appropiate date and time in the "Validity of Certificate" window can appear truncated.

>Die angegebene Uhrzeit liegt in der Vergangenheit. Ihre lokale Einreisezeit muss in [cut]

This might only affect the German locale, I can't reproduce it in English on my phone.

## Steps to reproduce the issue

Prerequisites:

- Phone set to German locale 
- Vaccination certificate in CWA

Steps to reproduce:

1. Open Certificates tab
2. Tap on your certificate
3. Tap "Check Validity"
4. Enter a date or time in the past
5. Observe error message below the date and time input

<img alt="" width="300" src="https://user-images.githubusercontent.com/828496/128663315-64c25338-fa04-4c73-b6f5-490cdf043508.png">

## Expected behaviour

Text should not appear truncated

## Possible Fix

Possibly minor adjustments in the layout

## Additional context

---
Internal ID EXPOSUREAPP-8787

**Comment by MikeMcC399** [comment]
@chk1 
Thanks for taking the trouble to report this issue!

It has already been fixed in PR https://github.com/corona-warn-app/cwa-app-android/pull/3864 for the upcoming CWA 2.7 version. 

> Internal ID [EXPOSUREAPP-8787](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-8787).
> 
> TextView was set to a fixed height of `31dp`, so that error messages longer than 2 lines were not displayed correctly. Fixed it by setting the TextView height to `wrap_content`.

The issue not only affects the error message. Also even the prompt to enter the date and time is truncated, if the display is small and / or the font size is set to large.

The same applies to the English locale: if the display is small and / or the font size is set to large, the prompt and error message may be truncated.

**Comment by marcauberer** [comment]
Is fixed in the lastest release.
