### ISSUE TITLE
Date and time when checking certificate status must be entered in UTC and not in local timezone.

### ISSUE THREAD

**Issue by wertzui** [corona-warn-app/cwa-app-android#3990]
## Avoid duplicates

* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

Might be related to https://github.com/corona-warn-app/cwa-app-android/issues/3562

## Technical details

- Device name: Huawei P30
- Android version: 10
- App version: 2.7.1

## Describe the bug

When checking a certificate, you have to put in a date and a time into the "Datum und Uhrzeit" input box. Under the box it states: "Geben Sie Ihr Einreisedatum und Ihre lokale Uhrzeit ein."
However this must be entered in UTC and not in local time (currently Germany ix +2:00).

## Steps to reproduce the issue

Vaccinated at 2021-08-01 (time does not matter)
Entered 2021-08-16 00:01 => says certificate is invalid
Entered 2021-08-16 02:01 => say certificate is valid

## Expected behaviour

The input should be in the users local timezone as stated below the input.

**Comment by KinNeko-De** [comment]
I do not use the corona warn app. But this issue was mentioned in Digitaler-Impfnachweis/covpass-android#106

Using only UTC timestamp is a common practice to avoid time problems with local time and summer/wintertime.
Using "german time" makes everything more complex.
And if you deal with internal people, you always get problems.

Assume the following scenario.
You (from germany) fly to the west and somebody from another timezone checks it.
You can not explain to him that your phone is german and your certificate is valid in your timezone.
I would not like that anything is based on german time.

So for me (as a developer) it is okay that the certificate is valid only at 02:00 (or now 01:00)

**Comment by mtwalli** [comment]
@wertzui  UTC is actually used under the hood see 
https://github.com/corona-warn-app/cwa-app-android/blob/d84d7b537ba92c7577a23f903c882b85e58cd1a9/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/validation/core/business/wrapper/Mappings.kt#L30-L43

and see https://github.com/eu-digital-green-certificates/dgc-certlogic-android/issues/53#issuecomment-905382384  changes have been included in CWA long time ago. are you still facing this issue?
