### ISSUE TITLE
Remove or at least hide date of birth

### ISSUE THREAD

**Issue by dirkriehle** [corona-warn-app/cwa-app-android#4020]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
When selecting a certificate to show and validate, my birth date is also shown. 

## Suggested Enhancement
Please remove date of birth from view, or, if necessary for other reasons, hide it in such a way that anyone checking your certificate will not see it in plain view.

## Expected Benefits
Date of birth is a security relevant information that should not be made available to other people easily.

**Comment by Ein-Tim** [comment]
Just FYI: If somebody uses the [CovPassCheck-App](https://digitaler-impfnachweis-app.de/en/covpasscheck-app) to check your certificates and check the data shown their against your ID (this is how a verification of vaccination, recovery or test should be done) the date of birth is also shown.

**Comment by MikeMcC399** [comment]
@dirkriehle 

The certificate which is chosen by the app as "Currently used certificate" is already shown in the top-level view without a date of birth.

The following screenshot is from https://www.coronawarn.app/en/screenshots/
https://www.coronawarn.app/assets/screenshots/2-8/en/android/PersonOverviewFragment_one_person.png

<img src="https://www.coronawarn.app/assets/screenshots/2-8/en/android/PersonOverviewFragment_one_person.png"
     alt="Certificate" />

As @Ein-Tim already wrote, the way that a certificate is intended to be verified is for it to be scanned with [CovPassCheck-App](https://digitaler-impfnachweis-app.de/en/covpasscheck-app) from an independent second mobile device and then the name and date of birth is to be compared to the name and date of birth on an official identification document, such as a passport or a personal ID (Personalausweis). 

You can read more about this on https://digitaler-impfnachweis-app.de/en/covpasscheck-app/.

**Comment by dsarkar** [comment]
@dirkriehle Thank you for contributing here. @MikeMcC399 and @Ein-Tim have already point out the two main important points here:
- The screen with the certificate to be verified is preserving your privacy ("Datensparsamkeit")
- For the verification of a certificate the certificate should be scanned by a official verifier app (in German CovPassApp) and name and date of birth should be compared with an ID. 

Hope that clarifies the situation. 
Best wishes, DS 

---
Corona-Warn-App Open Source Team

**Comment by Jo-Achim** [comment]
If I understand the topic correctly ...
I think @MikeMcC399 hint is the most important thing first. The standard certificates are displayed by the CWA without the date of birth (see screenshot).
It may look different when displaying non-standard certificates. Here the date of birth is shown at least in the lower scroll area and is thus possibly visible.

However, the correct fact that the name and date of birth can be compared with an identification document does not conflict with hiding the date of birth (in the display of the CWA).
Because CovPassCheck only reads the displayed QR code, checks it and then displays its relevant content with name, standardized name and date of birth. This means that the data read from the QR code by CovPassCheck and displayed in CovPassCheck only can always be compared with an identification document.

> Date of birth is a security relevant information that should not be made available to other people easily.

I'm not sure I want to share this opinion. However, I will not necessarily disagree either. 

Best regards, Joachim.

**Comment by friedalex** [comment]
Thanks for the clarification. If people only ever see the front page and don't have to click on the certificate to use the app's validation feature, then at least on Android they won't see the DoB. That works for me. That my DoB is easily visible on both my id card and driver's license is annoying but unrelated.

**Comment by dirkriehle** [comment]
(Sorry, wrong account at first try.) Thanks for the clarification. If people only ever see the front page and don't have to click on the certificate to use the app's validation feature, then at least on Android they won't see the DoB. That works for me. That my DoB is easily visible on both my id card and driver's license is annoying but unrelated.
