### ISSUE TITLE
Stricter TLS settings for CDN

### ISSUE THREAD

**Issue by IndianaDschones** [corona-warn-app/cwa-app-android#404]
## Current Implementation

On the client side `TLS 1.0` and `TLS 1.1` are enabled for the CDN. As stated in #402 these protocols are vulnerable.

@secjoe i decoupled your additional findings into this seperate issue

https://github.com/corona-warn-app/cwa-app-android/blob/970e8b859cff3c8beeca83ac83e9ed534927107a/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/ServiceFactory.kt#L102-L109

A scan on [Qualys SSL Labs](https://www.ssllabs.com/ssltest/analyze.html) reveales, that the server only supports `TLS 1.2` and a hand full of good chipher suites, see screenshot. So actually, **there is no need** on the client side to offer/accept `TLS 1.0` and `TLS 1.1`

![cwa-cdn-ciphers](https://user-images.githubusercontent.com/6652142/84441317-e009ad80-ac3b-11ea-89c4-c0af9142ae33.png)

## Suggested Enhancement

Stick to the settings used for Submission and Verification, because the offered ciphers and protocols from the CDN are contained in the stricter settings. 

## Expected Benefits

Security and only use what you need. The server does not offer these settings, so the client doesn´t need to support them.

---
Internal Tracking ID: EXPOSUREAPP-1033

**Comment by rugk** [comment]
Also: It would be actually good if the server could support TLS 1.3. Even TLS 1.3 is a few years old already.

And [BSI confirms this suggestion here](https://www.bsi.bund.de/SharedDocs/Downloads/DE/BSI/Publikationen/TechnischeRichtlinien/TR02102/BSI-TR-02102-2.html) by reco0mmending TLS 1.2 and TLS 1.3 with forward secrecy ciphers.

**Comment by GPclips** [comment]
This issue has been completed and will be closed now.

**Comment by SecJoe** [comment]
Hey, 

@GPclips and @jakobmoellersap 

it seems that the commit/branch has been deleted: https://github.com/corona-warn-app/cwa-app-android/pull/379 . I hope the change is not lost. So its not transparent, where/in which release/commit the change will be applied later on. With the git search function i have found [here](https://github.com/corona-warn-app/cwa-app-android/blob/release/1.6.x/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpModule.kt) a new TLS-Spec specific file in the 1.6x release: .I think this is the change you focused on, while you have closed this issue, right? If i am right, please read everything below:

[Here](https://github.com/corona-warn-app/cwa-app-android/blob/10a78bdff2e19176d03b66e8a5a995fd7096c6ff/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpModule.kt#L63) you specify custom TLS Cipher and Versions but above there is the ciphers as ConnectionSpec.RESTRICTED_TLS. With this keyword you allowed that ciphers are a mixture of this custom ciphers and the OkHttp restricted ciphers. The OkHttp restricted ciphers are referenced [here](https://github.com/square/okhttp/blob/86fc1ae3f4e008abd6384872649e87860bea55a7/okhttp/src/main/kotlin/okhttp3/ConnectionSpec.kt#L274) and linked to the variable in [this place](https://github.com/square/okhttp/blob/86fc1ae3f4e008abd6384872649e87860bea55a7/okhttp/src/main/kotlin/okhttp3/ConnectionSpec.kt#L316). 

The problem is: OkHttp allows for example: chacha (CipherSuite.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256). We do not allow chacha because the BSI does not allow it. But chacha will work nevertheless, because we are mixing the OkHttp requirements with our requirements in [this line](https://github.com/corona-warn-app/cwa-app-android/blob/10a78bdff2e19176d03b66e8a5a995fd7096c6ff/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/http/HttpModule.kt#L64).

I think we should only specify our custom rules and not mix it with others...
