### ISSUE TITLE
Risk tile timestamp ignores system setting "Use 24-hour format"

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-app-android#4236]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Samsung Galaxy A5 (2017) SM-A520F
- Android version: 8.0.0
- First reported on App version: 2.11.2
- Reproducible still on App version: 2.25.0

## Describe the bug

The risk tile timestamp for last updated presents the time always in 24 hour format if the locale is set to:
- English (United Kingdom)
- Use 24-hour format: disable

which goes against the device's selected time-format setting.

## Steps to reproduce the issue

Device settings:
1. Settings > General Management > Language and input > Language, select English (United Kingdom)
2. Settings > General Management > Date and time > Use 24-hour format: disable

CWA
1. Open CWA with EXPOSURE LOGGING ACTIVE
2. WiFi is enabled and the time is past midday
3. Note that risk tile shows "Updated: Today, hh:mm" wrongly using the 24-hour clock format
4. Settings > General Management > Language and input > Language, select English (United States)
5. Note that risk tile is now showing "Updated: Today, hh:mm AM/PM" correctly using the 12-hour clock format

Screenshot for step 3 (incorrect time format)

![Risk tile wrong time format](https://user-images.githubusercontent.com/66998419/137538622-285b5a35-a20c-40b1-926e-d04d4da7b1c8.jpg)

## Expected behavior

If the system is set to use 12-hour time format, then the risk tile should also use this format.

## Additional context

- The problem is also reproducible on Android 11.

- If the locale is set to English (United States) and Android settings have "Use 24-hour format" enabled, then the time-stamp in the risk tile ignores the system setting and displays the time in 12-hour AM / PM format.

---
Internal Tracking ID: [EXPOSUREAPP-10177](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-10177)

**Comment by MikeMcC399** [comment]
I noticed that in fact CWA simply ignores the Android system setting "Use 24-hour format". The time format used for the time-stamp in the risk tile depends on which locale is selected in the Android system settings.

- English (United States) results in 12-hour format
- English (United Kingdom) results in 24-hour format
- Deutsch (Deutschland) results in 24-hour format

**Comment by svengabr** [comment]
I have added the new information to the Jira ticket and asked for an update on this.

**Comment by mtwalli** [comment]
@MikeMcC399  Here is a feedback from @schauersbergern 
>we currently use android utility functions to display this text, and android removed the functionality to switch between 12 and 24 hour representation in german locale completely and I think I know why.
German Representation is "Aktualisiert: Heute, 14:00 Uhr" and when you would have the option to switch to 12hour representation it would look like
"Aktualisiert: Heute, 2:00 PM" which is not right because generally the time will not be displayed like that for german locale.
We now could build our own functionality which prints out
 "Aktualisiert: Heute, 2:00 Uhr" which would also be not right, because when its 16:00, how would you know if the status was updated at 2:00 at night or 14:00. 
 "Aktualisiert: Heute, 2:00 PM Uhr" is completely wrong.
Because of this dilemma this utility was removed and its now standardized on android not to switch between 12 and 24 hour representation manually, and I would suggest to close this ticket and not implement non standard time display.

For more information see https://developer.android.com/reference/android/text/format/DateUtils#getRelativeDateTimeString(android.content.Context,%20long,%20long,%20long,%20int)

**Comment by MikeMcC399** [comment]
Android and vendor-specific issue.
Closing.
