### ISSUE TITLE
Luca QR Code auch.scannen

### ISSUE THREAD

**Issue by didiw58** [corona-warn-app/cwa-app-android#4339]
Warum kann die CWA die QR-Codes von Luca und anderen nicht scannen?

**Comment by Ein-Tim** [comment]
@didiw58 

Luca QR-Codes sollen bald gescannt werden können, siehe: https://github.com/corona-warn-app/cwa-server/pull/1594#issuecomment-959378350

In diesem Issue findest du weitere Informationen dazu wie 3rd Party Apps Kompatibilität mit der CWA erreichen können: https://github.com/corona-warn-app/cwa-documentation/issues/590

**Comment by dsarkar** [comment]
@didiw58  FYI PR https://github.com/corona-warn-app/cwa-website/pull/2041

**Comment by dsarkar** [comment]
https://www.coronawarn.app/de/faq/#check_in_luca

**Comment by floscher** [comment]
Die CWA kann ab sofort luca-QR-Codes scannen.

Kleine Einschränkung: Wenn die Codes vor dem 26. Mai 2021 erstellt wurden, müssten die Locations ihre QR-Codes neu von der luca-Website herunterladen, damit das funktioniert.

**Comment by Jo-Achim** [comment]
The problem is often incomplete articles, for example in print media. Please refer: [luca-qr-code rejected](https://github.com/corona-warn-app/cwa-documentation/issues/743#issuecomment-966180008) and the proposed changes to the text in https://github.com/corona-warn-app/cwa-documentation/issues/743#issuecomment-966097744.

**Comment by Ein-Tim** [comment]
I suggest to close this issue now @dsarkar
