### ISSUE TITLE
Exposure framework request - rework wording 

### ISSUE THREAD

**Issue by tmechen** [corona-warn-app/cwa-app-android#4405]
## Avoid duplicates
* [x] This enhancement request has not already been raised before
* [x] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [x] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
When initially setting up the app, android shows this request, to make sure the user knows the implications of the exposure framework API (screenshot taken with the austria corona warn app "Stopp Corona" because for whatever reason one cannot take a screenshot of this request in the setup of the CWA. 

![image](https://user-images.githubusercontent.com/9123876/142292604-d4fbfe87-f846-44bf-b63b-7dad5ec62fb4.png)

## Suggested Enhancement
I am aware of the fact, that this is not a text generated by CWA, but Android - but there is no specific contact for this kind of request, and I hope you might have some contacts to them - therefore I opened this issue in here, because it impacts possible users for the CWA. Feel free to close or move.

**Problem**   
especially the last paragraph sounds fishy. I know what it is supposed to mean, but for people thinking the CWA would be able to generate tracking data for authorities, this sounds like a confirmation. Maybe this wording should be reworked, I do not have a specific proposal, but without knowledge of the exposure framework this just sounds fishy to people. 

## Expected Benefits
increased usage by people not knowing the concepts of the CWA

**Comment by MikeMcC399** [comment]
@tmechen 

The text "_Datum, Dauer und Signalstärke der möglichen Begegnungen ..._" comes from the Google Exposure Notification Service which is supplied by the Google Play services. 

A very similar sentence is also displayed through:

Settings > Google > COVID-19 Exposure Notifications (EN)
Einstellungen > Google > COVID-19-Benachrichtigungen (DE)

EN | DE
--- | ---
![Google Play services EN](https://user-images.githubusercontent.com/66998419/142424238-fc44e3ba-2fd5-4f6d-8a17-c6b97c8989ef.jpg) | ![Google Play services DE](https://user-images.githubusercontent.com/66998419/142424261-81b96489-c014-432a-8ddd-cf75d52b0d1a.jpg)

You can see it also in the [v1.8, January 2021 release notes](https://developers.google.com/android/exposure-notifications/release-notes#v18_january_2021) of Google API for Exposure Notifications.

Especially the statement in the Datenschutzerklärung of the Corona-Warn-App itself is important in this regard:

"Das gesamte System der App ist so programmiert, dass so wenig personenbezogene Daten wie möglich verarbeitet werden. Das bedeutet, dass das System bei der Risiko-Ermittlung, der Warnung anderer und dem Abruf des Testergebnisses keine Daten erfassen muss, die es dem RKI oder anderen Nutzern ermöglichen, auf Ihre Identität, Ihren Namen, Ihren Standort oder andere persönliche Details zu schließen."

The Corona-Warn-App privacy document is displayed when the app is first used (onboarding) and is available in the app through the App Information menu or online

[CWA Privacy notice - EN](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-en.pdf)
[CWA Datenschutzerklärung - DE](https://www.coronawarn.app/assets/documents/cwa-privacy-notice-de.pdf)

which explains in detail what data is processed, stored and transmitted.

Google does have an e-mail address for feedback exposure-notifications-feedback@google.com. I imagine that there are legal reasons to display this text and since the Google software is used worldwide it is unlikely for it to get changed unless it is considered wrong.

**Comment by mtwalli** [comment]
Please report this issue to Google, we can't change that
