### ISSUE TITLE
Entering birth date when adding a PCR-test could be more user friendly

### ISSUE THREAD

**Issue by trutzig89182** [corona-warn-app/cwa-app-android#4496]
## Current Implementation

When entering a PCR Test, I am asked to give my date of birth as a way to receive an official test certfificat (figure 1). For this I press on „Geburtsdatum/birth date“. The next screen presents a field for entering the birth date in the format. However the field is not automatically activated (figure 2). When tapping on the field the keyboard opens. I can enter the date including seperators (".") (figure 3). 

## Suggested Enhancement

The menue could be more userfriendly.
1. The state of figure 2 could be skipped so that the user can directly start to type in her birth date without tapping on the field again.
2. Usually it is not necessary to enter seperators like "." when entering a birth date. It would be more convenient to type 291181 and than automatically get 29.11.81 as result.

## Expected Benefits

Obviously the benefits are not enormous, but changing this could make entering a test a bit more convenient and make the experience with the app more pleasant. Given the amount of tests that are entered every day making this more user friendly could still be relevant. At least I stumbled over these extra steps that I had to do. 

### figure 1
![First screen after scanning the PCR-test QR code. Text (German) „Sie können über die App ein offizielles digitales COVID-Testzertifikat der EU anfordern, das anschließend in der App hinzugefügt wird.“ Under this text a field, „birth date“, a button „Testzertifikat anfordern/request test certificat“ and a button „no thank you“. ](https://user-images.githubusercontent.com/63927781/143883558-ddc39543-3fb6-47b0-8b71-3ace985c7945.png)

### figure 2
![CWA screen (German): „Ausgewähltes Datum“ with a Field named „Datum“ and showing the Format „TT.MM.JJ“. On the bottom button „cancel“ and button "ok". ](https://user-images.githubusercontent.com/63927781/143884119-7fd846d5-8360-48e5-854b-b7c77818bf81.png)

### figure 3
![CWA screen with active field "Datum". Keybord extended on the bottom. The field containsg "2312". Underneath the field the indication: „infalid format. Format TT.MM.JJ. Example: 29.11.21](https://user-images.githubusercontent.com/63927781/143884468-47aed65a-813a-4955-a348-1bf8b8224867.png)

**Comment by retonap** [comment]
I stumbled over this issue too after scanning the QR code but in my case it is less the way to enter the birth date but more to find the need for it as the text is in a light gray only - you know, if people are just coming back from the doctor, they have so many things in their head so they need a clear and simple advice step by step what to do without reading to much - otherwise they will give up quickly 

![Screenshot_20220727-123742_Corona-Warn](https://user-images.githubusercontent.com/110158922/181458168-06891437-98d8-4cda-ac8b-66f15689d70b.jpg)

My suggestion is to at least make the requirement to enter the date more obvious - make it an eye catcher like keep the field in red color until you click on it to enter your birthdate. Then change back to gray.

**Comment by mtwalli** [comment]
No planned
