### ISSUE TITLE
Risc detection without switching on Bluetooth and Localisation

### ISSUE THREAD

**Issue by madiko** [corona-warn-app/cwa-app-android#4524]
## Avoid duplicates
* [X] This enhancement request has not already been raised before (at least as far as I know. Found no open issue)
* [ ] Enhancement request is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)
* [ ] If you are proposing a new feature, please do so in [CWA-Wishlist](https://github.com/corona-warn-app/cwa-wishlist)

## Current Implementation
Currently when I want to check my "Risiko-Ermittlung" (risc detection?), I am forced to switch on Bluetooth as well as location sensing. Only then I am able to activate the matching of data. After that I have to do the same process vice versa: switching off the "risc detection". Only then I can switch off Bluetooth and location sensing. Which means I have to remember to do so every day. And to be frank: It's quite annoying.

Yes, I do not want them on all the time! They not only drain the battery. They are useless in my home office anyway. I only need to switch them on when en route, of course.

## Suggested Enhancement

* run the risc detection independently (as soon as a web connection is detected, preferably WLAN)
* send a note to the user with the result (wich would also serve as a kind reminder, e. g. to note ones contacts in the "contact-diary" or switching on the detection when leaving ones home)

## Expected Benefits

* saves battery
* less data recorded
* less devices that run services, that are not needed (all the time)

**Comment by vaubaehn** [comment]
Hi @madiko ,
if I got you right, you have disabled bluetooth/location all of the time, except when you want to run risk assessment from inside CWA? If this is the case, risk assessment does not make any sense unfortunately.
Google's Exposure Notification System receives beacons from other devices only, when Bluetooth (and because of the rights management also location) is turned on. The other way round, your device won't transmit any beacons to other devices, when bluetooth is turned off.
This means, the GMS internal database of received beacons is empty, and you can't get notified when there has been a risk contact. The other way round, no-one will bei warned in case you are infected and you anonymously share your status.

Google's ENS uses bluetooth low energy (BLE) which only needs very low power. More over, scanning for beacons and transmitting your own only takes place every 5 minutes for a couple of seconds (what is enough to detect a risk contact). There will be no remarkable battery drain.

**Comment by dimikw** [comment]
I'm in the same boat, I only want to actively run the app when I leave the house, not 24/7 because that is a waste of energy and makes no sense when I am home alone. On that note, the constant error notification that shows up all the time when Bluetooth/GPS is disabled is REALLY annoying. Yes, I KNOW that the app cannot work properly unless Bluetooth and GPS are activated, but when I sit at home all day **I. Don't. Care!** And the only way to block this notification is to block notifications from the app entirely, which completely defeats its purpose. We really need a "shut up, **I KNOW**" button for the Bluetooth/GPS requirement.

**Comment by Ein-Tim** [comment]
@dimikw 

The notifications you see come from the Google Play Service & not from CWA.

**Comment by madiko** [comment]
Tim @Ein-Tim, that's not entirely true: This Google Play Service notification is triggered by the app itself. So the solution must be fixed in CWA anyway.

**Comment by Ein-Tim** [comment]
@madiko So you mean CWA "tells" the Play Service to send this notification?

**Comment by madiko** [comment]
@Ein-Tim Yes, I am quite sure that this is one of the fundamental pre-sets in the app, like a basic requirement set in the root/boot or else of the application. I am no app developer, so unfortunately I can't tell it more excactly. But I very much hope, that an app developer understands and can find a solution.

**Comment by Ein-Tim** [comment]
@madiko 

@MikeMcC399 stated in https://github.com/corona-warn-app/cwa-wishlist/issues/35#issuecomment-740021048 the following:

> The notification you showed is provided by the Google Exposure Notifications System. It is not controlled by the Corona-Warn-App.

Maybe he could clarify this here?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

In the Google UI there is a switch
- "Use Exposure Notifications"

which is either on or off.

In Android CWA you may see:
- EXPOSURE LOGGING ACTIVE
- EXPOSURE LOGGING STOPPED

These two status are directly linked.

If exposure logging is stopped, then the app says: "Activate exposure logging to evaluate your risk status".

If you disable Bluetooth whilst exposure logging is active in CWA, then Google (not CWA) sends a warning after a delay. I have not checked that lately, but it used to be after 30 minutes.

I don't know if it is possible to enhance CWA Android so that it continues to do risk evaluation if exposure logging is disabled. This is not something which I can try out because the API is only enabled for developers who have special rights. The question would need to be addressed to the Open Source Team.

The API specification is on https://developers.google.com/android/exposure-notifications/exposure-notifications-api for reference.

I think there is value to this request. For instance, a health worker may want to disable exposure logging if they are dressed in full protective clothing, however they may want to continue to be informed without delay about any newly discovered exposure risk that might have taken place at an earlier time whilst they were in a different and unprotected environment.

There is additional information in the FAQ https://www.coronawarn.app/en/faq/#android_location about location access which is not required starting with Android 11.

**Comment by mtwalli** [comment]
@madiko Unfortunately it is not something that we can change from CWA, we are relying on Google Exposure Notification System. For more information please refer to [architecture](https://developers.google.com/android/exposure-notifications/exposure-notifications-api#architecture)

**Comment by madiko** [comment]
Thank you for letting me know @mtwalli.

I still can't understand, why it is not possible to distinguish between matching _already existing data_ (who is infected that I was exposed to via data match) and actually _collecting new data_ (and therefore switching on Bluetooth/GPS and collecting data), but anyhow, I give up. Either it is really not possible or you do not want to. For me it makes no sense to keep on going when there is no will to solve or to consider data economy.

**Comment by mtwalli** [comment]
@madiko  That is already the case. 
1- Matching does not require bluetooth or location because key packages are downloaded from the server and them it matched against keys you have on the device.
2- Exchanging keys between nearby devices requires bluetooth and on some devices location to be enabled (Google Exposure API) As I already mentioned above this is the way how Google and Apple designed it. we (developer of CWA) are just consuming these APIs. Please see https://www.google.com/covid19/exposurenotifications/ for more information.

**Comment by madiko** [comment]
I will. Thank you again. 
Have a nice day.
