### ISSUE TITLE
Bluetooth disabled after update to 2.16.2

### ISSUE THREAD

**Issue by Thomas1664** [corona-warn-app/cwa-app-android#4706]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Galaxy A 50
- Android version: 11
- App version: 2.16.2

## Describe the bug
After updating to version 2.16.2 last night, CWA notified me that Bluetooth was disabled. I couldn't enable Bluetooth so I had to restart my phone.

## Additional context
I am 100% sure that I didn't disable Bluetooth manually. I am also sure that I don't have other apps installed that do something with Bluetooth.

**Comment by MikeMcC399** [comment]
@Thomas1664 

I also updated a Samsung Galaxy A50 device running Android 11 yesterday to the current 2.16.2 version. The phone was previously running CWA version 2.15.1. I didn't have a problem with Bluetooth, and CWA continued without interruption after the update. My device is SM-A505FN/DS updated to security patch level 1 December 2021.

If you could not enable Bluetooth without restarting the phone that points more to a temporary Android or hardware issue rather than a problem with the CWA app.

There is a closed issue https://github.com/corona-warn-app/cwa-app-android/issues/988 which describes a similar problem. It does not look like the problem is caused by the app however.

**Comment by Thomas1664** [comment]
Ok, likely it's not caused by the app, but might be related to ENF.
