### ISSUE TITLE
Certificates get split because standardized name does not completely match

### ISSUE THREAD

**Issue by TimH54** [corona-warn-app/cwa-app-android#4713]
I have browsed the open issues to see if this was already in here and did not see it. Apologies if I missed it and it is a duplicate.

Anyway, I have the problem that from my three vaccination certificates, two were issued to my "standardized name" including my "Dr." title, and the third was issued to my "standardized name" but without the title. The app now lists them as two separate certificates.

I have heard from other people who have had the same problem because, for example, their second forename was once included and once not.

An easy solution would be to allow users to merge the certificates manually. Obviously, this should only be allowed if other data match among the certificates (birthdate, ...) and possibly after checking that there is reasonable overlap in the "standardized name".

It might just be a cosmetic problem, but it might also lead to discussions in case certificates are checked, so I think it would be good (and easy) to fix this.

**Comment by dsarkar** [comment]
Hi @TimH54 

this is related to:

https://github.com/corona-warn-app/cwa-wishlist/issues/748
https://github.com/corona-warn-app/cwa-wishlist/issues/705
https://github.com/corona-warn-app/cwa-wishlist/issues/705#issuecomment-986247875
https://github.com/corona-warn-app/cwa-wishlist/issues/754

---
Internal Tracking ID: [EXPOSUREAPP-11014](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11014)

**Comment by Ein-Tim** [comment]
@dsarkar 

Do you want this issue to stay open? I think it is a duplicate of https://github.com/corona-warn-app/cwa-wishlist/issues/705, or?

**Comment by vaubaehn** [comment]
As already commented elsewhere:
This will change from a cosmetic problem to a more fundamental problem in some weeks, when CWA/CovPass/CovPassCheck shall be ready to correctly detect immunization & test status with regard to applied admission rules (2G +/B, 2G +, 2G...). In all cases when 2 (or even more) certificates will be needed to be eligible for admission, then at least these certificates must match. Otherwise the apps can't detect, that both certificates belong to the same holder. This will be crucial when checked with CovPassCheck or with a validation service after DCC ticketing is started.

**Comment by Ein-Tim** [comment]
FYI: iOS PR https://github.com/corona-warn-app/cwa-app-ios/pull/4179 starts working on an automatic solution, e.g. filtering out "Dr." ([link to code](https://github.com/corona-warn-app/cwa-app-ios/pull/4179/files#diff-301ce2b909539e9b152de45bc1275cb29e09382c1c9c7d645f9a55efbef34c09R100)).

**Comment by MikeMcC399** [comment]
@dsarkar 
This issue should have the `Fix 2.19` label applied.

**Comment by MikeMcC399** [comment]
Hello Dr. @TimH54

It would be good to get your feedback, when you have had the opportunity to install and check the 2.19, if the issue is resolved using your certificates.

The blog announcement [CWA 2.19 improves the assignment of certificates to persons](https://www.coronawarn.app/en/blog/2022-03-16-cwa-2-19/) and the FAQ [What happens if the names of my certificates do not exactly match?](https://www.coronawarn.app/en/faq/#cert_fault_tolerant_name_handling) 

"A doctorate in a name will now be ignored for the purpose of comparing names."

explicitly say that the case reported in this issue is resolved.

---
CWA Android 2.19 is still in a 48 hour staged rollout since Wednesday morning, so it may not be available to you yet.

**Comment by TimH54** [comment]
Hi @MikeMcC399,

I confirm that my certificates have been merged on CWA 2.19 Android. Thanks a lot!

**Comment by dsarkar** [comment]
@TimH54 Thanks for reporting and your feedback.

Best wishes, DS

---
Corona-Warn-App Open Source Team
