### ISSUE TITLE
"Es gibt Neuigkeiten zu Ihren Zertifikaten" shown without any news (booster notification missing)

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4746]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Huawei P Smart 2019
- Android version: 10
- App version: 2.16.2

## Describe the bug

The app shows this on the persons overview screen:

<img src="https://user-images.githubusercontent.com/67682506/151186831-f003ef10-6557-41ef-8fe3-0308d4f029ec.JPG" width="300">

However, when clicking on the certificates, there are no news shown:

<img src="https://user-images.githubusercontent.com/67682506/151186911-9057d243-17ad-4805-97a0-a1d2a0e0222a.JPG" width="300">

## Steps to reproduce the issue

Not too sure, there is nothing special I have done. This certificate is already registered in the app for >3 months. 

## Expected behaviour

The text "Es gibt Neuigkeiten zu Ihren Zertifikaten" should only be shown if there are news. 

## Additional context

As you can see, the last vaccination is more than 180 days ago, so the app should show a booster recommendation. However this is not the case. Maybe this is the root cause of this issue? 

- Also, the red dot does not disappear, even after opening the details screen of the 2/2 DCC
- The 2/2 DCC is the only DCC of this person in the wallet

---
Internal Tracking ID: [EXPOSUREAPP-11593](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11593)

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- Do you have certificates for multiple persons stored on this device?
- Can you identify which of the rules should have been applied, depending on age, etc.? @dsarkar posted the current rules in https://github.com/corona-warn-app/cwa-wishlist/issues/684#issuecomment-1020570848

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Do you have certificates for multiple persons stored on this device?

Yes, for 9 persons.

> Can you identify which of the rules should have been applied, depending on age, etc.?

BNR-DE-0100 should be shown. There person is <70 years old.

**Comment by larswmh** [comment]
Thanks for your report @Ein-Tim. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-11593](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11593)

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> BNR-DE-0100 should be shown. There person is <70 years old.

Did you mean to write "The person is >=70 years old"? The text for `BNR-DE-0100` says:

"The Standing Committee on Vaccination (STIKO) recommends that all persons who are 70 and over and who have not had a proven case of the coronavirus (SARS-CoV-2) have a booster shot if they obtained their base vaccination more than six months ago."

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Yes, sorry.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thanks for the correction. That makes sense now.

In your screenshot where it says 
```
Impfstatus
Letzte Impfung vor 260 Tagen
```
I would expect to see the full text from the booster rule:

"Die Ständige Impfkommission (STIKO) empfiehlt allen Personen eine Auffrischimpfung, die mindestens 70 Jahre alt sind, bei denen keine Infektion mit dem Coronavirus SARS-CoV-2 nachgewiesen wurde und wenn ihre Grundimmunisierung über 6 Monate her ist.
Da Sie laut Ihrer gespeicherten Zertifikate dieser Personengruppe angehören und noch keine Auffrischimpfung erhalten haben, möchten wir Sie auf diese Empfehlung hinweisen. (Regel BNR-DE-0110)
Dieser Hinweis basiert ausschließlich auf den auf Ihrem Smartphone gespeicherten Zertifikaten. Die Verarbeitung der Daten erfolgte auf Ihrem Smartphone. Es wurden hierbei keine Daten an das RKI oder Dritte übermittelt."

**So the concrete point of this issue is that the booster notification is not shown for a person older than 70 years with the previous vaccination more than 6 months ago.**

**Comment by dsarkar** [comment]
@Ein-Tim Thanks for the report. 

So I understand the red dot does not disappear.
From the screenshots I can see that you are not in the detail view of a certificate. Can tap on the 2/2 DCC and have a look there? I think then the dot disappears. Now, you are still right, where is the notification then?

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Indeed, I would also expect notification rule BNR-DE-0110 (not BNR-DE-0100).
My understanding is:
- BNR-DE-0110 is sent after 6 month
- BNR-DE-0100 is sent after 5 month and before 6 month are elapsed since date of last vaccination

**Comment by Ein-Tim** [comment]
@dsarkar

> From the screenshots I can see that you are not in the detail view of a certificate. Can tap on the 2/2 DCC and have a look there? I think then the dot disappears. 

I tried this but this did not help. The dot then only disappears if the certificate was just imported. 

Regarding which notification should be shown: I scanned the certificate on my iPhone XR and there it shows the BNR 0110.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> Regarding which notification should be shown: I scanned the certificate on my iPhone XR and there it shows the BNR 0110.

Is it possible for you to scan the certificate on another Android phone with no other certificates and check whether a booster notification is generated? It might be possible to find out then which factors are affecting the issue.

(BTW: In the original post you wrote: "This certificate is already registered in the app for <3 months." Did you mean less than 3 months ago or more than 3 months ago?)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Is it possible for you to scan the certificate on another Android phone with no other certificates and check whether a booster notification is generated? It might be possible to find out then which factors are affecting the issue.

Sorry, I only have access to this one Android device 👍

> Did you mean less than 3 months ago or more than 3 months ago?

More than 3 months, sorry. I was not careful enough when typing this in.

**Comment by dsarkar** [comment]
@Ein-Tim Are there more DCCs, apart from the 2/2? I assume you did this, but just in case: If there are more DCCs, open the detail screen of each of them: Red dot still there?

**Comment by Ein-Tim** [comment]
@dsarkar 

Only 2/2 is scanned in.

**Comment by dsarkar** [comment]
@Ein-Tim And you confirm  that the red dot still there, even after looking into the detail view?

**Comment by Ein-Tim** [comment]
@dsarkar

Yes, confirm.

**Comment by WiseWomanVP** [comment]
I can confirm that I have had the exact same problem. I had the red dot "Es gibt Neuigkeiten..." but no news. I updated this morning to Version 2.16.2 (ENF Version 18214815000) and thought the "2G" thingy looked nice. Except that my booster certificate has now disappeared, so I was unable to prove my 2G+ status! The CWA tells me that my last vaccination was in June, not in November 2021. I tried to re-scan the 2D Barcode for my third vaccination, it told me that I had already scanned that barcode.

After re-booting the device I now have the Certificate for the third vaccination "on top", but it only says "2G" and not "2G+". This might be a problem since the goverment is changing the meaning of the terms constantly, but it would nice to have it say the right thing and not have me have to dig around to find the third vaccination just to have a cup of coffee while shopping :)

And the red dot has now disappeared.

**Comment by Ein-Tim** [comment]
@WiseWomanVP 

Please take a look at https://www.coronawarn.app/en/faq/#admission_policy reg. the 2G+

**Comment by WiseWomanVP** [comment]
@Ein-Tim Thanks for the link. 
"The project team is already working on ensuring that the Corona-Warn-App will include certificates of booster vaccinations accordingly in the future." My hope would be that "in the future" happens in less than a week.

**Comment by Ein-Tim** [comment]
@WiseWomanVP 

The whole 2G+ topic is highly complex: https://github.com/corona-warn-app/cwa-app-ios/pull/4119#issuecomment-1024885520

**Comment by Ein-Tim** [comment]
@mtwalli 

I will continue to monitor the behavior & if I don't observe this anymore I will let you know.

**Comment by mtwalli** [comment]
@Ein-Tim  any updates?

**Comment by Ein-Tim** [comment]
@mtwalli 

Thanks for the reminder, yes, this has been fixed!
