### ISSUE TITLE
Twitter Reports: App Shows certificates as invalid, after one day, they are valid again

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-app-android#4786]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Pixel 2
- Android version: 11
- App version: 2.16.2

## Describe the bug

A user on Twitter reported, that all of a sudden, the certificates of herself and from her children are shown as invalid:
<img src="https://user-images.githubusercontent.com/67682506/152547116-afb4d439-d256-4aa7-b9ba-34bfddcba8f9.png" width="300">

She [confirmed](https://twitter.com/frustfliege/status/1489365726309883904?s=20&t=ex97vxfGdt8xT4TmzNodeg) that she was still able to add the certificates to CovPass and they were not shown as invalid.

After waiting one night, the certificates are now shown as valid again: https://twitter.com/frustfliege/status/1489501872897593344?s=20&t=ex97vxfGdt8xT4TmzNodeg

## Steps to reproduce the issue

Not clear.

## Expected behaviour

Certificates should never be shown as invalid unless they are invalid. 

## Additional context

1. This bug report is based on this Tweet: https://twitter.com/frustfliege/status/1489332828655468552?s=20&t=ex97vxfGdt8xT4TmzNodeg
2. This bug was also reported by another user: https://twitter.com/tsia/status/1488847022941782025?s=20&t=ex97vxfGdt8xT4TmzNodeg who confirmed the same behavior via DM to me

## Pings 

cc @thomasaugsten 
FYI @molk-ibm, @vaubaehn

---
Internal Tracking ID: EXPOSUREAPP-11763

**Comment by Ein-Tim** [comment]
@vaubaehn 

All stored certificates where affected, regardless of dose number, series of total doses or the type of vaccination.

**Comment by molk-ibm** [comment]
As this issue _resolved itself over night_, all that's left is to analyse possible execution paths that render the certs invalid.
I'd suspect a failure to download/update the _block lists_ combined with _unexpected_ exception handling.

**Comment by mtwalli** [comment]
An error report would be very appreciated?
DSC List is updated daily and cached to be used when there is no internet connection ,first we check the last cached version , if not then we use the default list ( bundled in the App ) see https://github.com/corona-warn-app/cwa-app-android/blob/658f702021dfce94278be40fdf9c43f386574ec3/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscRepository.kt#L34-L43

when DSC list is refreshed the cached version will updated 
https://github.com/corona-warn-app/cwa-app-android/blob/658f702021dfce94278be40fdf9c43f386574ec3/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/signature/core/DscRepository.kt#L47-L57



it might be also the `AppConfig` 
https://github.com/corona-warn-app/cwa-app-android/blob/658f702021dfce94278be40fdf9c43f386574ec3/Corona-Warn-App/src/main/java/de/rki/coronawarnapp/covidcertificate/common/statecheck/DccStateChecker.kt#L34-L42

which is used to check if the certificate is `BLOCKED`

**Comment by Ein-Tim** [comment]
@mtwalli 

Ad this seems like an edge case both user haven't had error logging active. If there should be another case I definitely will ask for a log.

**Comment by vaubaehn** [comment]
@mtwalli 
I'm throwing some speculations into the pot:
The pixel 2 is an old mobile, probably she has low internal storage left (@Ein-Tim , could you ask her for that?).
I assume, both DSC-list and appconfig active on runtime are stored in the apps' cache directory?
What happens when the cache gets wiped on runtime and the cached versions are not available for access anymore? With the first version of the error logging we had the same issue, but the app crashed in that case. Are exceptions due to deleted cache files captured gracefully in a similar way for DSC list and appconfig? If not, may there be a chance that dsc list becomes `null`?

**Comment by Ein-Tim** [comment]
>  (@Ein-Tim , could you ask her for that?)

Will do & report back.

**Comment by Ein-Tim** [comment]
@vaubaehn 

She answered: "44 von 64 GB belegt."

**Comment by svengabr** [comment]
Internal Tracking ID: EXPOSUREAPP-11763

**Comment by vaubaehn** [comment]
> @vaubaehn
> 
> She answered: "44 von 64 GB belegt."

Thanks, @Ein-Tim . Then a problem associated with (automatic) wiping of the cache is not impossible, but rather unlikely.

**Comment by vaubaehn** [comment]
I just found another thing - it may be related, or maybe not. But in any case could be good to have a look at it:

@mtwalli , you mentioned above, that in case CWA can't access a cached appconfig or dsc list, it uses the default files. I guess you refer to the .bin files that reside inside the assets directory?
I just saw that the default appconfig hadn't been changed since 10 months and the dsc list for six months.
As far as I remember for the appconfig some parameters changed meanwhile and I think it was extended for some parameters, wasn't it?
And for the dsc list there could also be some changes meanwhile. Afair the 'open access issuance servers' in some countries led to a revocation of dscs 3-4 months ago.
Maybe you can assess whether an update of these default files could be released with 2.18?

**Comment by mtwalli** [comment]
@vaubaehn Yes, I am referring to the default bin files, we do update these files when needed, being old does not mean that they are outdated. For some features we do hardcoded values that don't need a default `appConfig` update. can you please point me out to the revocation issues you mentioned? I can align with Max, to see if an update if needed

**Comment by vaubaehn** [comment]
@mtwalli thanks for your considerations. I'll come back to you next week for details.

**Comment by mtwalli** [comment]
@Ein-Tim without error report this issue can't be investigated, If the user is not experiencing this anymore I suggest to close it ? Specially that the app recovered from it automatically

**Comment by Ein-Tim** [comment]
@mtwalli Agreed!

**Comment by mlenkeit** [comment]
Just for the record, this might have been related to a flaky network connection and an outdated default list of DSCs for verifying the signature of the DCCs. This was updated with e.g. https://github.com/corona-warn-app/cwa-app-android/pull/5363.
