### ISSUE TITLE
Deleted test certificate still shown on start activity

### ISSUE THREAD

**Issue by uwemock** [corona-warn-app/cwa-app-android#4803]
## Technical details

- Device name: Samsng Galaxy A40
- Android version: 11
- App version: 2.17.2

## Describe the bug

I had a test certificate that had expired after 2 days. The CWA start activity showed "Test has expired" ("Test nicht mehr aktuell"), so I deleted the certificate, i.e. it was moved to the trash can. With the expired test certificate in the trash can, the start activity still shows the notice that the test has expired. Expected behaviour: Any certificates in the trash can don't show up anywhere in the app (except the trash can).

## Steps to reproduce the issue

- Import a test certificate to the app.
- Wait until the test has expired.
- Move the expired certificate to the trash can.
- The expired certificate in the trash can still shows up on the start activity.

## Expected behaviour

Any certificates in the trash can should not show up anywhere in the app (except the trash can).

**Comment by Ein-Tim** [comment]
Test Results (shown on the "Status" tab) and Test Certificates are two different things. The only connection is that with a test result you can also request a test certificate, however, if you have a test result in the app you don't automatically have a test certificate in the app and vis versa.

**Comment by Ein-Tim** [comment]
The point I'm trying to make here: Test certificates and test result are deleted independently of each other - deleting a test certificate does not delete the test result, deleting a test result does not delete a test certificate.
If you think this should be changed I recommend to open an enhancement request.

**Comment by uwemock** [comment]
I consider it a bug when something leaves a residue that just tells the user "I am useless" and offers for removal.
When two things are so obviously connected, removing the one should also remove the other.
So you just confirmed the bug. Thanks!

Is this bug part of the specification? Does the specification provide a reason for disconnecting the "Test Result" from the test certificate? How does the user benefit from this behaviour?

**Comment by vaubaehn** [comment]
Hi @uwemock ,

@Ein-Tim tried to respond to you, to support you in your issue, but he was obviously blocked by you, and is now not able to assist in any way here.
There is a Code of Conduct for contributors (https://github.com/corona-warn-app/cwa-app-android/blob/main/CODE_OF_CONDUCT.md) that counts some behaviors that voilate against the Code of Conduct.
I couldn't find any, that @Ein-Tim would have violated.
Please consider if blocking one of our best volunteer community supporters, who tried to assist you in an purely objective way, may violate against this point of the CoC:
> Other conduct which could reasonably be considered inappropriate in a professional setting

It's your personal choice to keep him blocked, but this increases the chance that you won't find the reponses or help here that you expect, also from other supporters.

Thanks for reading, have a good night.

**Comment by uwemock** [comment]
@vaubaehn Thanks for pointing me to that source. This helped me a lot.

Considering your hint on blocking might be violating some CoC: As the blocking mechanism is provided as a tool by the platform, I cannot see how using that tool could be found inappropriate. On the other hand, taking care for oneself should always be considered appropriate - in any context.

And, btw, I was not asking for help or support.

**Comment by dsarkar** [comment]
Dear @uwemock, 

We welcome and encourage everybody to participate in this project and we appreciate all the different inputs we receive, for example bug reports, proposals for feature enhancements, questions, discussions, code, PRs, suggesting/creating/reviewing content, the website functionalities and so forth. Even though discussions might get heated sometimes (rather on very few occasions), we think that within this community here on GitHub in this project it is very much appreciated that we act welcoming and inclusive as well as deal with each other with great respect.
 
With regard of blocking @Ein-Tim: As mentioned already above by another community member, he is one of the very active - and I dare to say, very respected - member of the community and we cannot stress enough how much we welcome his and other's contributions to this project. From your writing above we understand that the reason of blocking him relies solely on this thread/issue. Since obviously he did not violate the CoC, we consider this to be a private matter between you two. This is an open forum and everybody should have the possibility to contribute as long as they comply with the CoC. 
 
Therefore, we kindly ask you to unblock him so that you can interact again in other issues and pull requests. As we need to follow-up with this issue and ensure that all community members can participate, we will close and lock your issue and create a new one (in this specific case it would be an enhancement request, since currently we do not consider your reported issue as a bug) with your report and everybody, including you and @Ein-Tim will be able to read it and contribute to it. 
 
Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by dsarkar** [comment]
continues here https://github.com/corona-warn-app/cwa-wishlist/issues/783
