### ISSUE TITLE
Let the user choose the app language

### ISSUE THREAD

**Issue by ffflorian** [corona-warn-app/cwa-app-android#483]
## Feature description
Let the user choose the app language independent from the device language.

## Is this something you're interested in working on
No, since I don't know how to write Kotlin :)

**Comment by emilyhunt** [comment]
This would be really helpful! I keep my phone in German as a way to help me learn the language. But for important life threatening stuff we should have the choice to choose the app language (I wouldn't want to miss anything), opposed to only being able to use the device language. I'm sure many others will have the same issue (I know many Germans who have their device set to English so that debugging issues is easier, but they'd probably rather get important information like this in German.)

**Comment by krin-san** [comment]
For me applications is shown in English language even though AOS Languages settings has "Russian" and "Deutch" (exactly in that order). I assume that app picks first language from that list and falls back to English. Is there a workaround to see app in German, besides moving "Deutsch" to the 1st place?

**Comment by tkowark** [comment]
We have a request for this language selection in the documentation repo corona-warn-app/cwa-documentation#153 and would like to bundle discussions there.

As for the issue of @krin-san , could you kindly open this as a dedicated bug?

**Comment by ffflorian** [comment]
This is now tracked in https://github.com/corona-warn-app/cwa-wishlist/issues/22.
