### ISSUE TITLE
R-Wert not in line with guthub repo nowcast

### ISSUE THREAD

**Issue by btreut** [corona-warn-app/cwa-app-android#4954]
* [ x] None of the other issue templates apply to this issue.

the R-Wert and its tendency displayed in CWA Android is different from what I find in https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/blob/main/Nowcast_R_aktuell.csv

Why?

**Comment by Ein-Tim** [comment]
The R-Wert for today is in line with the one from the RKI.
The R-Wert from the RKI can be found here: https://www.bundesregierung.de/breg-de/themen/coronavirus/fallzahlen-coronavirus-1738210

**Comment by MikeMcC399** [comment]
@btreut 

You didn't actually say what value for the 7-Day R Value which you are seeing in the app. I am seeing 0.99 today.

You can see on the [CWA web Dashboard](https://www.coronawarn.app/en/analysis/) if you scroll to the bottom and select [RKI: Covid-19 Trends (GER)](https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/COVID-19-Trends/COVID-19-Trends.html?__blob=publicationFile#/home) that the value displayed there is also 0,99.

You can find the same value in the daily report from RKI https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Situationsberichte/Maerz_2022/2022-03-17-de.pdf?__blob=publicationFile from yesterday.

![image](https://user-images.githubusercontent.com/66998419/159006650-938255bd-c369-4b4e-9b29-10e7aede0718.png)

---

If you want to find out about the correlation of the dates used in the table on https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/blob/main/Nowcast_R_aktuell.csv compared to what is shown in RKI's daily report, you should probably ask in the https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung repository.

---

The value in the app today seems to be correct.

**Comment by vaubaehn** [comment]
@btreut 
Additionally to the nice explanation from @MikeMcC399 :
The values in the csv you linked to are not up to date, the latest values are for 2022-03-14.
Also, when you look to the history of that repository, you will see that older dates are updated/corrected: https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung/commits/main/Nowcast_R_aktuell.csv
Assumingly, this is due to "Nachmeldungen" from the federal states that result in higher r-values calculated for the past.
But like Mike wrote, it's better to directly ask in the RKI repo.

**Comment by btreut** [comment]
I see in cwa 0.99 and increasing tendency.
The tendency in the actual now casting table is decreasing. The latest R-Wert in the now casting table is 1. It cannot be calculated for today.

**Comment by btreut** [comment]
Sorry, conflicting numbers on different pages of the same source (RKI) do not increase the confidence in the presented numbers. The figures 4 pasted by @MikeMcC399 above clearly show a decreasing tendency, but cwa displayed an increasing.

**Comment by MikeMcC399** [comment]
@btreut 

I agree that the trend shown in the app contradicts the graph. The "7-Day R Value" is the a difficult statistical value to understand and use.

You might find the explanations and links in

- [Tile "7-Day R Value"](https://www.coronawarn.app/en/blog/2021-08-05-statistictiles/#tile-7-day-r-value) (English)
- [Kachel "7-Tage-R-Wert"](https://www.coronawarn.app/de/blog/2021-08-05-statistictiles/#kachel-7-tage-r-wert) (German)

helpful for more background reading.

**Comment by Ein-Tim** [comment]
@btreut Was it your intention to close this issue?

**Comment by btreut** [comment]
my arguments are more or less wiped away and labelled as irrelevant. I do not want to get lost in retargeting data sources. To my knowledge the github repo for nowcasting  is the primary source and if this is not acknowledged then I do not want to get lost in strange discussions about other publications of RKI, with different numbers.

**Comment by vaubaehn** [comment]
> my arguments are more or less wiped away and labelled as irrelevant. I do not want to get lost in discussions about other data sources. To my knowledge the github repo for nowcasting is the primary source and if this is not acknowledged then I do not want to get lost in strange discussions about other publications of RKI, with different numbers.

@btreut 
No one wants to wipe away your arguments. What we were trying to do is to find an explanation together with you. You can be sure that the community here has a critical eye on functioning and possible wrong data sources, that certain that I can speak for everyone participating in this discussion, that we're thankful for everyone coming up with such an issue.
However, I'd like you to again have a look at the RKI data set in the corresponding repo. From the description it's obviously a different dataset aimed for research. According to the history of commits to the dataset from their maintainers, it looks like it's trimmed for accuracy and changed whenever new data are coming in ('Nachmeldungen').
The r-value that is reported daily (and that is displayed in the app and on the RKI website) can only be weak estimate with regard to the reporting processes and capacities in the federal states.

**Comment by MikeMcC399** [comment]
@btreut 
> my arguments are more or less wiped away and labelled as irrelevant. 

I am sorry if you feel that you were not taken seriously! @Ein-Tim has written in parallel to me and also says the same.

I took another look at the tables and it seems that the values which are published in RKI's daily situation reports are not always aligned to the data in the table. That may be due to the daily recalculations which also affects previous days. See [Daten and Datenaufbereitung](https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung) "Die Schätzwerte zur Anzahl von Neuerkrankungen und der R-Schätzung zu früheren Tagen können von den Angaben in früheren Versionen der Tabelle abweichen, weil täglich der Gesamtverlauf, aufgrund der aktuell verfügbaren Daten, neu geschätzt wird.".

The app just displays the data which RKI provides on their data server, so I'm afraid that you won't get any more detailed insight and feedback here in the Android app repository. This part of the data connection from the app back to the data server is not open-source, so we from the community can't see what is being done.

The readme section [Administrative und organisatorische Angaben ](https://github.com/robert-koch-institut/SARS-CoV-2-Nowcasting_und_-R-Schaetzung#administrative-und-organisatorische-angaben) says: "Inhaltliche Fragen bezüglich des Nowcastings und der R-Schätzungen können an an das RKI unter [info@rki.de](mailto:info@rki.de) gestellt werden." It sounds like you do not want to go any further with your issue, but if you do, then the RKI e-mail address may be able to give you an answer.

**Comment by MikeMcC399** [comment]
@dsarkar 
Please move this issue to the cwa-documentation repository, since it is an issue affecting both Android and iOS. I will research the issue in more detail and (hopefully) provide a better answer.
