### ISSUE TITLE
Phone number in RAT Profile not saved (no message, just gone) when entered in a particular format

### ISSUE THREAD

**Issue by jkrwdf** [corona-warn-app/cwa-app-android#5130]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [X] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)  I DO NOT KNOW, HAVE NO IOS DEVICE WITH CWA
* [X] Bug is not already reported in another issue

## Technical details

- Device name: Google Pixel 4a (5G)
- Android version: 12
- App version: 2.21.1

## Describe the bug

Some phone numbers in quick test profiles are not saved and there is no message or error shown, the data is just lost unnoticeably.

## Steps to reproduce the issue

Create a quick test profile or update an existing quick test profile. 

Important for robust reproduction: There shall be no phone number entered yet. 

If you open an existing profile with number, clear the number first and save before you continue, otherwise it might be that you cannot reproduce the effect.

Enter this phone number:
`+49 172 123 45678`
(the spaces are important) and save. 
--> The number is not saved.

Now edit again and enter this same number without spaces (while entering "the system" will insert some spaces for you and you will get)
`+49 172 12345678`
--> Then the number is saved. 

Now it gets really weird.

Edit again and just insert a space between the "123" and the "45678" so you get to my first example
--> Now the number is saved in the first format. 

## Expected behaviour

Phone number is always saved. 

If CWA however accepts only certain formats and will not save others, an error message must be sent. 

---
Internal Tracking ID: [EXPOSUREAPP-12964](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12964)

**Comment by MikeMcC399** [comment]
@jkrwdf 

I can reproduce this issue.

**Comment by MikeMcC399** [comment]
It seems that there are two issues:
1. The error message "Invalid phone number" is only shown if the focus leaves the field "Phone Number". The problem can only be reproduced if at least one other field on the Rapid Test Profile is populated, otherwise the dialog will not allow the profile to be saved.
2. Spaces should be allowed in telephone numbers, however the dialog treats a space as a phone number input error

To show a bit more how the view reacts to inputs:
1. Delete any existing Rapid Test Profile
3. Enter `+491` into the field "Phone Number"
4. Note that `+49 1` is displayed and the `Save` button is active
5. Enter a space into the field "Phone Number" after the existing `+49 1`
6. Note that the `Save` button is deactivated (no error message is shown)
7. Tap on the Postal Code field and note that the Phone Number field label now shows an error
8. Enter "1" into Postal Code field and tap `Save`

**Comment by MikeMcC399** [comment]
@jkrwdf 

It looks like entering a space manually adds this to the end of the string which causes it to fail, presumably because the input dialog is also adding spaces automatically.

Try entering
`+49<space>172<space>123<space>45678`
then tap on the end of the string and delete the space after the `8`
In that case the phone number gets stored.

Anyway, this is all a bit buggy!

**Comment by jkrwdf** [comment]
> Try entering `+49<space>172<space>123<space>45678` then tap on the end of the string and delete the space after the `8` 

That's affirmative. The fact that "the system" has added an additional <space> at the end of the input text is not recognizable by the user unless one explicitly taps into the empty area behind the text;  then the input cursor moves forward from the location after the last number to the "hidden" space. 

Many thanks for breaking this magic issue down to the technical reason.

**Comment by MikeMcC399** [comment]
@dsarkar 
You've added https://github.com/corona-warn-app/cwa-app-android/labels/mirrored-to-jira to this issue. Will you also include the internal ID here?

**Comment by larswmh** [comment]
Thanks for your report @jkrwdf. We have created an internal ticket for it and will raise this topic internally.
Internal Tracking ID: [EXPOSUREAPP-12964](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-12964)

---
Corona-Warn-App Open Source Team

**Comment by larswmh** [comment]
I was able to reproduce this on version 2.21.1. However, it seems like this is already fixed in the upcoming version. Using version 2.22.0-RC1, it saved the telephone number.

**Comment by MikeMcC399** [comment]
@larswmh 

> I was able to reproduce this on version 2.21.1. However, it seems like this is already fixed in the upcoming version. Using version 2.22.0-RC1, it saved the telephone number.

I was able to reproduce the issue in 2.22.0-RC3

1. Click on Manage Your Tests
2. Scroll down and click on Rapid Test Profiles
3. Click "+ RAPID TEST PROFILE"
4. Enter "A" in "First Name" then "9" in "Phone Number"
5. Click "Save"
6. Note that only "A" is shown. "9" is not shown and there was no error message that the phone number was invalid.

**Comment by MikeMcC399** [comment]
There is a second problem that a phone number with a trailing space is not accepted as a valid phone number. This is also reproducible in 2.22.0-RC3.

1. Click on Manage Your Tests
2. Scroll down and click on Rapid Test Profiles
3. Click "+ RAPID TEST PROFILE"
4. Enter a valid telephone number, such as "08007540001" in "Phone Number" then add a space after the digits
5. Note that the "Save" button is now greyed-out

**Comment by dsarkar** [comment]
FYI PR https://github.com/corona-warn-app/cwa-app-android/pull/5175

**Comment by MikeMcC399** [comment]
- The fix for this issue https://github.com/corona-warn-app/cwa-app-android/pull/5175 is included in [v2.23.0-rc.1](https://github.com/corona-warn-app/cwa-app-android/releases/tag/v2.23.0-rc.1)
- If a phone number has an unacceptable format it is flagged immediately with the message "Invalid phone number", which remains visible until the phone number is removed or meets the validation check. 
- If a user enters spaces together with digits, it is still possible to end up with an trailing space character. A phone number with a trailing space is then flagged as invalid. I did raise this as a remaining issue (see https://github.com/corona-warn-app/cwa-app-android/pull/5175#issuecomment-1127426705), however it was not addressed in the PR. Even so, the new logic is a significant improvement on the current 2.22.1 version.

**Comment by jkrwdf** [comment]
Closing based on the fix description above. 

Thanks to all involved parties and @MikeMcC399 in particular.

The remaining issue with the suddenly appearing space-character at the end of the input field when space is entered in the middle is annoying, but if it does not lead any more to data loss upon save, this issue can still be closed. 

Eventually I open a new low priority one for this effect as soon as I have the new version on my device.
