### ISSUE TITLE
Contact Journal: Duration of places is not saved when using keyboard

### ISSUE THREAD

**Issue by j-l1nk** [corona-warn-app/cwa-app-android#5354]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Technical details

- Device name: Galaxy S21, Galaxy A41
- Android version: Android 12
- App version: 2.24.2

## Describe the bug

When changing the contact-duration for a place in contact journal by using the keyboard, the duration is not saved.

## Steps to reproduce the issue
* Open CWA
* Click on "Journal"
* Click on any day
* Switch to "Places"
* Select any place
* Click on the duration-input-field (where stands: 00:00)
* Click on "hours" and/or "minutes" in the time-wheel (where stands: 00)
* Insert a valid date by using the keyboard e.g. 11
* Click on "OK" while input-field is still selected
* See error: The date is not saved correctly

## Expected behaviour

Duration is saved correctly even if the user doesn't clicks outside the input-field before clicking the "OK"-button.

---
Internal Tracking ID: [EXPOSUREAPP-13642](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13642)

**Comment by dsarkar** [comment]
@j-l1nk Thanks for reporting, we will have a loom at this. Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@dsarkar 

I can reproduce this issue that the Journal Places Duration keyboard input for hours and minutes is only saved after leaving the respective input field before tapping OK. So if you want to enter 1 hours and 30 minutes, you need to type 01 in the hours field, 30 min in the minutes field, then tap the hours field again before tapping OK.

In general, entering the duration using the keyboard instead of sliding up and down to select hours or minutes does not work well at all. Apart from the bug mentioned above, to enter 2 hours, it is necessary to type 02, otherwise the field records 20 hours. I would expect to be able to type just "2" to get 2 hours.

It is not possible to enter 15 minutes via the keyboard and there is no error message to indicate why 15 minutes is not accepted. If some input is not accepted then I would expect to see some explanation about why the input does not work.

**Comment by dsarkar** [comment]
@j-l1nk @MikeMcC399 Thanks for reporting and feedback. Internal Tracking ID: [EXPOSUREAPP-13642](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13642).

Best wishes, DS

---
Corona-Warn-App Open Source Team

**Comment by mtwalli** [comment]
Keyboard type would required an edit mode similar to Date and Time pickers so user can get feedback when wrong values are entered by keyboard such as an error message. Duration Picker is designed to provide a defined set of values, therefore I blocked keyboard typing in here

**Comment by MikeMcC399** [comment]
- The issue also affects other places where the Duration Picker is used, so PR #5496 for 2.27 looks good.
