### ISSUE TITLE
Bluetooth Benachrichtigung/Warnung nach Deinstallation

### ISSUE THREAD

**Issue by andreasblueher** [corona-warn-app/cwa-app-android#571]
## Describe the bug
Hallo, ich hatte die App gestern auf meinem Samsung S9 (Android 10) installiert und habe sie zu späterer Zeit wieder deinstalliert. Trotz Deinstallation und Neustart des Gerät wird mir beim Deaktivieren meines Bluetoothadapater immer noch die Warnung der Corona Warn App angezeigt.

![PHOTO-2020-06-17-08-36-30](https://user-images.githubusercontent.com/12544512/84864092-6d069980-b076-11ea-87da-de1199480f87.jpg)
![PHOTO-2020-06-17-08-36-22](https://user-images.githubusercontent.com/12544512/84864119-77289800-b076-11ea-9d5c-e008f79f2eba.jpg)

## Expected behaviour
Nach der Deinstallation sollte man keine Warnhinweise mehr erhalten, da ansonsten der Eindruck entsteht, die App würde im Hintergrund ohne meine Erlaubnis weiterlaufen.

## Steps to reproduce the issue
1. Corona Warn App installieren und einrichten
2. Corona Warp App deinstallieren
3. Bluetooth deaktivieren

## Technical details
Samsung S9 Android 9

Vielen Dank

**Comment by kolyaopahle** [comment]
Hello, thank you for the Report.
Unfortunately the error message you are receiving is caused by the operating system of your device, the app cannot influence if/how/when this dialog is shown.

**Comment by tomjschwanke** [comment]
Turn off the tracing in Google's settings and see if it's gone

**Comment by andreasblueher** [comment]
> Hello, thank you for the Report.
> Unfortunately the error message you are receiving is caused by the operating system of your device, the app cannot influence if/how/when this dialog is shown.

Shouldn't notifications be removed from my device if an app is uninstalled? Fair enough the operation system is giving them, but please don't tell me it's supposed to stay that way ;-)

> Turn off the tracing in Google's settings and see if it's gone

Turned it off and it's still happening

**Comment by pwoessner** [comment]
Hi @andreasblueher ,
you are right. The expected behaviour by the Google API is that as soon as you have no tracing app installed on your phone the tracing will be turned off immediately. This would also mean that if you turn off bluetooth you should not get a notification that tracing is no longer working since it should be stopped already.

You can check in the Google settings if tracing is somehow still active or maybe you have a different tracing app installed which could cause this behaviour?

Since this functionality is provided by Google (stop tracing on deinstall and triggering a notification when you deactivate bluetooth) there is unfortunately nothing we can do on our side. Therefore I am closing this issue.

Thanks,
Philipp

**Comment by andreasblueher** [comment]
Also mal ganz im Ernst: Ich als Techniker kann diese Antwort inhaltlich nachvollziehen, 98% der Deutschen könnten das mit Sicherheit nicht und wenn das Verhalten zum ersten Mal nach dem Deinstallieren der Corona App auftritt, dann ist es unwahrscheinlich, dass es eine andere App  verursacht.

Ich möchte für kein Geld der Welt mit euch in diesen Tagen tauschen, aber die Begründung ist schon ziemlich dünn und das Problem für _mich_ nicht behoben. In 20 Minuten Google Suche zu diesem Thema habe ich auch keine vergleichbaren Probleme oder Nutzererfahrungen zum Thema Notifcations, Tracings oder ähnlichem gefunden.
