### ISSUE TITLE
3.1.1 Android Error 39507

### ISSUE THREAD

**Issue by toteph42** [corona-warn-app/cwa-app-android#5902]
Hi,
error message appeared. Reinstalled app. During activation of "Riiko-Ermittlung" I get `UNKNOWN_ERROR_CODE(39507)`

**Comment by MikeMcC399** [comment]
@toteph42

- Is this the first time you tried to activate "Risiko-Ermittlung" on this device?
- Did you install the Corona-Warn-App from the Google Play Store?
- What device are you using?
- What is the version of Android?

[Google ENS error 39507: FAILED_UNAUTHORIZED](https://developers.google.com/android/reference/com/google/android/gms/nearby/exposurenotification/ExposureNotificationStatusCodes#public-static-final-int-failed_unauthorized)

![image](https://user-images.githubusercontent.com/66998419/226162953-9f4cf988-1cd3-44ce-869a-84bdae9a8f2a.png)

**Comment by toteph42** [comment]
- No, had it running for 2 years, but I just recognized discovery stopped working
- No, I got it from F-Droid (was not available @playstore)
- Galaxy A52s 5G
- Android 13 / One UI-Version 5.0

**Comment by MikeMcC399** [comment]
@toteph42 

> No, I got it from F-Droid (was not available @playstore)

This is the support list for the official app. If you got the app from F-Droid, then you should probably go to https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues with your problem.

If you are not seeing the app on https://play.google.com/store/apps/details?id=de.rki.coronawarnapp is your Google account linked to a country other than Germany or one of the countries listed on https://www.coronawarn.app/en/faq/results/#international?

The official app has been unofficially uploaded to https://www.apkmirror.com/apk/robert-koch-institut/corona-warn-app/ which bypasses the country checking.

> Galaxy A52s 5G
> Android 13 / One UI-Version 5.0

That's interesting because I just confirmed that the official version of the app from https://play.google.com/store/apps/details?id=de.rki.coronawarnapp works on a Samsung Galaxy A52 5G (SM-A526B/DS) with Android 13.

There will be information about ramp-down on https://www.coronawarn.app/en/faq/results/#ramp_down. It is planned to switch off the exposure notification functionality starting May 1, 2023.

**Comment by toteph42** [comment]
Your're rigth, I'm using corona tacking app...

**Comment by MikeMcC399** [comment]
@toteph42 

It seems to be a known problem on https://codeberg.org/corona-contact-tracing-germany/cwa-android/issues, so you should search in that list and check out the closed issues from other users reporting this problem.
