### ISSUE TITLE
Protest against silencing of community by locking issue #478

### ISSUE THREAD

**Issue by corneliusroemer** [corona-warn-app/cwa-app-android#600]
The maintainers 4min ago locked issue #478 as "too heated".

Nothing heated was going on, it was simply the community discussing reasons what the root issue and the reasons for it were.

The discussion started going in a direction that wasn't pleasing the maintainers/SAP so the discussion was locked - without comment nor warning. This is totally against the spirit of the project.

I'm opening this issue to continue the discussion.

**Comment by corneliusroemer** [comment]
Update: this is the statement from the maintainers
<img width="858" alt="Screenshot 2020-06-17 at 16 04 07" src="https://user-images.githubusercontent.com/25161793/84908055-449d9000-b0b4-11ea-862b-fc7aa9f05f81.png">
It's not clear what the profane language was. "Clusterf*ck?"
Again, it's not explained how anything said was against the Code of Conduct. No discussion with the community.

If someone is contravening the code of conduct, it's the maintainers. I am writing a request to investigate the silencing of the community.

@piratenkatzerr, @fhajji, @arianvp @dalbre, @treysis, @sschuldenzucker

**Comment by arianvp** [comment]
@corneliusroemer I do not think this is a very constructive way to make this point and I do not want to be associated with this discussion further.

I think we made pretty clear what the problem is, and what the solutions are, and we can now wait for a solution to come.  

 Locking a thread when the tone of the discussion is getting grim is something that's in their right to do especially when the signal-to-noise ratio of an issue starts to get big.  My two cents as an open source maintainer.

**Comment by mohe2015** [comment]
I think their reaction is totally fine. They are probably just communicating with the RKI and Google to get the app available in more countries. Also every comment that doesn't help to resolve a discussion just notifies all watchers.

**Comment by treysis** [comment]
@mohe2015 Just unwatch then...

While I agree everything has been layed out, I don't agree with the behavior of quickly locking what could result in bad press. Anyway, I think this is all that I can contribute to this issue for today and I will just silently monitor the progress for now.

**Comment by kbobrowski** [comment]
A suggestion for maintainers: maybe you could set up discord / slack channels for free-for-all, open, wild-west and heated discussions.

Regarding legal requirements, I think discussing whether there is a legal requirement or not may be even constructive for solving these problems, since I'm sure community would start to dig into German law to determine it quickly and perhaps could support you with findings. We are not only developers / users, I'm sure we'd find some lawyers among ourselves as well.

But I agree that such heated discussions on GitHub issues may be counter-productive, overwhelming, and sometimes violating code of conduct - that's why it's common to have a project discord / slack for such discussions - it would keep GitHub issues temperature much lower!

**Comment by corneliusroemer** [comment]
@fhajji in his comment raised a good point 
https://github.com/corona-warn-app/cwa-app-android/issues/478#issuecomment-645385879
It's important to know the details so that we can lobby in the right direction.
Is it in the contract that it's geo-locked? If not, what are the legal concerns raised by whom?

@arianvp made a very good point, that the Datenschutzfolgenabschätzung contains no basis to geo-lock. That makes it even more questionable what legal issues arose all of a sudden.
https://github.com/corona-warn-app/cwa-app-android/issues/478#issuecomment-645385599

By providing an update on what the precise issue is, the maintainers would enable us to lobby the right people to get this sorted quickly. Now we have to go very general instead.
The last update was yesterday evening, talking very broadly about "Special German laws". A more effective way to calm the "heated" discussion would be to update us so that we don't need to speculate.

@kbobrowski's idea of Slack/Discord is good for fast moving discussions. But I don't think the maintainers are agile enough to set it up - please convince me of the opposite!
Great point about the benefit of telling us what the legal problems are.

Violations of the code of conduct of individuals should not cause a lock on any issue as a whole. That's "Sippenhaft". The code of conduct is about individual behaviour. 
Community leaders, a term which ironically is just a euphemism for SAP maintainer, should issue corrections for every violation and if appropriate ask for apologies/edits.
Locking an issue for everyone as "too heated" as a result of putative violations is not part of the code of conduct. So if anything, it may seem that the leaders are not following the code of conduct guidelines for enforcement.
<img width="1053" alt="Screenshot 2020-06-17 at 16 36 13" src="https://user-images.githubusercontent.com/25161793/84911891-153d5200-b0b9-11ea-8847-e750b1c584a0.png">

**Comment by JProof** [comment]
@corneliusroemer Mimimi.

**Comment by sschuldenzucker** [comment]
Yeah they were facing a lot of questions and complaints and they decided to address the language and one (minor) point of the discussion _exclusively_. Very strange and, again, feels like a populist exercise in reframing ("you can't say a bad word!!1" - and suddenly the content doesn't matter).

The maintainers could've tried to, you know, defuse the situation somehow. By explaining, reassuring people, providing some transparency. Like normal people do. Instead, they decided to just lock the issue. :(

They being said, I agree that while this discussion is important, a github issue is not the right place to have it.

**Comment by piratenkatzerrr** [comment]
@corneliusroemer apologies, if my usage of the word "clusterf*ck" have prompted the lock of #478. 

I think it would be helpful if someone from SAP/(T-Sys)/RKI/BReg would simply state what legal issues need to get sorted out. Vaguely pointing to "special German laws" comes across as rather ominous and prompts more questions (as demonstrated) than it gives answers to. This is mostly about good community management and open communication. 
Overall, maybe bring in someone from the press office of RKI or BReg to handle the communication on all issues that are less technical and involve more of a legal and/or political background/reasoning (to the technical problems that arise here). After all, RKI and BReg are the ones making those decisions anyways... let their comms professionals handle it...
(I guess, it's either IP rights or data protection/DSGVO/BDSG and whatever consequences might come form a distribution outside of "Germany". ) 

Regarding [#478 comment](https://github.com/corona-warn-app/cwa-app-android/issues/478#issuecomment-645385599), the DPIA does not explicitly require to geo-lock, buuuuut geo-locking is in sync with restricting access to the app to persons 16 or older. Or at least offloads the legal responsibility onto the Google Play Store since their terms and conditions state a minimum age of 16 for Germany. (Note: it differs between countries.)
(The CWA's age rating (IARC/USK) is set at 0 in the Google Play Store though.) 

It's a great mystery. Looking forward to it being resolved. Eventually. Hopefully.

**Comment by jarjarbentley** [comment]
Dear @corneliusroemer ,

We highly value your passion for this topic and your contributions in the community. Nevertheless, we would like to highlight the code of conduct which explicitly mentions personal attacks as an unacceptable behavior.

You accused the maintainers of cover ups because they are not responding in your desired time frame. So, unfortunately, this leaves us no choice but to issue an official warning with this response.

Please note, that new issues going in the same direction which complain about this email response or about the closure of issue #600 will lead to a temporary ban immediately. Continued behavior that violates the code of conduct can also lead to further consequences for participating in this community.

We'd like to also inform you that the discussion was not closed because of individual code of conduct violations, but because discussions got too heated even after we already mentioned that we will take care of the issue and report back as soon as we can.

Best regards,
JB
Corona-Warn-App Open Source Team
