### ISSUE TITLE
FAQ: CWA working after device got switched off/on? 

### ISSUE THREAD

**Issue by DonRevilo** [corona-warn-app/cwa-app-android#617]
Will the CWA automatically continue to work (i.e. log contacts) even after the device got fully switched off and back on? Or does it need to be reactivated manually?

**Comment by kolyaopahle** [comment]
Hi @DonRevilo,
the contact tracing is provided by the google play services and will also work after a reboot or power cycle of the device, even without opening the app again.

**Comment by NKarolak** [comment]
But the app's **Terms of Use** tell you otherwise.
They tell you that after a phone restart, Android update etc. you are obliged to open the app manually.

I called the technichal hotline yesterday, and I was told that this has to be writte because the app developers cannot guarantee that every (older) phone would work like expected. E.g. it could theoretically happen that after the restart, bluetooth would not start. So just to be sure, we have to check ourselves.
