### ISSUE TITLE
Implement a proper Network Security Configuration

### ISSUE THREAD

**Issue by thecloudseeker** [corona-warn-app/cwa-app-android#63]
## Current Implementation
Currently a Network Security Configuration is declared but it is empty.

## Suggested Enhancement
Please implement a proper network security configuration for certificate pinning and setting up trusted Certificate Authorities. 

## Expected Benefits
Enhanced security and reduction of security vulnerabilities.

**Comment by kolyaopahle** [comment]
related to #7

**Comment by jakobmoellersap** [comment]
We are considering an in-code pinning (to allow for dynamic pin exchange down the line)

**Comment by jakobmoellersap** [comment]
Please note that we support API 23+
We will add a more specific Network Configuration regarding Certificate Stores and also clearText restrictions.

I will link the PR once ready.

All the best,
Jakob

**Comment by jakobmoellersap** [comment]
The only TODO left is the integration of the final verification URL, other than that we have a Pinning Setup. There is currently no Backup-Pin but this might change (e.g. through an update). Secure Network Communication is enforced, System Certificates are taken into account but do not override Pinning as Trust Anchors. Additional Verification is done for the Application Configuration. For us, this issue is thus solved.
