### ISSUE TITLE
"Low Risk" -> "App did not detect any source of risk" to properly manage expectations

### ISSUE THREAD

**Issue by ramboldio** [corona-warn-app/cwa-app-android#640]
"Low Risk" in home screen suggest that the app can guarantee safety. Rather use "App did not detect a source of risk" or similar instead

**Comment by marcmuschko** [comment]
Hi @ramboldio,

thank you for bringing this up. As you are not the only one that has suggestions on this and as this is also valid for our corresponding iOS app, please move this discussion to the [documentation repository](https://github.com/corona-warn-app/cwa-documentation/issues/175) for general suggestions.

Since this seems to be a duplicate, I am closing this issue. 
Best, 
Marc
