### ISSUE TITLE
"Unbekanntes Risiko" keeps displaying

### ISSUE THREAD

**Issue by maxreb** [corona-warn-app/cwa-app-android#693]
## Avoid duplicates
* [x] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [x] Bug is specific for Android only, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [x] Bug is not already reported in another issue

## Describe the bug

I installed the app on the release date but even though I was outside my house to buy groceries my app still says 

> Unbekanntes Risiko
> Da Sie die Risiko-Ermittlung noch nicht lange genug aktiviert haben, konnten wir für Sie kein Infektionsrisiko berechnen.

I'm quite unsure why this is displayed and it makes me wonder if propaply the app doesn't work/has no background rights or something. I **do not** have activated power saving.

## Expected behaviour

It should display "Geringes Risiko" as it does by all my friends

## Steps to reproduce the issue

Front Page

## Technical details

- Mobile device: Huawei Mate 20 (HMA-L29)
- Android version: 10 (EMUI: 10.0.0.220)

**Comment by kilianhann** [comment]
I also had this issue for 3 days, today it changed to "Niedriges Risiko" "4/14 days".

Huawei P smart
Android EMUI 9.1.0.203

**Comment by queequac** [comment]
Same on my Xiaomi Mi 9T Pro.

It updated only two times in 5 days.
To be on the safe side I turned off smart battery mode for that app (unrestricted now), but interesting to see that app info always showed 0% battery usage. Looks like the app does not really run in background.

Today it turned back into unknown risk and shows "Risiko-Ermittlung aktivieren" (which actually is active and shows then "active for 5 days")

I know the app should be simple, but some more advanced info would be great to see whether the app does anything at all.

**Comment by maxreb** [comment]
The "Risikoermittlung" is active since 5 days, the app shows that when I click on "Risiko-ermittlung aktiv" in the home screen.

**Comment by duke2906** [comment]
I am using an Huawei P20 Pro, the first days it worked fine. Not I opened the app to show a friend how it looks like.
It says "Risiko-Ermittlung nicht möglich", "Ihre Risiko-Ermittlung konnte seit mehr als 24 Stunden nicht aktualisiert werden."
Last check seems to be 3 days ago, 18.06. afternoon.
When klicking "Risiko-Ermittlung einschalten" a screen opens where the setting is activated ofcourse, and it says that it is activated since 5 days.

I just disabled automatic power-saving for this app, as told in FAQ. I´ll give an update if something will change.

**Comment by github-normalnutzer** [comment]
Warum muss man um einen Fehler in einer Deutschen APP die nur in D verwendet wird, in Englisch schreiben?
Warum gibt es bei so einer (hoffentlich) wichtigen APP außer einer Hotline und einer kleinen FAQ keinen Deutschen Support?
Egal...es gibt wichtigeres.
-----------------------

Happend on two Honor 9 devices, 
since installing the app 5 Days ago,
it stays at "Unbekanntes Risiko" 
No error warnings, all asked permissions are granted.
Including camera access, which i don't understand the need right now.
Accu optimizations for the app are checked and turned off.
APP Start options already set to "Manuell verwalten" 
and all three Options (Auto Start/Sekundärer Start/Im Hintergrund) are ON

I have noticed that for example, in the accuusage screen,
 WhatsApp stays as activ in the system after swiping it out.
Instead of the Corona App which shows inactive after swiping it out.

Don't know what to check next?

**Comment by lor-enz** [comment]
I believe this issue is due to aggressive battery optimization strategies of the custom Android OS employed by some manufacturers.

How to fix: Disable battery optimization for the Corona Warn App. 
If you are unsure how to do this, search for your phone model and 'disable battery optimization'

https://dontkillmyapp.com
This site tries to put more attention on this topic. Previous comments mention using Huawei or Xiaomi phones. Those are listed with some of the most negative scoring regarding this issue.

**Comment by queequac** [comment]
@lor-enz I would agree... but read above, I turned off any battery optimization and explicitly allowed MIUI to let the app run unrestricted, so this should no longer apply. (And this usually works for other apps that have problems to run in the background.)

**Comment by jakobmoellersap** [comment]
Hi! Thanks for your issue description. Could you check the Version of the App? There might be an update that solves the issue for you with 1.0.4

**Comment by maxreb** [comment]
Hey Jakob. Updated to 1.0.4 and now it seems to work immediately. It says "Niedriges Risiko" and show me that it was 5 out of 14 days active.
