### ISSUE TITLE
API aktualisiert Begegnungen nicht

### ISSUE THREAD

**Issue by AndroidFire9704** [corona-warn-app/cwa-app-android#696]
In den Google Einstellungen wird werden 0 Überprüfungen angezeigt und in der App selbst das diese heute früh überprüft worden sind.
![Screenshot_20200621-105241](https://user-images.githubusercontent.com/16021531/85220699-14a10600-b3ae-11ea-9a0f-10cab0feb2dd.jpg)

**Comment by nilsalex** [comment]
Devs should verify that, but I think that "0 Überprüfungen in den letzten 14 Tagen" in you screenshot means that there have been no calls to the API for assessing the risk of exposure. This is plausible, because up to now there is no bundle of diagnosis keys available. Just try getting all dates with available keys:
https://svc90.main.px.t-online.de/version/v1/diagnosis-keys/country/DE/date

Now, the indicator in the actual app (cwa) should mean that the app checked for keys, found none and thus shows "low risk".

**Comment by daimpi** [comment]
related (reason why there might be no keys as of now): https://github.com/corona-warn-app/cwa-documentation/issues/236#issuecomment-646505696

**Comment by gizmo21** [comment]
Don't even have those lines in my options in android 6.0.1 
![774bafa0-eb4c-4899-a502-fa059e687826](https://user-images.githubusercontent.com/2779732/85231879-1349fa80-b3fb-11ea-8930-9a31a84a01fb.png)

**Comment by MikeJayDee** [comment]
Me neither (Pixel 2, Android 10).

**Comment by daimpi** [comment]
Me neither (Galaxy S8, Android 9)

**Comment by tkowark** [comment]
Yes, indeed that observation is related to the fact that no keys are currently being distributed by the server and hence no calls to the API are being made (https://www.coronawarn.app/de/faq/#no_log_check).
