### ISSUE TITLE
Request for daily updates on Issue #478

### ISSUE THREAD

**Issue by schuhmi2** [corona-warn-app/cwa-app-android#711]
While the community understands that Issue #478 is a hot topic, and we are no longer able to post there, would it be possible to get a daily update posted on that thread (or somewhere else) providing us with any updates, even if it's just "nothing new today".
This would help reassure the community that it is not lost or forgotten.
Thx

**Comment by ironjan** [comment]
You could subscribe to #478](https://help.github.com/en/enterprise/2.13/user/articles/subscribing-to-and-unsubscribing-from-notifications). This will send you an email whenever something happens at #478 (e.g. a new maintainer comment or the issue gets closed). A daily "nothing new" is not really useful and only causes more work (which could be spent on solving #478 instead of reporting on the status of #478). 

(Not a maintainer, just a recommendation)

**Comment by schuhmi2** [comment]
@ironjan sub already done.
I have (bad) experiences from other projects where daily updates (no matter what) were not published, and as such, tickets and issues went under and were forgotten about. Since the severity of this is high, this shouldn't be allowed to happen here.
(also, its 15 seconds work to go to, type 'nothing new' and click comment)

**Comment by tkowark** [comment]
Thanks @schuhmi2 for the suggestion and if it would have taken longer, we definitely would have given regular updates. But thankfully, after working extensively in the background to solve this issue with the RKI, we now finally have an official statement to share (https://github.com/corona-warn-app/cwa-app-android/issues/478#issuecomment-648742144). Future updates on the matter will be centralised in corona-warn-app/cwa-backlog#9.
