### ISSUE TITLE
Crash with "Ursache 4000"

### ISSUE THREAD

**Issue by speedy-1702** [corona-warn-app/cwa-app-android#712]
## Describe the bug
After restarting the phone and clicking on cwa, immediately crash report appears on my phone.
See details in screenshots
![grafik](https://user-images.githubusercontent.com/1996354/85287034-fc0b1b80-b493-11ea-8a36-faa11f564ff7.png)
![grafik](https://user-images.githubusercontent.com/1996354/85287075-0a593780-b494-11ea-9784-c5eb594bc659.png)
![grafik](https://user-images.githubusercontent.com/1996354/85287126-1ba24400-b494-11ea-9951-291b413050f0.png)

## Expected behaviour
no crash

## Steps to reproduce the issue
not reproducable

## Technical details

- Mobile device: HUAWEI P30 lite
- Android version: 10.0.0.197

**Comment by jakobmoellersap** [comment]
Thanks for your bug report. this comes due to a UnknownHostException that could have happened due to a network reset or a problem during the establishment of the connection. This is not a real "crash" and will not affect App functionality once your standard internet connectivity is restored. Sometimes this can be caused when your phone is connected to WiFi but your WiFi has no connectivity towards the internet.
