### ISSUE TITLE
Ursache:9002 Etwas ist schiefgelaufen 

### ISSUE THREAD

**Issue by Keuleriker** [corona-warn-app/cwa-app-android#778]
Gerät: Honor 10

Mitteilung: file is not a database: , while compiling: select count (*) from sqlite_master;

**Comment by tkowark** [comment]
Thanks for your report. This error is already being worked on in #642

**Comment by vaubaehn** [comment]
Hi @Keuleriker  , it's quite a while since you reported this bug:
**"Ursache 9002 - File is not a database: ,while compiling: select count (*) from sqlite_master;"**

As far as I know, the root source for this exception is not known yet.
I came across the information, that the problem often occurs with Huawai and Honor devices.
One similar feauture of many of these devices is the PrivateSpace feature (Huawai/Honor specific privacy app & data storage container; see [here](https://consumer.huawei.com/de/support/content/de-de00746116/), [here](https://consumer.huawei.com/de/support/content/de-de00722628/), [here](https://www.giga.de/smartphones/huawei-mate-9/specials/top-10-tipps-zur-emui-5.0/page/2/), or [here](https://www.honornews.de/tweaks/privatespace-fur-mehr-privatsphaere/)).

Did you ever use or ever enable PrivateSpace for your phone, or might it have been preconfigured to be active when you bought it?

Are you still using CWA, with the newest version 1.2.0? If yes, is the error still persisting for you? Or is it gone?

A reply to these questions may help to get an idea, if PrivateSpace might be related to the issue you experienced.

Thanks very much in advance, kind regards,
V.
