### ISSUE TITLE
Derzeit gibt es in deinem Land keine App zur Kontaktaufzeichnung

### ISSUE THREAD

**Issue by quaddy-services** [corona-warn-app/cwa-app-android#830]
Suchergebnis im Play Store

![Screenshot_20200707-082607](https://user-images.githubusercontent.com/2789123/86727490-c6396b80-c02b-11ea-82c3-3e73595a478b.png)

---
Internal Tracking ID: EXPOSUREAPP-1978

**Comment by tkowark** [comment]
Hi @quaddy-services , the app is currently only available in the app stores mentioned here:
https://www.coronawarn.app/en/faq/#international

For some of those, there is also a play store review pending, which prevents them from showing up.
If your app store is one of the ones mentioned in the FAQ, we kindly ask for your patience.

If it is not mentioned, please either add the country in the [cwa-wishlist](https://github.com/corona-warn-app/cwa-wishlist/issues/new?labels=country&template=03_additional_country.md) or upvote one of the existing issues.

**Comment by quaddy-services** [comment]
My app store is the german one.
Why is "The RKI currently released the app for the following European countries:" is not showing Germany?
Do I need to put germany to the wishlist?

**Comment by quaddy-services** [comment]
https://play.google.com/store/apps/details?id=de.rki.coronawarnapp
is available but Search does not find anything:
https://play.google.com/store/search?q=Corona-Warn-App&c=apps

> Keine Ergebnisse für deine Suche nach Corona-Warn-App
> 
> Vorschläge:
> Achte darauf, dass alle Wörter richtig geschrieben sind.
> Versuche es mit anderen Suchbegriffen.
> Versuche es mit allgemeineren Suchbegriffen.

**Comment by tkowark** [comment]
No, Germany is of course on the list. We just thought it would be superfluous information to mention that in the FAQ.

Thanks for the clarification. Interestingly, the app is displayed as a search result if I omit even a single character:
https://play.google.com/store/search?q=Corona-Warn-Ap&c=apps

We'll take this into the talks with Google but also have our app store admins check again what kind of SEO could be done from our end ...

**Comment by ironjan** [comment]
@tkowark I did a few experiments and whenever all three words "corona", "warn", and "app" were part of the query 
  * in their correctly written form, 
  * in this exact order, and
  * with no other words between, 
there was no result. It seems to me like the *exact* combination is somehow blocklisted.

The app showed up *first* with other variations: changing letters as you did, flipping words as in  "warn-corona-app" or "app-corona-warn", adding puffer words as in "corona warn rki app".   
Even reducing the queries to single words worked ("app" was the only one for which CWA did not show up first :D) or introducing extreme typos ("carina barn abb", 4th result).   
Note: my results may be skewed since I have the app installed.

**Comment by quaddy-services** [comment]
I can confirm:
corona-warn-app
no match

corona-warn
Several matches where rki app is the first:
![Screenshot_20200708-090638](https://user-images.githubusercontent.com/2789123/86888485-88efdf00-c0fa-11ea-827f-49a8377b916e.png)

**Comment by treysis** [comment]
This PlayStore message is sometimes misleading. It will also show the same text if your phone is running Android 5 or lower.

**Comment by GPclips** [comment]
Hello @quaddy-services and community,

to follow up, I like to ask if now the search is working for you?

Thanks,
LMM

Corona-Warn-App Open Source Team

**Comment by ironjan** [comment]
The issues described in
https://github.com/corona-warn-app/cwa-app-android/issues/830#issuecomment-655115495
are solved. The search term "Corona warn app" is not blacklisted (out
whatever the reason was) anymore. CWA can now be found as seen in the
screenshot.

GPclips <notifications@github.com> schrieb am Do., 1. Okt. 2020, 08:47:
