### ISSUE TITLE
Not available in the newly added countries (e.g. UK, ES, CH, etc.)

### ISSUE THREAD

**Issue by treysis** [corona-warn-app/cwa-app-android#834]
Despite official announcement from last week, the app is still not available in the local PlayStore of the newly added countries, for example UK, ES, CH.

This only affects the Android version. The iOS version is available in those added local AppStores since Thursday, July 2nd.

**Comment by tkowark** [comment]
Sorry, I was just about to give an update in the Switzerland issue, but had other tasks on my plate. Quick update:
* The review did not receive priority due to some internal issues
* Due to the public holiday, a quick fix was not possible
* We expect the app to appear in the respective app stores some time today

**Comment by treysis** [comment]
Public holiday? Do you mean July 4th? Somebody should fast track this issue. It's been pending for 5 days.

**Comment by tkowark** [comment]
Yes, July 4th. The issue was fast tracked yesterday, and as said, we expect a fix today.

**Comment by treysis** [comment]
Available now. Can be closed.
