### ISSUE TITLE
Ursache:9002 Etwas ist schief gelaufen

### ISSUE THREAD

**Issue by MarkusW89** [corona-warn-app/cwa-app-android#852]
Hab bei meinem Huawei P20 Pro das Problem "Ursache 9002"

File is not a database: ,while compiling: select count (*) from sqlite_master;

als Anhang die kompletten Details der Fehlermeldung

![1](https://user-images.githubusercontent.com/68109740/87153680-25abab80-c2b8-11ea-8206-ea78a984ea69.jpg)
![2](https://user-images.githubusercontent.com/68109740/87153668-217f8e00-c2b8-11ea-820e-da6c6d57e11e.jpg)
![3](https://user-images.githubusercontent.com/68109740/87153671-22182480-c2b8-11ea-9051-01a784c52895.jpg)
![4](https://user-images.githubusercontent.com/68109740/87153674-23495180-c2b8-11ea-809d-77beb8862fe8.jpg)
![5](https://user-images.githubusercontent.com/68109740/87153676-23e1e800-c2b8-11ea-8660-877959402e87.jpg)
![6](https://user-images.githubusercontent.com/68109740/87153678-25131500-c2b8-11ea-9590-74b067ca57e5.jpg)

**Comment by SebastianWolf-SAP** [comment]
That issue has already been reported. Please follow-up in #642 

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by MarkusW89** [comment]
Ok, Thanks 
I missed it, sorry

Kind regards 
Markus Wolff

**Comment by vaubaehn** [comment]
Hi @MarkusW89 , it's quite a while since you reported this bug: 

As far as I know, the root source for this exception is not known yet.
I came across the information, that the problem often occurs with Huawai and Honor devices.
One similar feauture of many of these devices is the PrivateSpace feature (Huawai/Honor specific privacy app & data storage container; see [here](https://consumer.huawei.com/de/support/content/de-de00746116/), [here](https://consumer.huawei.com/de/support/content/de-de00722628/), [here](https://www.giga.de/smartphones/huawei-mate-9/specials/top-10-tipps-zur-emui-5.0/page/2/), or [here](https://www.honornews.de/tweaks/privatespace-fur-mehr-privatsphaere/)).

Did you ever use or ever enable PrivateSpace for your phone, or might it have been preconfigured to be active when you bought it?

Are you still using CWA, with the newest version 1.2.0? If yes, is the error still persisting for you? Or is it gone?

A reply to these questions may help to get an idea, if PrivateSpace might be related to the issue you experienced.

Thanks very much in advance, kind regards,
V.

**Comment by MarkusW89** [comment]
Hi,

sorry for my late respond.
Yes i used the Privat Space on my Huawei P20 Pro and the newest version of CWA (1.3.1).

I deactivate now the Privat Space.

I'll test that and then get back to you

Thanks and kind regards 
Markus Wolff

**Comment by MarkusW89** [comment]
Hi @vaubaehn 

sorry for my late respond.
Yes i used the Privat Space on my Huawei P20 Pro and the newest version of CWA (1.3.1).

I deactivate now the Privat Space.

I'll test that and then get back to you

Thanks and kind regards
Markus Wolff

**Comment by MarkusW89** [comment]
Hi @vaubaehn,

deactivate the Privat Space was't succesful, but after the latest Update of CWA (1.5.0) it works since 6 days.

Thanks and kind regards
Markus Wolff
