### ISSUE TITLE
Replacing Volley based network stack with a OkHttp based one.

### ISSUE THREAD

**Issue by timo-drick** [corona-warn-app/cwa-app-android#89]
## Current Implementation
The current network stack is based on Volley using a requestQueue. For every request a complex class is defined which declares how the request should be parsed and some other boilerplate code. As far as i analyzed the code none of this requests is used in a asynchronous way. The WebRequestBuilder object do synchronize the requests so they can be used in a serial programming style using coroutines. Btw. a little bit misleading to call the functions e.g.: WebRequestBuilder.asyncGetKeyFilesFromServer because it is not a async call it is a synchronized call. ;-)

## Suggested Enhancement
Use OkHttp to do the network calls with a small layer of serialization helper (Kind of OkHttp rest class to make it easy describe requests in a simple function call) for ProtoBuf and json (Why do you mix JSON and ProtoBuf is this really necessary?).
I use this approach in many projects and the OkHttp helper class will only take about 100 loc. Maybe a little bit more supporting both JSON and ProtBuf and implementing a general error classification system. Than the WebRequestBuilder could be a class which defines a function for each call. We do not need a class for every request anymore.
Sample for this OkHttp helper class is here: https://gitlab.com/timod/compose-playground/-/blob/master/app/src/main/java/de/appsonair/network/RestJsonClient.kt

## Expected Benefits
- Reducing lines of code (Reducing boilerplate code for request definitions).
- Reducing complexity (We do not need to do asnychrouse calls and than synchronize them with suspendCoroutine continuation any more)
- The refactoring will not change the interface ob the WebRequestBuilder

**Comment by jakobmoellersap** [comment]
Hi there! I have a few remarks regarding your status update:

- In fact every request is sent asynchronously via a RequestQueue, which is in fact backed by a prioritised queue that is handled by a thread-pool inside the Volley Framework
- Coroutines are in fact not a serial programming style
- The methods are called async because they are in fact asynchronous

The calls towards these methods are in fact also asynchronous as they wait for the completion of the request (by being handled on a thread as the queue gets to it) before going forward. The only thing that is synchronous is the suspended building of the request objects inside the WebRequestBuilder. (which through the suspension, can also be handled asynchronously)

With these thoughts in mind I do not see any added benefit on adding OkHttp. If we want we can adapt the Request Queue to use an OkHttp Stack but this is currently not planned. Please let me know your opinion. Thanks for your detailed issue description!

**Comment by timo-drick** [comment]
Yes there is no benefit in terms of additional functionality. The only benefit would be less code. And less complexity. Which means less bugs less potential security issues.

**Comment by jakobmoellersap** [comment]
> The only benefit would be less code.

I checked your reference code again. The Helper Class is about 70 LOC (without Tests) like you mentioned, however I currently do not need any Helper Class in Volley to induce a JSON Request. Thus the error potential here is higher when we switch to OkHttp since I do not need to rely on a Helper. 

Regarding your initial comment:

> Maybe a little bit more supporting both JSON and ProtBuf and implementing a general error classification system.

I agree this needs to be done (specifically the error classification system), however this should be aligned also with the general exception handling method we use in our application and this is currently still WIP as mentioned in our docs.

_Maybe as additional context regarding the classes we use for building requests: We decided to use explicit RequestClasses for our most important HTTP-Calls to be more explicit about our call structure, but this is not yet final and could change._

Regarding the asynchronous Calls:

> Reducing complexity (We do not need to do asnychrouse calls and than synchronize them with suspendCoroutine continuation any more)

I tend to disagree here, as your call (referencing your helper class) just makes the HTTP Call synchronous, and we would thus need to rely on another way of spreading Requests on our ThreadModel and still wrap the actual calls with something like a fork-system or a queue (like currently implemented). In fact, if I look at the snippet of your helper you use the `client.newCall(request).execute()` method, which is in fact synchronous as you can see [in the okhttp docs](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-call/execute/) The only way to do this (to my knowledge right now, maybe I missed something) in OkHttp asynchronously is in fact by using callbacks, which would be then (just like now) be wrapped in a coroutine that suspends itself.

I rather reference an android native implementation than OkHttp and some own coding here to be honest (and we can switch to OkHttpStack in case of security issues down the line as a base handler), we thus do not limit ourselves at the moment.

All in all, I see more complexity in this stage of the project by introducing your change because we need to add helper functions, thread-managing code and still use blocking requests down the line (in the way you proposed), all that while still needing the tests for the actual purpose of the calls.

As always open for feedback! Thanks, Jakob 👍

**Comment by R4md4c** [comment]
I'd also recommend to use OkHttp, however not to replace Volley (even though it would be better since it has a nicer and more superior API (Interceptors, analytics etc...) ) but to use its Volley backend, for the following reasons:

* OkHttp is faster as it uses connection pooling, that means it reuses connections rather opening a new one each time we do a request. 
* Supports HTTP/2 protocol.
* Supports more recent security standards (e.g. TLS 1.3 which is supported from Android 10 under the native implementation)
* Finally and most importantly, depending on the native Android implementation means that if a security vulnerability arises on a specific Android version, users under that version are screwed. However by having an upgradable OkHttp artifact within the code you can mitigate such risks since you're just going to bump up the version that contains the fix.

**Comment by jakobmoellersap** [comment]
I think your mentioned concerns are valid and should be considered. I am currently considering a volley interface backed by an OkHttpStack

**Comment by jakobmoellersap** [comment]
Okay so after a some more investigation I conclude:

- TLS 1.3 Enforcement is possible on both Volley Native as well as an OkHttp backed Client
- HTTP/2 is only really used outside of queuing which is enabled by default by OkHttp
- OkHttp is more future-proof as it is maintained way more regular and volley is considered "finished"
- The Connection Pooling does in fact induce a little performance gain, although marginal for our scenario
- The last point struck with me. We should make sure that we are able to react to security faults within the HTTP Stack at will.
- I also checked again to see how much effort is needed for Certificate Pinning referenced in #7 , and in general pinning is possible in code for both solutions as well. In General I like the OkHTTP way of simply being able to include a SHA256 Base64 encoded Hash of the PubKey in the Pinning Management of the Client.

Close Call, but I am going for an OkHttp3Stack Wrapper using:
- inmemory connection management
- diskbased caching (10MB)
- Interface Extension based on Volleys BaseHttpStack
- Volley Request Queue
- Synchronous Calls

This way we have the best of both worlds while still staying flexible in both direction. As time is running out for a finished release, this will have to do as an intermediate solution that can be enhanced down the line.

I will tackle this in #117

**Comment by R4md4c** [comment]
@jakobmoellersap Sounds good to me! Perhaps after the first release (in case you're planning to do it), replace Volley completely with OkHttp since as you've mentioned Volley is "finished" and is the de facto standard Http client for Android apps.
