### ISSUE TITLE
android:installLocation="auto"

### ISSUE THREAD

**Issue by Lutzion** [corona-warn-app/cwa-app-android#90]

**Comment by marcauberer** [comment]
Just created a pr for this

**Comment by tklingbeil** [comment]
This issue was already raised here: https://github.com/corona-warn-app/cwa-documentation/issues/114

Storing the application on the SD card always bears the risk that it becomes unavailable due to the SD card being removed etc. However it is crucial that the Corona-Warn-App can regularly be invoked from the background to download new diagnosis keys and do the internal matching.
