### ISSUE TITLE
QR Code cannot be re-added after accidental deletion

### ISSUE THREAD

**Issue by daimpi** [corona-warn-app/cwa-app-android#960]
## Avoid duplicates
checked. This issue was reported under Android, I'm not sure whether this could also apply to iOS though. If this is the case feel free to move it to the documentation repo.

## Describe the bug
Somebody on Twitter asked me to post this for them: they recently got tested, entered the QR code in the App, but accidentally deleted it shortly afterwards. When trying to scan it again, they get an error. Now they can’t find out about their test result.

## Expected behaviour
After deleting the test, it should be possible to add it again without an error occurring

## Technical details

- CWA version 1.1.1

## Additional context
Twitter Thread: https://twitter.com/VerpissDichh/status/1289974550315204608

**Comment by thomasaugsten** [comment]
Hi unfortunately this is not possible. We have to ensure only one phone can scan the qr code and submit his diagnoses keys. We are not allowed to save an ID of the phone this is the reason why the qr code is only valid for one scan.
Please wait for the normal way (a letter via post mail or Gesundheitsamt calls you) of the test lab to get your result.

**Comment by vaubaehn** [comment]
@daimpi 
Do you know if there is any information shown to the user during the process of scanning the qr-code or before deleting, that after deleting the qr-code becomes invalid?
If not, it might be worth to ping maintainers/dev again, to ask for improvement of ux -> inserting warning that qr-code becomes non-reversible invalid after deleting, and user has to wait for the normal way after.

**Comment by daimpi** [comment]
@vaubaehn I unfortunately don't know what kind of warning message comes up in case you try to delete an entry, I was just forwarding this issue for someone on twitter. And yes I agree, that warning should at least make it **very** clear that deletion will be permanent and re-scanning will not work.

@thomasaugsten thanks for the explanation, could you maybe point us in the direction where to find the warning messages in case of an attempted deletion?

**Comment by thomasaugsten** [comment]
This is the current text of the alert
https://github.com/corona-warn-app/cwa-app-android/blob/fb7267d1bdfc843b04580e1e05ef926051feffeb/Corona-Warn-App/src/main/res/values-de/strings.xml#L810

**Comment by vaubaehn** [comment]
The warning message _is_ indeed **very** clear...

**Comment by daimpi** [comment]
Yes agreed 🙂. 

And if there is anyway a second line of notification via phone/mail to fall back on, it's also not the end of the world if someone actually deletes their result. I was afraid that this line might not exist, which would have been a much worse situation.

**Comment by SouhaibBenFarhat** [comment]
Just to add something here, it's not a user friendly experience at all to show the `Delete Test` as a main call to action button after scanning the QR code and at the same showing a very small line of text before scanning to tell users that the QR code is only usable once. I actually deleted the Test accidentally and know i'm stuck without a test result and I'm not allowed to take the flight because of that. Really sad but please improve this.

**Comment by MikeMcC399** [comment]
@SouhaibBenFarhat 
>  I'm not allowed to take the flight because of that.

I'm sorry to hear that you have had difficulties!

Are you saying that you wanted to show an airline a negative result from a PCR test using the Corona-Warn-App (CWA), so that you could fly? Was this an international flight and were you planning to fly from or to Germany?

The test result in CWA is not personalized. For the person being tested there is no:
- name
- date of birth
- address

contained in the test result, so it cannot be verified to whom the test result belongs. The test registration and result-delivery process with the app is deliberately (pseudo-)anonymous for data protection reasons.

See [example screenshot of negative test result](https://www.coronawarn.app/assets/img/screenshots/en/android/SubmissionTestResultNegativeFragment.png) from the [Screenshots page](https://www.coronawarn.app/en/screenshots/).

**Comment by dsarkar** [comment]
@SouhaibBenFarhat Thank you for contributing here. 

1. Of course it is unfortunate that you deleted the test accidentally. 
2. As @MikeMcC399 already commented, the functionality of the Corona-Warn-App to transfer Covid test result is anonymised, i.e. in general it will not be accepted as a negative PCR test result proof for travelling. 
3. You will typically get your test result additionally via email, also typically it should include at least full name and passport number for the purpose of travelling. I would suggest you, to contact the test centre where you have done the PCR test and confirm with them that you need this document for travelling purposes. 

Best wishes, DS

---
Corona-Warn-App Open Source Team
