### ISSUE TITLE
 Corona-Warn-App/src/main/res/values/strings.xml: adjust update interval

### ISSUE THREAD

**Issue by schweer-guest** [corona-warn-app/cwa-app-android#980]
* [x] None of the other issue templates apply to this issue.

"The exposure check is performed automatically about every two hours." should rather be:
"The exposure check is performed automatically each day." or some such.
And then, all translations need to be fixed...

---
Internal Tracking ID: EXPOSUREAPP--1997

**Comment by MikeMcC399** [comment]
This issue has not been addressed.

CWA three-dot menu > Overview still contains the following text under 
### Definition of Terms
#### Exposure Check
<string name="main_overview_body_glossary_calculation">"Exposure log data is retrieved and synchronized with reported infections of other users. The exposure check is performed automatically **about every two hour**s."</string>

So far, including with the current version 1.5.1, exposure checks are performed automatically once a day, not every two hours.

https://github.com/corona-warn-app/cwa-app-android/blob/master/Corona-Warn-App/src/main/res/values/strings.xml
Line 282

`<!-- YTXT: App overview body for glossary risk calculation -->`
`<string name="main_overview_body_glossary_calculation">`

**Comment by dsarkar** [comment]
Hi @schweer-guest, @MikeMcC399,

Thanks for your contributions. This issue is fixed, text is now:
`<string name="main_overview_body_glossary_calculation">"Exposure log data is retrieved and synchronized with reported infections of other users. Your risk is checked automatically several times per day."</string>
`

We will close this issue now. Best wishes, DS

---
Corona-Warn-App Open Source Team
